vuejs/docs

src/guide/components/registration.md

This PR just changes the closing quote to match the opening quote. The current code is invalid.
This was originally included in #1461, but that PR combined a number of disparate changes that have made it tricky to merge. This PR splits off this one change so we can get it merged.

Fix mismatched quotes in import

---

src/guide/essentials/component-basics.md

There's a minor grammatical error in a sentence.
Add the word "at".

Fix a grammatical error in the docs

---

src/guide/essentials/lifecycle.md

> Do note this doesn't mean that the call must be placed lexically inside `setup()` or `<script setup>` - `onMounted()` can be called in an external function as long as the call stack is synchronous and originates from within `setup()`.
The dash in this sentence makes it look like it's `<script setup>` - `onMounted()`, when in fact they should be separate.
To improve clarity and flow of the sentence, I suggest using a fullstop instead.

Improve clarity of a sentence in the "Lifecycle Hooks" section of the docs

---

src/guide/extras/web-components.md

There was a typo, it should be `detail` instead of `details` 
Adjusted it
https://github.com/vuejs/core/blob/5898629d723e82b68e9b17b91bf8b1a8390a3912/packages/runtime-dom/src/apiCustomElement.ts#L341-L347

fix: update typo in `web-components.md`

---

src/guide/essentials/reactivity-fundamentals.md

> It also means that when we assign or destructure a reactive object's property into local variables, or when we pass that property into a function, or destructure properties from a reactive object, we will lose the reactivity connection:
In the above sentence, "or destructure properties from a reactive object"  is redundant and may cause confusion.
Remove the redundancy:
> It also means that when we assign or destructure a reactive object's property into local variables, or when we pass that property into a function, we will lose the reactivity connection:
It will make the explanation better match the code example.

Remove redundancy in reactivity-fundamentals.md

---

src/guide/essentials/event-handling.md

This PR does two minor fixes: 
- adds a missing punctuation mark at the end of a sentence
- removes a pair of unnecessary backticks

Fix punctuation mark typos

---

src/guide/essentials/component-basics.md

While copying example code at section component basic, I found missing comma at example `src/guide/essentials/component-basics.md`.
Add an comma 😁

fix: missing comma at example src/guide/essentials/component-basics.md

---

src/tutorial/src/step-8/App/template.html
src/tutorial/src/step-8/_hint/App/template.html
src/tutorial/src/step-8/description.md

Removed "closing" forward slashes in empty html (input) elements.
I was working through the new Vue tutorial in the docs and noticed that on example 8, Computed Property, there is an error rendering the preview window, `Cannot read properties of undefined (reading 'done')`, after pressing the 'Show Me' button for a solution. I noticed that in the "app" div element of the index.html in the REPL there is an unnecessary closing `</input>` tag after the first `<input>` tag, and an early closing `</ul>` tag after the next `<input>` that is in the `<li>`. The early closing `</ul>` tag appears to be causing the error in the preview. Manually deleting the closing </ul> tag in the REPL fixes the error in the preview.
Removing the closing forward slashes in the template.html file for both `<input>` …

update tutorial step-8 hint template.html

---

src/api/sfc-spec.md

Fixed this formatting error on [SFC Syntax Specification](https://vuejs.org/api/sfc-spec.html#pre-processors) page:

fix: correct Markdown syntax and broken links

---

src/api/reactivity-advanced.md

Fixes issue with `useDebouncedRef` function so it can be readily imported to a project.
The current docs do not indicate the complete code needed to implement the `useDebouncedRef`. 
Update the docs to include the import statement and default function export.

Docs: Update to useDebouncedRef code

---

src/guide/scaling-up/ssr.md

The `<button>` element is already used in the example above. This commit updates the next example, where a `<div>` is used instead.

fix example for consistency

---

src/tutorial/src/step-2/description.md

The "state" object is inconsistent with the other parts of the tutorial, the object should be "counter" instead.
Change "state" object to "counter".

Update inconsistent naming in step-2 of the tutorial

---

src/api/composition-api-setup.md

Problem described in https://github.com/vuejs/docs/issues/1625
The solution is partial—fix the link. The other problems from the issue will still remain.

Fix broken 'ref-unwrapping-in-templates' link to

---

src/api/reactivity-utilities.md

This is my attempt at addressing the concern raised in #1567.
The API entry for `toRef` mentions using it to create refs from props. This change attempts to clarify that the usual restriction on not mutating a prop still applies, using `toRef` is not a fix for that.
I've also made a few other tweaks to this entry:
* It said `string` when it meant `number`.
* An example wasn't importing `toRef`. Usually I wouldn't show the imports, but given the `<script setup>` tag was shown, I felt the import should be shown too.
* The final note about using `toRef` with optional properties was added back when props did not include omitted values. That has since been changed, so props now includes all props, even if they aren't passed. I've reworded that note to avoid mentioning props.

Update API entry for toRef to mention mutating props

---

src/examples/src/cells/Cell/template.html
src/examples/src/circle-drawer/App/composition.js
src/examples/src/circle-drawer/App/template.html
src/examples/src/flight-booker/App/template.html
src/examples/src/form-bindings/App/template.html
src/examples/src/timer/App/template.html
src/examples/src/todomvc/App/template.html

Fixes #1634.
Several of the examples don't work correctly if the HTML/SFC switch is set to HTML.
The main problem is that `<input />` and `<br />` is transformed to `<input></input>` and `<br></br>`. For some examples this is harmless and just leads to strange-looking code, but for other examples it breaks the parsing, leading to incorrect rendering or an error.
Rather than fixing the transform I've just removed the unnecessary closing slash from those tags.
There were also a couple of problems with the Circle Drawer demo. These only applied to the Composition API version. Two things used in the template were not being returned from `setup`. In SFC mode this still worked because the `return` is stripped out by a transform, but in HTML mode that `return` needs to return the correct things.

Fix examples in HTML mode

---

src/api/composition-api-setup.md

we used `toRef` in Accessing Props section, but we didn't import it.
add `toRef` to list of imported properties from `vue` package.

fix: toRef is used without import

---

src/guide/scaling-up/state-management.md

obtrusive punctuation marks
Because there's nothing in front or back
remove obtrusive punctuation marks

fix: remove obtrusive punctuation marks

---

src/api/built-in-components.md

According to the TypeScript interface ([here](https://github.com/vuejs/core/blob/main/packages/runtime-core/src/components/BaseTransition.ts#L24)) the default mode is `default`.
This was missing from the docs.
So I added it to this API docs page.
However, this might **also** be useful to mention in the guide where it introduces the `mode` parameter/attribute ([VueJS.org](https://vuejs.org/guide/built-ins/transition.html#transition-modes) / [GitHub source](https://github.com/vuejs/docs/blob/main/src/guide/built-ins/transition.md#transition-modes)). So developers know what to use for the default behaviour (if you have to set it explicitly).
It might seem obvious when you *know* the default value is `default`... but otherwise you might try an empty string, or `'sync'` / `false` / null / etc.

Added transition mode `default`

---

src/guide/essentials/reactivity-fundamentals.md

The [Reactivity Fundamentals](https://vuejs.org/guide/essentials/reactivity-fundamentals.html#reactive-proxy-vs-original-1) states on the limitations of [reactive()](https://vuejs.org/api/reactivity-core.html#reactive):
> Since Vue's reactivity tracking works over property access, we must always keep the same reference to the reactive object. This means we can't easily "replace" a reactive object:
```js
let state = reactive({ count: 0 })
// this won't work!
state = reactive({ count: 1 })
```
While this is great, I thought it could be expounded a little further to make the concept clearer.
Addresses https://github.com/vuejs/docs/issues/1630
Indicate the fact that the the reactivity connection to the first reference is lost when we re-assign a variable to a new reactive value.
Once a value …

Update reactive API limitation 2

---

src/api/built-in-directives.md

Reverts vuejs/docs#1571
Following discussion with @LinusBorg and others, it appears that the `^` shorthand isn't currently supported in the template compiler. While it almost works anyway, the attribute value is treated as a string rather than as an expression. It is not currently equivalent to using `.attr`.
The reason it almost works is because `.attr` is compiled into a `^` prefix, so using a `^` directly gives a similar result. Whether `^` was actually supposed to be used as a shorthand is unclear, so for now we're reverting the docs change. The documentation for `^` can be reintroduced if it gets proper support in the compiler.

Revert "Document v-bind.attr shorthand in API section."

---

src/guide/typescript/composition-api.md
src/guide/typescript/options-api.md

This PR attempts to address the problem raised in #1616.
The TS settings currently used by `npm init vue` require the use of the `type` modifier when importing types. So the following won't work:
```ts
import { ref, Ref } from 'vue'
```
This could be fixed using:
```ts
import { ref, type Ref } from 'vue'
```
However, this won't currently work in the SFC Playground. Details at https://github.com/vuejs/repl/pull/28.
The only syntax that seems to work in both cases is:
```ts
import { ref } from 'vue'
import type { Ref } from 'vue'
```
I'm not convinced this is ideal either. While it does work in all cases, I feel this is probably the least likely of the 3 options to be used in a real project.
In this PR I've switched the examples to use that last syntax. There aren't many examples that are …

Use 'import type' in TypeScript examples

---

src/api/application.md

chore: fix compilerOptions link error

---

.vitepress/theme/components/VueSchoolBanner.vue

Wrong banner height(Vue School Banner) leads to wrong nav-bar position
VueSchoolBanner.vue:
```
.has-top-banner {
--vt-banner-height: 80px;
}
```

fix: banner height error

---

src/api/reactivity-utilities.md

The link to type predicates in this page: https://www.typescriptlang.org/docs/handbook/advanced-types.html#user-defined-type-guards has been deprecated.
so it is replaced with a new link: https://www.typescriptlang.org/docs/handbook/2/narrowing.html#using-type-predicates
I will synchronize the translation work in Chinese.

fix: replace deprecated link

---

src/api/ApiIndex.vue

Fix #1542.
In Firefox, the `overflow` algorithm interferes with the `break-inside` property.

Fix layout inconsistency on Firefox

---

.vitepress/theme/components/VueSchoolBanner.vue

This PR updates the text of the Vue School top banner to announce the promo is extended for 48 hs.
Please merge this on `2022-05-01T00:00:00+02:00` (so, on the first minute of Sunday, or soon later).
The banner will stop appearing automatically on `2022-05-04T00:00:00+02:00`, the date is hard-coded.
[Click here to see screenshots of the banner](https://imgur.com/a/jp0BmUY)

Update Vue School banner copy

---

src/guide/components/registration.md

Fix #1638.
The first paragraph mentions that:
> A Vue component needs to be "registered" so that Vue knows where to locate its implementation when it is encountered in a template. There are two ways to register components: global and local.
Now that the content contradicts it, I wonder if we need to reword it, too.

Fix wording about component use with <script setup>

---

src/guide/quick-start.md
src/guide/typescript/overview.md

Links are not pointing to Vue publisher
Fix links to Vue publisher on vscode marketplace

migrate volar links to vue publisher

---

src/about/community-guide.md

The newly created (unofficial) Twitter community was missing from the community guide.
Add a link to the community to the guide.
I also fixed an uppercase/lowercase typo

added twitter community to the community-guide

---

pnpm-lock.yaml
src/tutorial/src/step-15/description.md
src/tutorial/tutorial.data.ts

404 errors on the links in /tutorials/#step-15 
- Quick Start
- Main Guide
- Examples
Changing the links from markdown based links `[]() to <a href="">` like in the previous steps
Tough unrelated, it is my first time committing to an open source.

Fix for #1691

---

src/guide/components/props.md

The Boolean missing prop will cast to false instead of undefined, https://github.com/vuejs/core/issues/5863#issuecomment-1118446966

Correct default value for Boolean absent props.

---

src/guide/best-practices/performance.md

https://bundle.js.org is moving to a new domain, namely https://bundlejs.com

docs: update bundle.js.org to bundlejs.com

---

src/guide/components/props.md

I spotted differences in the descriptions about the argument for prop default between composition/options API.
Composition API says:
```
// Object with a default value
propE: {
type: Object,
// Object or array defaults must be returned from
// a factory function
default() {
return { message: 'hello' }
}
},
```
Options API says:
```
// Object with a default value
propE: {
type: Object,
// Object or array defaults must be returned from
// a factory function. The function receives the raw
// props received by the component as the argument.
default(rawProps) {
// default function receives the raw props object as argument
return { message: 'hello' }
}
},
```
The difference seems to be introduced after
b0f5fff833c556f73672997693f11bfbe09031db
and
046ea54be8218ed495cf486e099cb652f8d1c068
These …

Align description about props default between composition/options API

---

src/api/built-in-directives.md
src/guide/extras/render-function.md

See https://github.com/vuejs/docs/issues/1649
Add a shorthand for `.attr` in the directives guide and a note on how to use modifiers in the render function
Close #1649

Added a note about prop modifiers on render function examples

---

src/guide/components/props.md

"The next section" does not seem to exist within the page.
I guess it is located in the same submenu -> Components in depth -> Fallthrough Attributes.
(/guide/components/attrs)
Add link and link text.
```
(which will be discussed in [its dedicated section](/guide/components/attrs)).
```

Fix reference to another page on Fallthrough Attributes

---

src/examples/utils.ts

The common IDE option like "Files: Insert Final Newline" in VSCode which add ending lines for files automatically when you save them, causes an additional empty line in the description comment from `description.txt` in examples.
Just trim the `desc` string in `src/examples/util.ts`
Original source file:
After saving it with the newline option in VSCode:
Then the render result:
After trimming the desc in `util.ts`:
Thanks.

Fixed rendering about ending lines in example desc

---

src/ecosystem/themes/themes.json

Themes page misses new themes from PrimeVue.
Adds new Poseidon and Verona themes from PrimeVue.

Add Poseidon and Verona themes for PrimeVue

---

src/api/ApiIndex.vue
src/api/api.data.ts

The API index page looks like this if we use custom anchors in pages, especially for translation websites that want to keep the English anchors with the translated text:
Extend `headers` from `string[]` to `{ text, anchor }[]` and process the text and the anchor separately.
https://github.com/vuejs-translations/docs-zh-cn/pull/294

Supported custom anchors in API index

---

src/api/ApiIndex.vue
src/api/api.data.ts

API Reference Page's filter with no result breaks page as described on #1759 
Fixed the data matching logic.
#1757

fixed API filter bug #1759

---

src/guide/components/events.md
src/guide/essentials/component-basics.md

Over the last few weeks I've encountered various examples of people misunderstanding some of the basics of component events. I've tried to address some of the potential sources of confusion in the two pages of the guide that introduce this topic: `component-basics.md` and `events.md`.
One specific problem is understanding the difference between `emit` and `$emit`: I've even encountered people who thought one or the other was a typo in the docs. As I understand it, when Evan rewrote the docs he chose to introduce `$emit` in the  `<template>` first, irrespective of which API people were using. `emit` was then introduced later, in the context of `defineEmits()`, as a way to emit events "in JavaScript", i.e. in the `<script setup>` section. This same approach to introducing the topic was used …

Various tweaks to how events are documented

---

src/guide/essentials/component-basics.md

#1713 raised a problem with the current wording, which refers to 'dynamic props'. It isn't clear what exactly that means, as both prop names and their values could be dynamic.
I've reworded that sentence to mention 'prop values', as well as making it slightly more explicit that the sentence is talking about the example above.

Reword passing of prop values to components

---

src/guide/scaling-up/testing.md

As of [this commit](https://github.com/testing-library/testing-library-docs/commit/ac0737e57af1b3b86cea039beef631e7e52b67f7) the testing library dependency for vue3 is the default one, so no need for the `next` tag.
Remove the `@next` tag from the the npm install command

Remove @next tag from @test-library/vue package

---

src/tutorial/TutorialRepl.vue

#1768
The tutorial route automatically adds the hash '#step-1' which creates a new history entry. This breaks the back button because every time we go back to the route without the hash it will automatically add the hash again.
Instead of changing the hash, replace the history entry

fix: tutorial breaks the back button

---

src/guide/extras/reactivity-in-depth.md

Fixes #1716.
`trigger` should be called after the value is updated, rather than before.

Reorder reactivity pseudo-code

---

src/guide/essentials/class-and-style.md

This change was first proposed in discussions on #1718, and replaces that PR.
The original suggestion was to replace the `:` with a `.`, but I felt that we could improve the wording to avoid the punctuation altogether.

Reword the introduction to class and style bindings

---

src/guide/built-ins/transition-group.md

Closes #1750.
The use of GreenSock is already noted in the guide to `<Transition>`, but the `<TransitionGroup>` page uses it without any explanation. This PR adds a note that GreenSock is being used.

Note the use of GreenSock in an example

---

src/guide/essentials/list.md

The docs claimed that `Object.keys()` is inconsistent across JS engines; this is not true in modern ECMAScript. The ordering is well-defined [in spec](https://tc39.es/ecma262/#sec-ordinaryownpropertykeys).
Made it clearer that the ordering is only inconsistent in legacy engines (especially IE).
I've done similar work in MDN docs. e.g. https://github.com/mdn/content/pull/17127

clarify that Object.keys is stable in modern ECMAScript

---

src/guide/scaling-up/sfc.md

Both "Single File Component" and "Single-File Component" were in the documentation
Change "Single File Component" to "Single-File Component" in the documentation to be more consistent with the usual rules for English hyphenation of compound adjectives.
See #1786 for an explanation (which clarified and reverted #1785)

Hyphenate Single-File Component

---

src/api/sfc-script-setup.md

An example within the docs potentially encourages a a11y unfriendly practice of adding interactivity to a non-interactive by default element
This makes a very small change to one of the examples given in the documentation.
There was a click handler on a `div` element as opposed to an interactive element such as `button`. This switches it to button simply to be consistent with best practices around accessibility
[MDN Article On Button Role](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/button_role#best_practices)

Update sfc-script-setup.md to align with best practices in accessbility

---

src/guide/quick-start.md

This is attempting to address the concern raised in #1722. I suggested a similar change on that PR, but it seems to have stagnated, so I've opened a new PR instead.

Add a note about Composition API usage to Quick Start

---

src/api/built-in-special-elements.md

This is an attempt to address the problem raised in #1783.
In brief, `<component :is="'input'" v-model="...">` won't work because the template compiler assumes it is a component `v-model`, not an `<input>` `v-model`.
#1783 attempted to address this in the guide. However, I think it would be better to address this in the API Reference instead. The API Reference already covers some other edge cases involving `<component :is>` that aren't directly mentioned in the guide. It also gives us the freedom to discuss the problem at greater length, without worrying about derailing the narrative flow of the guide.
In particular, the section of the guide that covers `<component :is>` comes before the section on component `v-model`, so it's trying to explain something that the reader isn't expected to …

Explain v-model with :is and native elements

---

src/guide/built-ins/transition.md

This adds the comment suggested in <https://github.com/vuejs/docs/pull/1767#issuecomment-1154643550>, clarifying that the CSS shown is not sufficient for a nested transition to work.

Clarify a partial transition example

---

src/guide/components/async.md

Attempting to address the problem described in #1782, I've added/extended some examples of async component usage. The main problem to be addressed is showing an example of how an async component is used in the `<template>`. This is described in the text, but it isn't currently shown.
The changes, in order, are:
1. Mention that slots are passed along, as well as props.
2. Show an example of registering an async component using `app.component()`.
3. Extend the existing Options API example to be a full SFC, including a template.
4. Add a roughly equivalent Composition API example.
I do have one concern about the Composition API example. Defining the async component inside `<script setup>` leads to a new wrapper component being created each time the parent component is created. While I would …

Extend the examples for async components

---

src/guide/essentials/list.md

The docs read 'Vue is able to detect when an reactive array's mutation methods are called and trigger necessary updates'.
This should read 'Vue is able to detect when *a* reactive array's mutation methods are called and trigger necessary updates'

Fixed a typo (changed an to a, due to consonant)

---

src/public/_redirects

Some links from v2 runtime warnings currently are broken like:
https://vuejs.org/guide/computed.html (should be https://v2.vuejs.org/v2/guide/computed.html)
https://vuejs.org/guide/list.html#key (should be https://v2.vuejs.org/v2/guide/list.html#Maintaining-State)
Some of them are already redirected to the v3 doc site, which I think inappropriate:
- https://vuejs.org/v2/api/#data -> https://vuejs.org/api/#data no such an anchor and relevant information there
- https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties -> https://vuejs.org/guide/extras/reactivity-in-depth.html no such anchor and relevant information there
- https://vuejs.org/v2/guide/components.html#data-Must-Be-a-Function -> https://vuejs.org/guide/essentials/component-basics.html no such anchor and relevant …

Update _redirects for existing v2 runtime warning links

---

.vitepress/theme/components/Home.vue
.vitepress/theme/components/SponsorsGroup.vue
.vitepress/theme/components/sponsors.ts

https://github.com/vuejs/docs/issues/1830
- Sharing sponsors' data loading logic to an independent ts file.
- Load the data into the home page.
- BTW, made the sponsor link target from `self` to `_blank`.

Support dynamic loading of special sponsors

---

.vitepress/theme/components/VueMasteryBanner.vue

Looks like there's already a CSS variable to properly handle banner z-index so I switched it to that.
closes #1846

Fix vue mastery banner z-order

---

src/api/component-instance.md

A small typo: "For consistency, **_its is_** recommended to use [template refs](https://vuejs.org/guide/essentials/template-refs.html)"
Just fixed it, removing the letter 's'
"For consistency, **_it is_** recommended to use [template refs](https://vuejs.org/guide/essentials/template-refs.html)"

Fixed small typo

---

src/guide/typescript/options-api.md

The Document URL is : https://vuejs.org/guide/typescript/options-api.html#typing-component-props
The caveats explaination of type inference problem need to update because it has been improved by TypeScript.
[TypeScript release notes 4.7](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-7.html#improved-function-inference-in-objects-and-methods)
[TypeScript PR #48538](https://github.com/microsoft/TypeScript/pull/48538)
Add additional instructions of TypeScript version.
No more.

Fix Caveats about props in TS with Options API

---

.vitepress/config.ts

Adding  `<meta name="theme-color" />` for the docs. For more info https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta/name/theme-color
I choosed #3c8772 as a theme-color hence it looks nice in dark mode and white mode too, and that colour in presents in VUE JS logo too.
_Sorry if I made any mistakes :(_

Adding `<meta name="theme-color" />` for docs

---

src/guide/components/attrs.md

There is an 's' missing at the end of 'reflect'...
Add an 's'.

Minor gramatical error in attrs.md

---

src/guide/components/attrs.md

Missing 'the' in attrs.md

---

src/about/team/TeamPage.vue

Shuffle team members like the v2 doc site.
Provide a `shuffleMembers()` function to process the data ahead.
It's on the TODO list of `@vue/theme`. However, now I feel it's better done here. Thanks.
https://github.com/vuejs/theme/issues/36

Shuffle team members

---

src/api/component-instance.md
src/api/composition-api-lifecycle.md
src/partners/components/PartnerHero.vue

fix typo and grammar mistakes

---

src/guide/essentials/watchers.md

This proposal is to remove the usage of the `indexOf` method when testing for the presence of a given character in a string. While `indexOf` is compatible with IE, `includes` is friendlier to newer JavaScript developers and it improves code readability.
`indexOf` is the legacy method of checking if a string contains a substring.
Removing usage of `indexOf` and replacing with `includes`

Swapping `indexOf` to `includes` in comparisons

---

src/about/team/TeamList.vue

Wrong sequence of team members info.
Client-side rendering only for shuffled team members.
#1880

Fix wrong shuffled team members info

---

src/partners/partners.json

The hiring link show error 404 due to missing protocol.
Add protocol to the link.

Fix hiring link of Vehikl

---

src/guide/essentials/forms.md

The multiline example uses the message ref for the v-model, so the example above "message" changed if we wrote something in the multiline section input.
change message ref in v-model and expression for multilineText(this one is not used anywhere so probably should be used there)

Change v-model for multiline example

---

src/guide/extras/reactivity-in-depth.md
src/tutorial/src/step-9/description.md

Incorrect usage of indefinite articles.
Change "a" to "an" before the vowel sound and vice versa before the consonant sound.

Fix indefinite articles usage

---

src/guide/extras/composition-api-faq.md

Currently Vue3 docs does not reffer to the composition api added in Vue 2.7
Added link to [Vue 2.7](https://blog.vuejs.org/posts/vue-2-7-naruto.html)

:memo: Composition api is available in Vue 2.7

---

src/guide/scaling-up/testing.md

I think the current example is wrong. It seems to render the component twice and uses different variable names for it (`Component` vs `Stepper`).
I guess the proper solution is to refer to the component as `Stepper`, like in the rest of the examples, and render only once.

Fix Testing Library example

---

src/guide/best-practices/performance.md

This is inspired by the change proposed in #1869.
In Vue 2, Vue Router used Async Components for the lazy loading of route components. However, in Vue 3 these are two similar but distinct features. The description in `performance.md` hasn't taken this separation into account.
The main change is to the paragraph describing the use of lazy loading with Vue Router. This has been updated to reflect the separation between these two features.
I've also tweaked an earlier paragraph to remove the word 'typically'. I think that was a little misleading in a Vue 3 context, as lazy loaded routes are more typical than explicitly using `defineAsyncComponent`.

Update the note about Vue Router and lazy loading

---

src/api/component-instance.md
src/api/options-state.md
src/api/reactivity-core.md

#1798 proposed adding information about `flush: 'sync'` to the main guide.
In my opinion, `flush: 'sync'` is an escape hatch that should be rarely used and is not something we want to encourage. Such features are typically only mentioned in the API reference, rather than the guide. I think mentioning it in an advanced guide would be fine (e.g. a detailed guide to the scheduler queue), but currently there isn't a suitable advanced guide where this topic can be covered.
The existence of `flush: 'sync'` is already mentioned in the API reference, but as far as I'm aware there isn't currently any explanation about what it does.
In this PR I've added a paragraph to `watchEffect()`, giving a brief explanation of `flush: 'sync'`. I have intentionally not given a lot of information or an example, …

Add a note about `flush: 'sync'`, with links from elsewhere

---

src/guide/extras/reactivity-in-depth.md

Changed `getter/setters` to `getter / setters` as in the following commit:
https://github.com/vuejs/docs/commit/c4ba9cb#diff-69907cc80676ccbf5f96eaeafae0365ca25493210a1fcaa5d6325cf02d59f834

chore: add spaces around slashes

---

src/guide/essentials/event-handling.md

Confusing and unnecessary method access `vm.submit()` in Key Modifiers section.
Replace `vm.submit()` with simple `submit` method name.

Fix confusing and unnecessary method access in comments

---

src/examples/src/circle-drawer/App/composition.js
src/examples/src/circle-drawer/App/options.js

now, will select A;
use reverse find circle from right

bugfix: circle A behind B, when a click both trigger them, should select B.

---

src/guide/extras/reactivity-in-depth.md

#1906 seems to have stalled, so I've made the proposed changes here instead.
***distinct*** seems like it should be ***distinctive*** instead.
***Component state are*** seems grammatically off, but it's tricky because we're equating a singular (state) with a plural (objects), making both ***are*** and ***is*** sound a bit wrong. I've attempted to dodge that altogether by changing it to ***consists of*** instead.

Small tweaks to the introduction of reactivity-in-depth.md

---

src/guide/extras/animation.md

This fixes the problem reported in #1899.
The final example in `animation.md` needs a slightly different template for the Options and Composition API examples. The Playgrounds already include this difference, but the code shown in the docs was sharing the same template.
The current template has been moved up, so that it is inside the `<div class="composition-api">`. A copy is now included inside the `<div class="options-api">`, with `tweened.number.toFixed(0)` changed to `tweened.toFixed(0)`.

Adjust an example template in animation.md

---

src/guide/typescript/composition-api.md

The section heading 'Takeover Mode' was recently renamed to 'Volar Takeover Mode'. This PR updates a link to reflect the new hash.

Update link to Takeover Mode

---

src/guide/essentials/event-handling.md

The word "clicks" is supposed to be in a possessive form in this context, and therefore apostrophe before the last letter "s" in that word is warranted.
Addition of possessive apostrophes, i.e. clicks -> click's.
Additionally added a comma before the word "while" since it is used to express the contrast between the two examples of modifiers.

Add missing possessive apostrophes

---

src/partners/components/PartnerList.vue

The "All partners" page is rendered randomly incorrect due to the shuffling logic.
Force render in client-side within `<ClientOnly>`
no

fix: partner shuffling bug in prod mode

---

.vitepress/theme/components/Home.vue

There's no description in platinum_china data.  Which caused the layout push to right by the `lead` span. We should keep the span next to img in order to keep the logo always center.
Also added `align-items: center` to keep texts in middle vertically.
ref: https://github.com/vuejs-translations/docs-zh-cn/pull/536

fix special sponsor layout problem on zh-cn doc.

---

src/guide/typescript/composition-api.md

Currently, we only mention `withDefaults` on the [API page](https://vuejs.org/api/sfc-script-setup.html#typescript-only-features) but not on the [guide page about Composition API with TypeScript](https://vuejs.org/guide/typescript/composition-api.html#typing-component-props)
Add `withDefaults` as a default option to the guide
Close #1843

Added `withDefaults` to Composition API TypeScript page

---

src/guide/quick-start.md

"Pre-requisites" is spelled with a hyphen, which is an uncommon spelling (this is also inconsistent with other pages, where hyphen is not used in that word).
The usage of the word "allows" is confusing in the specified sentence, which begins in a future tense. It makes more sense to omit the "s" at the end of it and make it "allow".
Pre-requisites -> Prerequisites
allows -> allow

Fix spelling and grammar

---

src/guide/components/slots.md

https://github.com/vuejs/core/issues/6549
Regarding [this issue](https://github.com/vuejs/core/issues/6549), the compiler doesn't inform what's the real problem with mixing named slot and default. This PR updates the documentation to explain how to avoid this error. The compiler error still needs to be clearer.
Provide an example on how to use default slots along named slots
—

docs: document mixing named and default slots

---

src/api/options-lifecycle.md

I added notes to `renderTracked` and `renderTriggered` as same as Composition API.
- [`onRenderTracked()`](https://vuejs.org/api/composition-api-lifecycle.html#onrendertracked)
- [`onRenderTriggered()`](https://vuejs.org/api/composition-api-lifecycle.html#onrendertriggered)

add notes in lifecycle hooks

---

.vitepress/theme/components/Banner.vue

This PR updates the top banner of vuejs.org to inform users about Vue School’s Free Weekend promotion.
The banner is closable and opens Vue School's site in a new tab. The banner will not reappear if a user has closed it (stored in localStorage following the repo instructions).
The banner has different phases, each with an end date. The copy, graphics and link of the banner depending on the current phase.
Here is the list of phases:
**Free Weekend subscription** (the current banner, no changes)
Ends 2022-09-30T23:59:59+02:00
Links to https://vueschool.io/free-weekend with UTMs
[Screenshots](https://imgur.com/a/oI41Ady)
**Free Weekend now live**
Ends 2022-10-02T23:59:59+02:00
Links to https://vueschool.io/free-weekend with UTMs
[Screenshots](https://imgur.com/a/GoUIk19)
**Special Offer** …

Update Free Weekend Vue School banner

---

.vitepress/theme/components/Banner.vue

This PR fixes the banner introduced in https://github.com/vuejs/docs/pull/1982
Now that the Free Weekend is over, this banner links to the promotion landing page (https://vueschool.io/sales/levelup2022) with UTMs and referal.
The title always says "Less than **48 hours** to get 45% off at Vue School" to avoid computing the remaining promo hours.
Thanks!

Update Free Weekend Vue School banner to point to offer landing page

---

src/guide/scaling-up/testing.md

Fix a typo within Tip example in Typescript configuration file.

fix: Typo in Typescript tip

---

src/api/utility-types.md

component state using the `v-bind CSS` function.
update
component state using the `v-bind` CSS function.

fix: typo v-bind CSS

---

src/guide/best-practices/performance.md

Since [vue-virtual-scroller](https://github.com/Akryum/vue-virtual-scroller) don't have types, it's necessary to introduce a new library.
[vue-virtual-scroller](https://github.com/Akryum/vue-virtual-scroller) don't have types.
Introduce a new library.

Add a virtual list library

---

src/guide/components/events.md

As-is, I did not immediately see the connection between `this.$emit('submit')` and the following code, `<MyComponent @some-event="callback" />` in the "component instance" example
I suggest changing the function name from `submit` to `someEvent` (and also possibly adding some extra HTML example code for added clarity)
I'm just learning Vue and was a little confused by this section in the docs. It's very possible I'm still confused, in which case, please disregard :)

Change emit example function name for clarity

---

src/guide/components/props.md

Reworded sentence about customizing the default behaviour of boolean props. 
Previous sentence ends up communicating that the built in behaviour is not desirable, which one would assume is not the case or it would not have been built in.
Mention how to customize the behaviour without implying that the default default behaviour is undesirable

Reword absent Boolean prop customization note

---

src/guide/best-practices/production-deployment.md

While translating `production-deployment.md` file in French, I came across "Reactivity debugging" that was tricky to translate because this concept was not clear to me and had to look for it on the internet to find the corresponding article.
I would suggest to add a link to the Reactivity Debugging doc, for users that didn't know about this concept like me. 
Linked to #2041

fix: add reactivity debugging link

---

src/about/team/TeamList.vue

Vue docs **`banner`** caused overlapping TeamList sticky info title ( e.g. Core Team Members ) under header ( VPNav )
https://vuejs.org/about/team.html
- `html.banner-dismissed`
- Use predefined `--vt-banner-height` CSS variable and CSS `calc()` for calculate correct **`top`** value for `sticky` position

fix: TeamList sticky info overlap

---

src/guide/essentials/computed.md
src/guide/essentials/conditional.md

add vs dot unified writing paradigm

fix: add vs dot unified writing paradigm

---

src/guide/essentials/watchers.md

Although it's mentioned that in Options API immediate watcher handler will run on component creation, it might be not instantly obvious that "created" hook will be executed after. Introduced few bugs before I realized it.
Maybe could be useful to explicitly mention in the guide that immediate watcher handler runs before "created" hook.

options api - immediate watcher handler runs before "created"

---

src/about/team/TeamList.vue

This is a tweak to #2043. The fix provided in that PR worked fine when the page had a banner (even if it was dismissed), but now the banner has been removed the variable `--vt-banner-height` is unavailable. This PR adds a default of `0px` (just using `0` doesn't work).
This impacts the sticky header sections on the Team page.

Fix Team sticky headers

---

src/guide/essentials/class-and-style.md

https://github.com/vuejs/docs/pull/2049#issuecomment-1304735799
removed duplicated `{#xxx}`

fix: duplicated id for some headings (#2049)

---

src/guide/scaling-up/testing.md

these matched the current online anchors.

add missing anchors in testing.md

---

src/api/reactivity-utilities.md

The `isReadonly()` function will return `true` for a `computed()` ref that doesn't have a `set` function. That isn't currently mentioned.
I've added a brief description of what it means for an object to be 'readonly', otherwise the list that follows may seem a bit arbitrary. I've then included `computed()` refs in the list of things that are readonly.

Add computed refs to isReadonly

---

src/api/ApiIndex.vue
src/api/api.data.ts

<https://vuejs.org/api/> is currently showing the wrong text for API entries. It should be showing the heading text but instead it's showing the anchor string. e.g. `app-mount` should say `app.mount()`.

Fix API index heading text

---

src/translations/index.md

French translation docs is missing.
Here the link for getting the link from the english version.
We need to translate the current version of [fr.vuejs.org](https://fr.vuejs.org) to [fr.v2.vuejs.org](https://fr.v2.vuejs.org). The repo responsible of the current version is https://github.com/vuejs-fr/vuejs.org.
Check-up list before merge:

feat: add french translations repo link

---

src/about/team/members-partner.json

My company has passed by a rebranding from [Airbank](https://www.joinairbank.com/) to [Friday Finance](https://www.fridayfinance.com/).
The `/about/team/members-partner.json` has been updated with the change.
N/A.

chore: update partner's company after rebranding

---

src/examples/src/todomvc/App/template.html

There is a missing space, which wrongly concats the {{ remaining }} value and the 'item'/'items' word.
Added spaces

Add space in TodosMVC example

---

src/api/application.md
src/guide/scaling-up/tooling.md

The plugin Vue packages are being moved from the Vite core monorepo to individual packages:
- https://github.com/vitejs/vite/pull/11158
New repository for `@vitejs/plugin-vue` and `@vitejs/plugin-vue-jsx`:
- https://github.com/vitejs/vite-plugin-vue

chore: update plugin vue links

---

src/guide/extras/web-components.md
src/guide/scaling-up/ssr.md

The ssr-vue playground link is still valid, but this may change in the future so it is better to already point to the new plugin-vue repository.
I also missed one link in the prev PR.

chore: update link to ssr-vue playground

---

src/api/composition-api-setup.md

Currently we don't have any information in the docs regarding the fact that normally, `setup()` should always be called synchronously. This raises questions from users who try to call `async setup()` and fail.
Add a warning to `setup()` docs
Close #1032

Added a warning regarding async setup

---

src/about/team/members-core.json

The issue found is the portal-vue URL under Linusborg leading to a 404 page.
The proposed solution - remove the * at the end of the URL.
Thanks!

Fix broken portal-vue link

---

src/guide/essentials/template-syntax.md

The singular possessive adjective "its" in the given sentence refers to the plural subject "boolean attributes".
Change "its" to "their" so that it matches "boolean attributes".

Fix a grammatical error

---

src/guide/essentials/reactivity-fundamentals.md

Singular pronoun is used to refer to the plural "functions".
Change singular "it" to plural "them" so that it correctly matches "functions".

Fix a grammatical mistake

---

src/api/built-in-special-attributes.md
src/api/composition-api-dependency-injection.md
src/api/options-state.md
src/api/reactivity-core.md

Inspired by #2138.
I've added or updated entries in the **See also** sections in the API docs that link to the relevant TS guides. In each case I've included the TS badge and prefixed the link text with **'Guide -'**.
In some cases I've also added the **'Guide -'** prefix to other (non-TS) links in the same list, to ensure consistency within the list.
The file `utility-types.md` is also missing the TS badge from its **See also** links, but given that whole page is TS I didn't think it was worth adding it.

Links to TS docs from the API section

---

src/guide/essentials/template-refs.md

As mentioned in #2126, the example that introduces `defineExpose` doesn't currently mention that it shouldn't be imported. I've added a comment to try to address that.
From what I can tell, this is the first point in the guides that the concept of compiler macros is mentioned. We haven't yet introduced `defineProps` or `defineEmits`. I imagine a lot of people won't be clear what a 'macro' is in this context. This PR doesn't attempt to address that problem directly, though I have used the term 'compiler macro' rather than just 'macro' in the comment.

Add a comment about not importing defineExpose

---

src/guide/best-practices/accessibility.md

- CSS syntax is case-insensitive so it is better to use kebab case (skip-link) instead of camel case (skipLink)
- The anchor tag must have a class of skip-link

Add class to the Skip Link in the accessibility.md

---

src/guide/scaling-up/state-management.md

The singular noun "parenthesis" is used in reference to two parentheses that invoke a function.
Change the singular form to plural.

fix: change a singular noun to plural

---

.vitepress/config.ts
.vitepress/theme/index.ts

As discussed with @yyx990803 this PR will disable the Jobs widget in the header of the documentation pages.

Disable VueJobs widget

---

src/api/reactivity-core.md

This PR adds some extra examples for `watch()`. They are very similar to the equivalent examples for `watchEffect()`.
The inspiration for adding these examples comes from #2102. There were some consistency problems that made it difficult to merge that PR, but I believe the changes here should address the same gap in the examples.

Add more API examples for `watch()`

---

src/guide/components/events.md

Closes #1888.
The current wording is a little ambiguous. On first reading, it isn't necessarily clear which component (parent or child) is being referenced by the words 'the component'. Further, the words 'emitted events' could be interpreted as 'events that have been emitted', rather than 'events that will be emitted'.
This rewording attempts to remove the potential for misinterpretation.

Reword the opening sentence about declaring events

---

.vitepress/theme/components/SponsorsGroup.vue
.vitepress/theme/components/VueJobs.vue
.vitepress/theme/styles/vue-mastery.css
src/about/team/TeamHero.vue
src/guide/built-ins/keep-alive-demos/CompA.vue
src/guide/built-ins/keep-alive-demos/CompB.vue
src/guide/built-ins/transition-demos/CssAnimation.vue
src/guide/extras/demos/SpreadSheet.vue
src/guide/scaling-up/TestingApiSwitcher.vue

Working towards closing #1778.
The changes here were suggested by Prettier. It suggested various other things, but I've just picked out the least controversial changes. These should just be code-style changes, nothing that will impact what's actually shown in the docs.
I did make a manual change to `TestingApiSwitcher.vue`, around line 70. There were several lines of CSS handling a transition that were indented oddly. I believe that was caused by someone copy/pasting the code from their developer tools, including all the expanded sub-properties for `transition`. Prettier fixed the indentation issue, but I took it a step further and removed all the extra lines. Just a single `transition` should be sufficient.

Minor changes suggested by Prettier

---

src/api/sfc-script-setup.md

This PR is based on the conversation on <https://github.com/vuejs/core/issues/6242>.
Using `<script setup>` alongside a separate `<script>` tag was intended as an escape hatch for some specific use cases, as described in the docs. But in practice it has been used in various other ways that were not really intended. However, the tone of the docs does not currently discourage that kind of usage.
This PR makes some of the caveats more explicit.

Add caveats around mixing `<script setup>` and `<script>`

---

src/api/built-in-special-elements.md

Add `<template>` to the API docs alongside `<component>` and `<slot>`.
Closes #1849.

Add an API entry for `<template>`

---

src/tutorial/src/step-5/description.md

The sentence is structured in such a way that it is either missing a word or has words arranged incorrectly.
Current incorrect version:
_`v-model` works not only on text inputs, but also **[missing "on" here]** other input types such as checkboxes, . . ._
Correct version:
_`v-model` works not only on text inputs, but also **on** other input types such as checkboxes,_
The problem could be solved by adding the word "on" before "other input types" as shown above, but I chose to slightly rearrange the words of the sentence without any additions to get the same result and avoid repetition of the word "on".

Fix grammar

---

src/examples/src/modal/Modal/style.css
src/examples/src/modal/Modal/template.html

The enter transition doesn't work in Firefox:
<https://vuejs.org/examples/#modal>
It seems to be a result of using `display: table`.
I've switched to using `display: flex` instead. I've removed `<div class="modal-wrapper">` too, as I believe that was only required for the `display: table-cell`. Vertical alignment is now being handled by the `margin: auto`.

Fix the modal example transition in Firefox

---

src/guide/components/provide-inject.md

An injector component is called "injected component".
Change "injected" to "injector".
This is the only instance on the page where this expression is used instead of "injector component".

Fix wording

---

src/api/general.md
src/ecosystem/newsletters.md
src/guide/components/v-model.md
src/guide/reusability/plugins.md
src/guide/typescript/composition-api.md

Some headings have no anchors.

chore: add missing anchors

---

src/guide/best-practices/accessibility.md

The `id` used in the aria-labelledby attribute is duplicated.
Change the `id`'s to make them unique.

docs: fix aria-labelledby example.

---

src/about/releases.md
src/ecosystem/themes/ThemePage.vue
src/ecosystem/themes/themes.json
src/guide/best-practices/performance.md
src/guide/reusability/composables.md

The expression 'real world' should have a hyphen when it is used as an adjective.
real world -> real-world

docs: hyphenate 'real world' when used as an adjective

---

src/guide/typescript/composition-api.md

Existing code snippet gives this error:
Default export of the module has or is using private name 'Props'.ts (4082)
Error fixed thanks to:
https://github.com/johnsoncodehk/volar/issues/1232#issue-1213615569

Fix bad error inducing documentation

---

src/guide/typescript/composition-api.md

Reverts vuejs/docs#2191
My apologies for the confusion in this. While this does fix the issue at hand, we're trying work at a long term solution that would not require users to use two separate script blocks in order to resolve the error being raised.

Revert "Fix bad error inducing documentation"

---

src/about/team/Member.ts

`src/about/team/Member.ts` is missing `linkedin` property in `Social` interface definition. While the page still works as intended since the data are presented in `.json` files, TypeScript check in Visual Studio points out this error on `TeamMember.vue`, where the property is called.
Add missing element into interface definition.

missed element in TypeScript interface

---

src/guide/typescript/options-api.md

Fixing https://github.com/vuejs/docs/issues/2206
Link was broken
Changing link destination from
https://github.com/vuejs/core/blob/main/test-dts/componentTypeExtensions.test-d.tsx (404)
to https://github.com/vuejs/core/blob/main/packages/dts-test/componentTypeExtensions.test-d.tsx

Fix broken link in docs

---

src/guide/essentials/reactivity-fundamentals.md

> It says 'foo' is a top-level property.
> Fixed a typo in which it says 'foo' is a top-level property when the object is.

fix(reactivity-fundamentals): Ref Unwrapping

---

.vitepress/theme/components/SiteMap.vue

`SiteMap.vue` is currently causing errors in the translations because it relies on detecting the English text 'Ecosystem'. See #2209 and #2211 for details.
This PR changes the logic to detect the URL path rather than the text label. This should be stable across translations.

Make SiteMap.vue compatible with translations

---

src/guide/quick-start.md

at somepoint this note can be remove entirely but for now it's probbably current enough to still be useful
https://caniuse.com/?search=import%20map

docs: update not about firefox support for import maps

---

src/guide/typescript/overview.md

Broken link
Changed link from https://github.com/vuejs/core/blob/main/test-dts/defineComponent.test-d.tsx to https://github.com/vuejs/core/blob/main/packages/dts-test/defineComponent.test-d.tsx

Fix reference to `defineComponent` type tests

---

src/guide/typescript/composition-api.md

Typescript and Intellij cannot find exposed methods when using `InstanceType` for typed template refs:
The methods are exposed inside the Modal like so:
```
setup(props, { expose }) {
expose({
open: () => {},
});
// ...
}
```
Use Vue's `ComponentPublicInstance` instead of `InstanceType`:
```
import { ref, ComponentPublicInstance } from 'vue';
const modal = ref<ComponentPublicInstance<typeof MyModal> | null>(null);
```

fix: typing component refs

---

src/guide/extras/ways-of-using-vue.md

[Vuminal](https://github.com/ycmjason/vuminal) has already been archived
With Vuminal has already been archived, I suggest we replace it with a more active, maintainable Vue renderer for terminal apps, which is [Vue TermUI](https://github.com/vue-terminal/vue-termui)

docs(guide-extra): change terminal to `vue-termui` link

---

src/guide/essentials/class-and-style.md

Some code examples on [Class and Style Bindings](https://vuejs.org/guide/essentials/class-and-style.html#class-and-style-bindings) page use text `Hi!`, while others only `Hi`. Not a big deal, but since they are meant to render the same output, it should be corrected.
Added missing ones (2 of 5 occurences)

docs: missing exclamation marks in examples

---

src/guide/extras/rendering-mechanism.md

On https://vuejs.org/guide/extras/rendering-mechanism.html#static-hoisting (static hoisting section) there is 2 links which redirects to legacy netlify.app Vue Template Explorer app.
Use the official link (under template-explorer.vuejs.org)

fix: remove netlify template explorer link

---

src/guide/extras/custom-renderer.md

The page custom renderers is empty.
Link: https://vuejs.org/guide/extras/custom-renderer.html
The file `src/guide/extras/custom-renderer.md` should be deleted.

Remove custom-renderer.md from extra topics section (#2238)

---

.vitepress/config.ts

The Custom Renderers page has been moved to the API section. The link to the Extra Topics section is now useless. 
I don't know about the other two link : `Building a Library for Vue` and `Vue for React Devs`.
Remove the link in `config.ts`.

remove unused link for Custom Renderers (#2242)

---

src/guide/extras/reactivity-in-depth.md

New heading added by Evan miss ids for making sure ids are not lost during translations
Add the default english ids

fix: add missing id keys

---

src/guide/components/registration.md

Other pages in `Guide/Components In-Depth` (props, events and slots) have first the assumption about user knows the basics and then the VueSchoolLink (if it is provided). `Component Registration` is the only one where first comes the link and the assumption after.
Unless it was deliberate for some reason unclear to me, I suggest to re-arrange it to follow the same pattern on all pages.

re-arrange VueSchoolLink like on other pages

---

.vitepress/config.ts

This PR adds a banner fixed top banner to vuejs.org, to inform users about Vue School’s upcoming _free weekend_.
The banner opens Vue School's free weekend landing page in a new tab. The banner will not reappear if a user has closed it (a key is stored in localStorage).
This implementation uses an external script to render the banner. This file is hosted on the Vue School server. If you prefer to host the file on own your server, use this PR instead: https://github.com/vuejs/docs/pull/2275
For more info about how the script works, please check the documentation here: https://vueschool.io/affiliates/banner
[Click here to see screenshots of the banner](https://imgur.com/a/mO0TpsZ)

Add script to show the Free Weekend banner from Vue School

---

src/guide/built-ins/transition-demos/ListStagger.vue

Fixes #2280.
This bug was introduced by the recent removal of Reactivity Transforms from the demos in 1bc0434c0d81f4cd45d96874d0b8982d6e8c9175.
Fixed: <https://deploy-preview-2281--vuejs.netlify.app/guide/built-ins/transition-group.html#staggering-list-transitions>

Fix staggered list transition demo

---

.github/contributing/writing-guide.md

Fix minor language errors.
Replace "dumb" with "foolish" as the use of "dumb" may be taken as offensive by some people even though most people do not see this word as offensive.
Make emoji plural. The plural of emoji is both emoji and emojis, but emojis is used elsewhere in this document.

Fix minor language errors

---

src/guide/extras/demos/ElasticHeader.vue

The ElasticHeader demo is supposed to ping back when the drag ends, but currently it just freezes in place.
This bug was introduced by a recent change to remove Reactivity Transforms, 1bc0434c0d81f4cd45d96874d0b8982d6e8c9175.
Specifically, the problem is on line 44/45, where the first argument passed to `dynamics.animate` needs to be a reactive object. The animation is driven by changing that object, so passing a throwaway wrapper object doesn't work.
I reverted the code back to the Reactivity Transforms version and then changed `$ref` to `reactive`.
Fixed demo: <https://deploy-preview-2282--vuejs.netlify.app/guide/extras/animation.html#state-driven-animations>

Fix animated ElasticHeader demo

---

src/api/sfc-spec.md

Fix minor language issues
* Remove "at a time" which is redundant as "at most" is sufficient
* Replace "relevant tooling section" with the name of the section for better accessibility
* Make "Src" lowercase to be consistent with other use of tags and attributes in the Vue documentation, i.e. setup() and <script setup>

Remove excess words and fix minor language issues

---

src/about/releases.md

Previous code was pointing to the last release on github including prerelease, so was showing v3.3.0-alpha.5 for instance
The `/latest` endpoint should point to the correct version.
> The latest release is the most recent non-prerelease, non-draft release, sorted by the created_at attribute. The created_at attribute is the date of the commit used for the release, and not the date when the release was drafted or published.
[Docs](https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#get-the-latest-release)

fix: wrong stable version

---

.vitepress/config.ts
src/translations/index.md

Here we go, after #2289, French version has been also completed !
I would like to thanks a lot of people involved in that translation project:
- @tlagoda who work hard to make the translations finish and who improves his translation quality along his PRs!
- @8HoLoN who make hard work at the beginning of the project on the component section!
- @kissu, @marcbouvier and @Kamsou who served on examples, testing, accessibility and several big topics!
- and thank you @ElisePatrikainen, @aklipfel, @demahom18, @deraw!
The team was amazing and we wouldn't be here without them! 💕

feat: French translation is complete!

---

src/api/ApiIndex.vue

The text is breaking incorrectly across lines.
https://github.com/vuejs/docs/blob/859e90a1f2683b0d8312b43ad7f38fd9940dff05/src/api/ApiIndex.vue#L161
```css
.api-group {
padding: 24px 28px;
}
```

fix: Update padding to improve layout consistency

---

src/guide/typescript/composition-api.md
src/guide/typescript/options-api.md

This change is inspired by the suggestion in #2174.
The use of the word 'cast' does seem to match how it is commonly used in a TypeScript context. However, it does have a slightly different meaning in other languages, and the TS docs seem to stay clear of using that word.
However, the proposal in #2174 to change it to the word 'assert' seemed less natural to me, even if it could be seen as more technically correct.
Instead, I've tried rewording the whole sentence, aiming to make it sound more like something from the TS docs.
The same sentence appears in both pages about TS usage, so I've applied the same change to both.

Reword type assertions with events

---

src/guide/essentials/application.md

This change was motivated by #1864.
The section on using an in-DOM template begins by introducing it as a feature used without a build step. That is one use case, but it is also commonly used with server-side frameworks that generate the template HTML dynamically.
While `import { createApp } from 'vue'` can be used 'without a build step', it does seem less natural in that context. This was the problem originally raised in #1864. The idea of using import maps is discussed earlier in the docs, but this specific example leans on that knowledge more heavily than the rest of the docs.
Instead, I've started by introducing the feature without explicit motivation, contrasting it with the more common approach. I've then mentioned the use cases at the end, including a link back to the section about …

Reword the section on in-DOM root templates

---

src/guide/scaling-up/testing.md

As described in https://github.com/vuejs/docs/issues/2295, vue-testing-library has issued with testing async components with Suspense. We cannot recommend it over Vue Test Utils that deal with Suspense fine
Recommend VTU over testing library
Close https://github.com/vuejs/docs/issues/2295

Changed recommendation for testing library

---

src/guide/essentials/forms.md

Highlighted references for both Options/Composition api styles missing links to corresponding docs sections in tip note
Added links:
- https://vuejs.org/api/options-state.html#data
- https://vuejs.org/api/reactivity-core.html#reactivity-api-core

feat: forms.md added docs references in tip note

---

src/guide/quick-start.md

The latest version (`3.6.1`) of `create-vue` allows to select the end-to-end testing framework, suggesting 2 options: Cypress and Playwright.

docs: change the outdated option for end-to-end testing

---

src/guide/built-ins/transition-demos/ListStagger.vue

List staggering example only filters on lowercase inputs.
https://vuejs.org/guide/built-ins/transition-group.html#staggering-list-transitions
Make the query value also toLowerCase.

fix: non-case sensitive filtering

---

src/guide/reusability/composables.md

use `onBeforeUnmount` in `useEventListener` instead of `onUnmounted` since `onUnmounted` will not work if you trying to pass some element ref from the consumer component. Using the  `onUnmounted` the ref will be null since the component is unmounted, so we should use `onBeforeUnmount`
using will throw an error:
```
Cannot read properties of null (reading 'removeEventListener')
```
if you use Element ref
Use `onBeforeUnmount`, no remove the listener just before destroying the component

use onBeforeUnmount in useEventListener

---

src/examples/src/timer/App/composition.js
src/examples/src/timer/App/options.js
src/examples/src/timer/App/template.html

…, in the timer example. #2359

fix: add conditional judgment  when call update in the timer example. #2359

---

src/guide/components/props.md
src/guide/extras/reactivity-transform.md
src/guide/typescript/overview.md

The `#typescript-only-features` section in `src/api/sfc-script-setup.md` was removed at 914630259ee9c64539071d61b092b9590912eba7.

fix: removed anchor

---

src/api/options-misc.md
src/guide/components/attrs.md
src/guide/extras/composition-api-faq.md

Reference #2369 added some content.
The new defineOptions macro allows declaring component options directly in <script setup>, without requiring a separate <script> block according to vue 3.3

feat: update composition-api-faq.md

---

src/guide/essentials/reactivity-fundamentals.md
src/guide/quick-start.md

[Preview](https://deploy-preview-2396--vuejs.netlify.app/guide/essentials/reactivity-fundamentals.html) (**Make sure to toggle API preference to Composition API**)
Also closes #2328

Rewrite reactivity fundamentals CAPI to start with refs

---

.vitepress/inlined-scripts/restorePreference.js
.vitepress/theme/components/PreferenceSwitch.vue
.vitepress/theme/components/PreferenceTooltip.vue
.vitepress/theme/components/preferences.ts
src/guide/introduction.md

- Default style to Composition API. First-time users without a saved preference will see a tooltip (see screenshot below).
- Support specifying desired style via URL with `?api=composition` or `?api=options`
- Auto switch to proper API style if URL's target header is only available for a given API style. For example, when visiting `/guide/essentials/reactivity-fundamentals.html#ref` with saved preference set to Options API, the page will be displayed in Composition API. A tooltip will also be displayed to let the user be aware that the displayed style is different from their saved preference.
- API style choice enforced via URL persists for that session. This means:
- If the user navigates to another page without reloading, the API choice remains the same as what was specified by the …

API style switch enhancements

---

src/api/sfc-script-setup.md

With vue 3.3+, you can use `defineOptions` to define `name` etc.

docs(script-setup): updated outdated tip

---

.vitepress/config.ts
src/glossary/index.md

Deployed: <https://deploy-preview-2199--vuejs.netlify.app/glossary/>
The motivation is to help developers to understand what key technical terms mean in a Vue context. e.g. What is a 'compiler macro' or a 'fragment'? These are intended to be relatively brief introductions to the terms, with links to read more.
The main guide could link to these entries when a term is potentially unclear to the reader, though I haven't currently added any such links.
In some cases, the need for a glossary entry could be an indication that we need to do a better job of explaining a concept in the guide. However, the guide has its own specific role, and trying to clarify the exact meaning of a term can potentially derail the flow or require discussion of topics that haven't been covered yet. The glossary …

Add a glossary

---

src/guide/reusability/composables.md

I have seen some vue developers interpret the following from the ["Composables -> Usage Restrictions"](https://vuejs.org/guide/reusability/composables.html#usage-restrictions) section: when calling composables in a `<script setup>` or `setup()` context, you must call them synchronously. This is good, however feel like we may need to be clear that composables also should only be called in `<script setup>` or `setup()` regardless of whether they are a/synchronously called, and for the reasons described later in the section.
Change how the section is phrased to emphasise that composables, in all cases, only be called:
1. in `<script setup>` or `setup()` hook
2. synchronously
And/or start discussion about best practices about where composables can be called from.
We should discuss whether …

clarify restrictions on where composables can be invoked

---

src/guide/components/props.md

Example: https://jsfiddle.net/b4cyeht6
This works the same in Vue 2 and Vue 3.

Correct docs

---

src/guide/scaling-up/testing.md

Current testing docs only offer PW and NW as alternative solutions. WebdriverIO has released v8 which includes component testing and has dedicated docs how to get up and running when using Vue as framework.
Using JSDOM and JavaScript click events do not seem like a viable approach for testing component these days as they don't mimic user behavior at all. For example, clicks through `fireEvent` of `@testing-library/vue` do not recognise whether another element is blocking the access to an element. I've done a [whole set of experiments](https://github.com/webdriverio/component-testing-examples/tree/main/framework-comparisons) showing that using WebDriver which is a W3C web standard as automation protocol to mimic user behavior prevents stupid errors to pass through and also offers much more …

Add WebdriverIO as alternative

---

src/tutorial/src/step-9/App/composition.js
src/tutorial/src/step-9/App/template.html
src/tutorial/src/step-9/_hint/App/composition.js
src/tutorial/src/step-9/_hint/App/options.js
src/tutorial/src/step-9/description.md

The use of `p` as the variable name of a `<p>` element was a little confusing.
See https://github.com/vuejs/docs/pull/2270 for a justification for renaming this variable to remove ambiguity
This PR proposes `pElementRef` as the variable name and then this style can be used in other parts of the documentation, for example: [Template Refs](https://vuejs.org/guide/essentials/template-refs.html) for `<input>`, we could use `inputElementRef`

Replace the variable `p` with `pElementRef`

---

src/guide/essentials/reactivity-fundamentals.md

There is few situation where it miss the `\` symbol before the second star

fix: missing \ before second star

---

src/guide/components/provide-inject.md

Adds `true` as third parameter in the example indicating the default value should be treated as a factory function and adds explanation in text
Example seems incorrect
Update the example

Update provide-inject.md explaining `inject`s third parameter

---

src/guide/typescript/composition-api.md

Added an example showcasing the new way to define emits with types, that was introduced in Vue 3.3
Vue 3.3 introduced a new way to define emits with types, this was not documented in the docs.
Added an example for it in the docs.

Example for new defineEmit with types syntax.md

---

src/guide/extras/web-components.md

described in #2314 
Add a global components typings
Did not add react (JSX) exemple because it is more complex and less straightforward: we need to extract the the props/events from a vue component instance and THEN create a global component in JSX namespace https://www.typescriptlang.org/docs/handbook/jsx.html#intrinsic-elements

add guide to typecheck web components written with vue #2314

---

src/api/ApiIndex.vue

I want to deploy copy of docs to a non-root URL.
Wrap links to `withBase` helper.
https://vitepress.dev/guide/asset-handling#base-url

add base url support on api index page

---

src/ecosystem/themes/ThemeListItem.vue
src/ecosystem/themes/ThemeProduct.vue

Define props default values using withDefaults.

chore: defining default values for Props using withDefaults

---

src/guide/essentials/reactivity-fundamentals.md

The Reactivity Fundamentals section of the Essentials Guide includes a grammatical error, namely `Vue perform`
Change phrasing into `Vue performs`
Since this is my first contribution, I would like to receive feedback on the format of this PR, so if you have any remarks, please feel free to tell me. Moreover, I would like to know whether these type of minimal PRs are appreciated or should best be avoided for future PRs. Thanks in advance for the invested time.

Reactivity Fundamentals: Use third person singular for "Vue performs"

---

src/glossary/index.md

chore: fix links in glossary

---

src/guide/scaling-up/tooling.md

Currently the guide links to the Chrome extension, the Firefox addon, and the standalone app, but not to the Microsoft Edge extension.
Also link to the Edge extension, with the ordering of the different varieties consistent with that of https://devtools.vuejs.org/guide/installation.html

Tools: Link to Microsoft Edge extension page

---

src/guide/reusability/composables.md

The rest of this documentation page uses `onUnmounted` for removing event listeners, including the example this composable directly references. The API also suggests using `onUnmounted` for this purpose.
Update the example to use `onUnmounted` as well, for consistency with the rest of the page.

onBeforeUnmount to onUnmounted for consistency

---

src/guide/components/attrs.md

removes an old example that used to document using defineOptions without a setup but now says the same thing twice
The docs recommend using the defineOptions macro twice. Looks like it was changed in [PR #2384](https://github.com/vuejs/docs/pull/2384) to always suggest always using `<script setup>` but it didn't remove the second example. 
Remove the first example. (Could remove the other too though 🤷‍♀️ )

docs: remove duplicate defineOptions script setup example

---

src/examples/src/todomvc/App/template.html

This example was using a deprecated API (`@vnode-mounted`), so I updated it.
Change `@vnode-mounted` to `@vue:mounted`.

examples (todomvc): change `@vnode-mounted` to `@vue:mounted`

---

src/about/faq.md

removed the section in the FAQ page that mentioned the consider to use Vue 2 due to the lack of stable versions for major ecosystem projects like Nuxt or Vuetify. The information was outdated as there are now stable versions available.

docs(faq): remove outdated information about consider to use vue 2

---

src/examples/src/cells/Cell/template.html
src/guide/extras/demos/SpreadSheetCell.vue

`@vnode-*` hooks in templates are deprecated. Use the `vue:` prefix instead.
For example, `@vnode-mounted` should be changed to `@vue:mounted`. 
`@vnode-*` hooks support will be removed in 3.4.
Replace `@vnode-mounted` with `@vue:mounted`

docs: change `@vnode-mounted` to `@vue:mounted`

---

src/guide/built-ins/transition.md

The hook `onEnterCancelled` of `transition` component lacks a comment description.

docs: transition hook add comment

---

src/guide/quick-start.md
src/guide/scaling-up/tooling.md

For consistency across package managers.
`yarn` and `pnpm` only support the `create` subcommand. `init` means something different for them.
So using `create` leads to the least confusion if the user uses multiple package managers.

Use `npm create` instead of `npm init`

---

src/guide/typescript/overview.md

WebStorm 2023.2 has added integration for the Vue Language Service. I think it would be nice if the docs reflect this, similar to VsCode

docs: update IDE support page as WebStorm now supports Volar

---

.vitepress/config.ts
src/translations/index.md

Add translation link for bn.vuejs.org
Note: bn.vuejs.org hasn't deployed in live.
Repo: https://github.com/vuejs-translations/docs-bn
Discussions: https://github.com/vuejs-translations/guidelines/discussions/66

Add translation link for bn.vuejs.org

---

src/api/built-in-special-attributes.md
src/glossary/index.md
src/guide/built-ins/keep-alive.md
src/guide/built-ins/transition-group.md
src/guide/components/props.md
src/guide/components/registration.md
src/guide/essentials/component-basics.md
src/style-guide/rules-strongly-recommended.md

Update `DOM template` to `in-DOM template` to consist with the glossary table.

docs: consist usage of in-DOM template

---

src/examples/ExampleRepl.vue

Remove event listeners from the `Repl` when `unMounted` to prevent memory leaks.

perf: remove `resize` event listener when `unmounted`

---

src/guide/components/v-model.md

camelCase is being used in the example, not following the convention.
kebab-case should be used when event is being listened to inside parent's template.
#2503

Update v-model.md naming convention

---

src/guide/typescript/composition-api.md

Provide information and a place to find the right dom interface for a HTML element.
Always stumple about the point HTMLInputElement for two reason
- It's not mention what it is (DOM interface), i can't search when i doesn't had the name
- Where to look into to get this information so that i can look for other HTML elements
Solve the problem by calling it by it's name (i hope the right one) and
provide a example for Input element to provide a source and the place in the source.

add DOM interface info to Typing Template Refs

---

src/guide/reusability/composables.md

https://vuejs.org/guide/reusability/composables.html#accepting-reactive-state
The watchEffect should not modify data.value and error.value used in this example to avoid infinite re-computations.

Update Infinite Re-computation Issue in useFetch Composable Example

---

src/api/built-in-components.md

I think teleport component name should be capitalized on this page. Sincere sorry if I'm wrong.
Renaming <teleport... into <Teleport...

Update built-in-components.md. Rename <teleport> to <Teleport>

---

src/style-guide/rules-strongly-recommended.md

There is an inconsistency in naming. Sometimes it is called "In DOM", sometimes "In in-DOM"
Change "In Dom" to "In in-DOM" in two places as used in the rest of the document

docs: consist usage of in-DOM template 

---

src/about/faq.md

As noticed in #2538 the former link is no longer working
I found on [project GitHub page](https://github.com/krausest/js-framework-benchmark) what should be the new location of the benchmark table

fix: update dead link in FAQ

---

src/guide/best-practices/accessibility.md

`Other Helpful Tools` : the `Focus Indicator` extension is not valid. In doc we also have a alternative option for this extension. that why we don't need this extension anymore.
Focus Indicator: is removed from document 
After merge: it will be like below 
No

docs: remove broken link to focus indicator extension (closes #2530)

---

src/guide/typescript/overview.md

Update url for vue-tsc in overview.md

---

src/guide/components/registration.md

To be consitent with the rest of the guide, it should be displayed the method call (with the dot accessor) i.e.: https://vuejs.org/guide/essentials/application.html#mounting-the-app
In other parts of the guide, when application methods are described, the `.methodName()` is used instead of `app.methodName()`
remove the constant `app` from the method call

Remove the app constant name from the method name

---

src/style-guide/rules-recommended.md

The doc on https://vuejs.org/style-guide/rules-recommended.html#empty-lines-in-component-instance-options doesn't show the split between good and bad examples.
Add the missing divs with the proper classes.
N/A

docs: add missing div to seperate bad and good examples

---

src/guide/components/events.md

The `emits` object sintax support for Options API text was displayed for both, Options and Composition API.
It talks about `emits` options and the script shows the `defineEmits()` macro
Add spans with `options-api` and  `composition-api` class to display properly `emits` options or `defineEmits()` macro

Update events.md - Diff between Options API and Composition API text

---

src/guide/scaling-up/testing.md

`const button = getByText('increment')` is using getByText, which is not optimal. It also uses an exact match, which could give a false negative if we decide to change the character case of the button text.
getByRole validates the role of an element, giving us an extra free assertion
https://testing-library.com/docs/queries/about/#priority
It is not a critical change, but I appreciate testing-library, and want to educate people on how to utilize it better. Also, I hope Grammarly did a good job assisting me with catching typos 🤷‍♂️.

docs: use useByRole in example and fix typos

---

src/guide/essentials/watchers.md

The example code for `watch` may cause race conditions.
~~However, adding cleanup process makes the code complex and difficult to understand.
So I added a note.~~
↓
Disable the input field until the request is resolved.

Fix `watch` examples

---

src/tutorial/src/step-10/App/template.html

In the code for [step 10 of the tutorial](https://vuejs.org/tutorial/#step-10), there is an issue where rapidly clicking the button can result in the results not matching the id.
There are several possible solutions.
- Disable the button during loading
- Hide the button while loading
- Add a cleanup process.
As referred to in https://github.com/vuejs/docs/pull/2537, adding a cleanup process would require explaining more, which I'm concerned might deviate from the original purpose. 
Therefore, I believe one of the first two options mentioned would be preferable. 
In this PR, I tried fixing it in the direction of disabling the button, as initially suggested!
Behavior after the correction:
https://github.com/vuejs/docs/assets/71201308/bdc1b2bb-d2c3-47d7-9e11-4d54a700f702
If you have any …

fix(tutorial): race condition on step-10

---

src/api/reactivity-core.md

Example showing ref's value update uses `++` operator, I think that assigning new value is more common and personally i think that using `++` operator should be avoided in this kind of examples (unless you want to show that you can use this specific operator in some specific cases)
```diff
- count.value++
+ count.value = 1
```
```diff
- count.value++
+ count.value = count.value + 1
```
There could be also example with objects, like
```js
const data = ref(null)
data.value = { name: 'John Doe' }
```
Let me know if this should be added as well to this PR

fix: get rid of `++` operator in ref example

---

src/guide/scaling-up/tooling.md

https://github.com/vuejs/language-tools/tree/master/packages/vue-tsc – returns 404 page
https://github.com/vuejs/language-tools/tree/master/packages/tsc – Updated link
N/A

docs: fix link to vue tsc package

---

src/guide/components/events.md
src/guide/typescript/composition-api.md

Document typing parameters when using `emits` options syntax. 
Also document of declaring `emits` via `props`.

docs: added events as props and typing with object based emits

---

src/guide/essentials/template-refs.md

In Options API, the value of template refs before mounted is not `null` but `undefined`.

fix: initial value of template refs in Options API

---

src/guide/typescript/overview.md

See also https://github.com/vuejs/create-vue/issues/401

Note that verbatimModuleSyntax meets the suggested criteria for `isolatedModules`

---

src/guide/components/provide-inject.md

The docs still include a warning for temporary config prior Vue 3.3
Remove it

chore: remove outdated warning for reactive provide

---

src/guide/essentials/component-basics.md

The sentence contains a grammatical error as it uses "allow" instead of "allows," causing subject-verb agreement issues.
Replace "allow" with "allows" to maintain proper subject-verb agreement.

Correct minor grammatical mistake

---

src/guide/best-practices/accessibility.md

The landmark table showed "Not available" in the HTML column for the search landmark
I replaced it to show the `<search>` element, as it already defines the search landmark.

docs: replaces 'Not available' with 'search'

---

src/tutorial/src/step-5/description.md

In Step 5 of the tutorial, the verbiage "a syntax sugar" is used when referring to `v-model`.
This can be simplified to "syntactic sugar" to make it more grammatically correct, using the correct terminology.

Fix terminology and grammar

---

src/guide/typescript/composition-api.md

The documentation currently lacks explicit reference to the capability of `defineProps` to incorporate types from an external file. 
Also, users should be aware that adding `TypeScript` as a peer dependency is necessary for this feature to work.
Add documentation for when types for `defineProps` are coming from an external file

Update docs on usage of external types in defineProps

---

src/guide/typescript/overview.md

There is a broken inline code.

chore: fix backticks

---

src/examples/src/list-transition/App/composition.js
src/examples/src/list-transition/App/options.js

In the [List with transitions example](https://vuejs.org/examples/#list-transition), when you hit `button`, the array will revert to original `[1, 2, 3, 4, 5]`, but the `id` for newly inserted items remains.
So then 7 is inserted instead of logical 6 and so on. You can end up with stuff like that:
Would be more logical to reset the `id` value as well.
I added the command to do it in each API variant.

List transition example fix

---

src/guide/quick-start.md

Like [Nuxt installation](https://nuxt.com/docs/getting-started/installation) to have a better DX, I added pnpm, yarn and bun installation commands to the quick-start page.

feat: add pnpm, yarn and bun support in quick-start

---

src/guide/best-practices/accessibility.md

Previous link had a redirect to a privacy error, which could be confusing for users.
This adds in the URL that the previous URL was trying to redirect to, which bypasses the privacy error

fix: Update broken link in accessibility.md

---

src/api/options-misc.md

fix : delete meaningless paragraphs

---

src/api/built-in-components.md

For each of 5 built-in components there is a link to respective "Guide" page.
While four of them are written like "Guide - Component name":
The first one for `<Transition>` is different:
Change the displayed text to match the others:
Alternatively we could change the other 4 texts to be the same as for `<Transition>`, but it is more work, and I don't even think it looks better.

API - Built-in Components - unify "See also" links

---

.vitepress/config.ts

https://www.opengraph.xyz/url/https%3A%2F%2Fdeploy-preview-2633--vuejs.netlify.app%2F
Fixes: #2631

fix: og preview

---

.vitepress/config.ts
src/api/application.md
src/api/built-in-directives.md
src/api/compile-time-flags.md
src/api/composition-api-lifecycle.md
src/api/options-lifecycle.md
src/api/options-state.md
src/api/reactivity-core.md
src/api/sfc-script-setup.md
src/error-reference/ErrorsTable.vue
src/error-reference/errors.data.ts
src/error-reference/index.md
src/guide/best-practices/performance.md
src/guide/components/props.md
src/guide/components/v-model.md
src/guide/essentials/computed.md
src/guide/essentials/template-syntax.md
src/guide/extras/reactivity-transform.md
src/guide/extras/render-function.md
src/guide/typescript/overview.md

Includes:
- https://github.com/vuejs/docs/pull/2515
- https://github.com/vuejs/docs/pull/2568

3.4 updates

---

src/api/compile-time-flags.md
src/api/sfc-script-setup.md
src/guide/components/v-model.md
src/guide/typescript/overview.md

#2637 
Adding missing
Closes #2637

fix: add missing anchors on new titles

---

src/guide/extras/ways-of-using-vue.md

TroisJS doesn't use the custom render API and it's unmaintained, updated to TresJS

Add WebGL and custom render API with TresJS ways-of-using-vue.md

---

src/tutorial/src/step-1/description.md

A follow-up to #2627
As a newcommer (and then me as well) got confused about using Vue directly in HTML without a build step, I think there should be more info about this topic to make Tutorial more friendly and help new developers to avoid pitfalls.
Add "Tip" section with some clarification.
The box is placed inside `Tutorial Setting Details` inside `/tutorial/#step-1` which is folded by default and only shows when user actively clicks on it.
I am not sure about the form, so I am more than happy to read the feedback and change the wording as necessary.

Side note about HTML-mode in Tutorial

---

vercel.json

Add this vercel config for all the translation sites (deployed on Vercel). So they can sync up with this easily. Thanks.
https://github.com/vuejs-translations/docs-pt/issues/128

chore: add vercel config for translations

---

.vitepress/config.ts
.vitepress/theme/styles/index.css

If Vue docs only use one code theme, we could explicitly specify that, and there is no CSS required (also save some bits as we never use the light theme).

chore: remove shikiji workaround

---

src/translations/index.md

Add translation info for newly deployed [ar.vuejs.org](https://ar.vuejs.org/)
Repository https://github.com/vuejs-translations/docs-ar

feat: Add Arabic to WIP languages

---

src/about/team/members-core.json

Change redirection link from https://github.com/vuequery to https://github.com/phanan/vuequery

fix: change redirection link

---

src/guide/essentials/watchers.md
src/guide/extras/render-function.md

For translating purpose, there is missing anchors.
I guess, we should write somewhere to think about those missing anchors because it's the 3rd time I spot this situation.

fix: add missings anchors

---

src/guide/essentials/event-handling.md

comment lines are being splitted to avoid horizontal scrolling as in a comment right after
the comment is in one line and right after there is another comment in 3 lines that avoid horizontal scrolling
Split the comment in two lines

Update event-handling.md to avoid horizontal scrolling

---

src/guide/built-ins/transition-demos/NestedTransitions.vue

[Nested Transitions](https://vuejs.org/guide/built-ins/transition.html#nested-transitions-and-explicit-transition-durations) example color is not suitable in the dark theme
I added the color that is in light theme directly in its style

fix: transition nested example

---

src/guide/components/slots.md

The link talks about syntax constraints of dynamic directive arguments, but points to Directives [#directives](https://vuejs.org/guide/essentials/template-syntax#directives)
Change link to Dynamic Argument Syntax Constraints [#dynamic-argument-syntax-constraints](https://vuejs.org/guide/essentials/template-syntax#dynamic-argument-syntax-constraints)

fix: slots.md link to Dynamic Argument Syntax Constraints

---

src/guide/extras/reactivity-in-depth.md

docs: update Angular Signals reactivity comparison

---

src/guide/essentials/watchers.md

Vue(v3.4) is provide once option on watcher([commit link](https://github.com/vuejs/core/commit/a645e7aa51006516ba668b3a4365d296eb92ee7d), [discussion link](https://github.com/vuejs/core/pull/9034)) 
I propose to add once option description on watcher

docs: add once option on watcher

---

src/guide/components/props.md

- I propose to add Error Type on defineProps docs
- regarding code: https://github.com/vuejs/core/blob/v3.3.8/packages/compiler-sfc/__tests__/compileScript/__snapshots__/defineProps.spec.ts.snap#L235

docs: add Error type on defineProps

---

src/guide/built-ins/transition.md

An Vue certification exam taker mentioned that the use case for key with transition wasn't clear in the Vue.js docs.
This provides a nice example of how using key with the transition component can be helpful.

docs: add transition + key example

---

src/guide/built-ins/transition.md

[Transitions with the Key Attribute](https://vuejs.org/guide/built-ins/transition.html#transitions-with-the-key-attribute) section didn't have options-api example.
I added options-api example.
I also added the playground example.

docs: add options-api for `Transitions with the Key` example

---

src/guide/quick-start.md

The mainstream bundle of Vue.js is too big or not the best for setups that do not have a build system or are too minimalist, so while I was reviewing the documentation, I found one possible enhancement for the documentation.
So, I added a note recommending users give a chance to the `petite-vue`  for no-build setups and minimalist approaches.

docs: recommend `petite-vue` for no build approaches

---

src/api/options-lifecycle.md

#2706
The description of `beforeCreate` is some ambiguous and can lead to misunderstanding, because the `initProps` is called after `beforeCreate` and the document only mention `beforeCreate` is called after the props resolution.
Add the description that after `beforeCreate` the props will be defined as reactive properties and the state such as `data()` or `computed` will be set up.

docs: improve the description of beforeCreate

---

src/guide/typescript/overview.md

Vue official docs for typescript support is outdated.
Update Typescript overview docs to sync it with [vuejs/language-tools latest changes](https://github.com/vuejs/language-tools/releases):
- Vue's Volar VS Code extension renamed to "Vue - Official".
- Takeover Mode has been deprecated.
- TypeScript Vue Plugin is no longer needed.

docs: sync vue typescript overview docs with vuejs/language-tools latest changes

---

src/guide/extras/reactivity-in-depth.md

The "Immutable Data" section contains a code example that uses Immer to achieve data immutability. However, the code example uses the outdated Immer import method, `import produce from "immer"`. The latest version of Immer recommends using the named import, `import { produce } from "immer"`.
[2694](https://github.com/vuejs/docs/issues/2694)

Fix outdated Immer import in "Immutable Data"

---

src/guide/extras/ways-of-using-vue.md

> 🚀 The [Beta for Tauri 2.0](https://beta.tauri.app/blog/tauri-2-0-0-beta/) has launched!

docs(extras): move Tauri

---

src/api/compile-time-flags.md

"Hydration" was misspelled in the `__VUE_PROD_HYDRATION_MISMATCH_DETAILS__` anchor link.  
```diff
- VUE_PROD_HYDRATATION_MISMATCH_DETAILS
+ VUE_PROD_HYDRATION_MISMATCH_DETAILS
```
Correct "Hydration" spelling

Fix "Hydration" typo

---

src/guide/extras/render-function.md
src/guide/quick-start.md
src/guide/scaling-up/tooling.md
src/guide/typescript/overview.md

I have noticed several more places in docs where "Volar" is still referenced instead of "Vue - Official"
I tried to change all mentions in a consistent way
Some remarks / things to think about yet:
- some links point to VS Code extension marketplace page, some lead directly to GitHub repo (even the old one, getting redirected to vuejs/language-tools). **Maybe it should also be unified?** Or were there intentions with that?
- there are some mentions of [WebStorm + Vue](https://vuejs.org/guide/typescript/overview.html#ide-support) using "Volar" too. I didn't changed that, as I am not familiar with it.
- in [Tooling](https://vuejs.org/guide/scaling-up/tooling.html#ide-support) there are also links to some special tools for sublime/vim, I guess their names stay for now, so I left them alone

docs: update Volar to Vue - Official

---

src/guide/built-ins/transition-group.md
src/guide/built-ins/transition.md

"GreenSock" CSS library is now widely referenced as "GSAP", also the link changed accordingly
Update the two mentions on `<Transition>` and `<TransitionGroup>` pages

Renamed GreenSock to GSAP + updated link

---

src/ecosystem/themes/themes.json

Added Wrappixel Templates to theme.json

Added Wrappixel Templates

---

src/guide/built-ins/suspense.md

`<Suspense>` is the only built-in component page in Guide, that hasn't its API reference linked
Add the same link as on the other components' pages

Link API reference for Suspense

---

src/guide/best-practices/production-deployment.md
src/guide/extras/composition-api-faq.md

There are two places, where docs mention compile time flags and link [GitHub readme file](https://github.com/vuejs/core/tree/main/packages/vue#bundler-build-feature-flags). But some time ago an internal [docs page about Compile time flags](https://vuejs.org/api/compile-time-flags) was added. I believe, it is better to link this page - it has more info + examples + is translated
Change links accordingly

Internal link to compile time flags

---

src/guide/quick-start.md

Resolves #2748
I applied workaround that @brc-dd shared in the issue.
N/A

fix: fix syntax highlight

---

src/guide/built-ins/transition.md

[/src/guide/built-ins/transition.md] 
some sentences need punctuation adjustments at the end.
change the symbol from 【.】 to 【:】

docs: adjust punctuation in /src/guide/built-ins/transition.md.

---

src/api/composition-api-dependency-injection.md

I believe second "See also" on https://vuejs.org/api/composition-api-dependency-injection logically belongs to **#inject()** section. Few months ago, new section for **hasInjectionContext()** was inserted and broke this logical bond. But since it is only a true/false indicator, I don't think further info, especially about TypeScript, is relevant to it.
Move "See also" links to appropriate place

docs: fix 'see also' for provide/inject API page

---

src/guide/components/v-model.md

When I read the documentation, I am unclear about the source of this count.

docs: fix typo - count should be model

---

src/guide/quick-start.md

vue-cli relies on a more up-to-date Node.js version since v3.10 (now it's using parseArgs from node:util):
— https://github.com/vuejs/create-vue/releases/tag/v3.10.0
— https://github.com/vuejs/create-vue/issues/469
Update required node version to greater than 18.11
Based on Node.js changelog, the value should be 18.11 https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V18.md#2022-10-13-version-18110-current-danielleadams

update: required node version

---

src/about/team/Member.ts
src/about/team/TeamMember.vue
src/about/team/TeamPage.vue
src/about/team/members-core.json

Kevin Deng is an important figure in the Vue.js community! 
He has made significant contributions to projects such as vuejs/core, Vue Macros, and VueUse.
Recently, he has been active as the lead of vuejs/core-vapor. 
He is definitely someone who should be featured in the documentation! 😄 
Document updation!

update: add "Kevin Deng" to core member

---

src/about/community-guide.md

The old link on /about/community-guide.html is not working properly - it only leads to Vue's GitHub discussions main page.
Update link to point directly to the desired section

fix: link to "Show and tell" forum

---

src/guide/quick-start.md
src/guide/scaling-up/tooling.md
src/guide/typescript/overview.md

Based on Microsoft's official documentation and resources, "VS Code" is the commonly used abbreviation for Visual Studio Code.
chenged "VSCode" to "VS Code"

"VSCode" to "VS Code"

---

src/guide/essentials/class-and-style.md

The example code mentioned a variable that is out of context. The `active` variable is used way up on the page, later on the page `activeClass` is used along with `errorClass`.
I suggest the variable here is changed to `activeClass` to remove any confusions that may arise.

Use the correct class variable based on the context

---

.vitepress/config.ts
src/translations/index.md

Hello @yyx990803 and @bencodezen, i am a member of the organization [translation-gang](https://github.com/translation-gang/docs-ru).
We have finished translating the documentation into Russian and would like to place a link to the official website of the documentation with the translation, as well as link the domain https://ru.vuejs.org/ for https://vuejs-doc-ru.vercel.app/.
You can help with the domain and consider this PR?
PS: Added additional information here https://github.com/vuejs/docs/issues/478#issuecomment-1943122897
Repository: https://github.com/vuejs-translations/docs-ru
Discussion: https://github.com/orgs/vuejs-translations/discussions/12#discussioncomment-8756236

Add translation link to ru.vuejs.org

---

src/guide/quick-start.md

Recently, `create-vue` adds an option to allow users to install Vue DevTools 7 interactively. This PR syncs the documentation with real output from the scaffolding tool.

chore: update create-vue output

---

src/guide/components/slots.md

The guide section of slots does not show how to do conditional slots.
I've added a section on how to use slots conditionally with a card
example and a link to a playground.
Here you can see it in action:
https://deploy-preview-2751--vuejs.netlify.app/guide/components/slots.html#conditional-slots

docs: added conditional slots section in slots guide

---

src/examples/utils.ts

fix: don't trigger onHashChange if path is not the same

---

src/api/built-in-components.md
src/guide/built-ins/suspense.md

``suspensible`` prop was added in https://github.com/vuejs/core/pull/6736 in Vue 3.3 but there's no mention of it in the documentation. I tried to simplify a bit further the description of the original PR (which is a great explanation and I didn't think it needed much changing besides maybe a few nitpicks which might be more understandable by the uninitiated).

feat(Suspense): add suspensible prop information

---

src/guide/essentials/component-basics.md

On the page about [Component Basics](https://vuejs.org/guide/essentials/component-basics.html) it might take a little bit for a first time user of Vue to understand that the `<slot>` is being used inside the `AlertBox` component, given that it is not mentioned directly
Adding direct mention of the `AlertBox` component to simplify readability
Based on this rule [here](https://github.com/vuejs/docs/blob/main/.github/contributing/writing-guide.md#:~:text=When%20you%20assume%20knowledge%2C%20declare%20it%20at%20the%20beginning%20and%20link%20to%20resources%20for%20less%20common%20knowledge%20that%20you%27re%20expecting.)

docs: rephrasing for understanding

---

src/guide/essentials/event-handling.md

The documentation mentions that method handler can access the DOM element through `event.target.tagName`. However, I think that `event.target.tagName` actually retrieves the tag name of the DOM element, not the DOM element itself. To access the DOM element directly, one should use `event.target`.
I suggest updating the documentation to replace `event.target.tagName` with `event.target`.

doc:fix method handler access the DOM element way

---

src/api/built-in-components.md
src/guide/built-ins/suspense.md

Line breaks in sentences make translation into other languages difficult.

chore: remove line breaks in sentences

---

src/api/sfc-script-setup.md

Simple PR to make it easier to find the `Suspense` docs from top-level await.

docs: link to suspense

---

src/guide/best-practices/accessibility.md

Change `chrome developer tools` to `Chrome DevTools`.
Note: `Chrome DevTools` is also used in other places on this page.

typo: Chrome should be capitalized

---

src/tutorial/src/step-11/App/composition.js

It should be `register child component`, not `register component`.
Also, refer to [here](https://github.com/vuejs/docs/blob/main/src/tutorial/src/step-11/App/options.js).

fix: wrong remark in guide step-11

---

src/guide/components/v-model.md

docs: add docs for v-model `update:*` event

---

.vitepress/theme/components/Home.vue

- Insert alternative text for the logo itself (because **this is a meaningful logo image**, not a background image)
- To prevent layout shift for the image, specify the `width` and `height`
- The `:global` specification is meaningless since CSS Modules are not being used

Fix: uwu logo style & alt text from Home.vue

---

src/glossary/index.md

Recent PR #2817 contained one incorrect link. Hard to spot it, I found it just by an accident during translating :)

fix: link to getter function definition

---

src/guide/reusability/custom-directives.md

docs: add warning to custom-directives

---

src/guide/quick-start.md

docs: update /guide/quick-start page

---

.vitepress/headerMdPlugin.ts

closes #2857
This can be exploited though, but I don't have any better fix. Just don't merge any PRs containing obfuscated HTML entities and it will be fine.

fix: broken header plugin

---

src/guide/built-ins/transition.md

Domain csstriggers.com was dropped 2022 Aug 27. It has a new owner since 2022 Oct 2, so it can turn malicious at any time.
Remove sentence with it

Domain csstriggers.com was dropped. Need to remove.

---

src/guide/reusability/custom-directives.md

Fix comma splice. This sentence should be two.

fix: remove comma splice

---

src/guide/scaling-up/testing.md

Remove dead playwright read more link
1. Remove dead playwright read more link - https://playwright.dev/docs/why-playwright
2. Added info text from https://playwright.dev/docs/intro#introduction

fix(testing): broken playwright link

---

pnpm-lock.yaml
src/guide/scaling-up/tooling.md

**tooling.md** uses broken/old [codesandbox link](https://codesandbox.io/s/vue-3)
Update **tooling.md** code sandbox link to https://codesandbox.io/p/devbox/github/codesandbox/sandbox-templates/tree/main/vue-vite which reference https://github.com/codesandbox/sandbox-templates/tree/main/vue-vite
When loading [Vue on Components.studio](https://components.studio/create/vue3) there is an error in there.
Update:
Created bug issue. Reference: https://github.com/divriots/components.studio/issues/6

fix(playground): update codesandbox link

---

src/api/sfc-spec.md

In i18n custom blocks, vite-plugin-vue-i18n is currently not the main one but unplugin-vue-i18n is mainstream.
fix the link
related https://github.com/vuejs/language-tools/pull/4392

fix: Correctly link to i18n custom blocks

---

.vitepress/headerMdPlugin.ts
package.json
pnpm-lock.yaml

reverts 4447a5e and fixes issues in #2878

chore: bump deps, remove lock and workaround

---

src/guide/typescript/options-api.md

The statement was a missing the word "to"
Add the missing word

Fix typo: "subject the" -> "subject to"

---

src/guide/components/v-model.md

I believe `v-model="foo"` is what is to be compiled into
```
:modelValue="foo"
@update:modelValue="$event => (foo = $event)"
```
instead of `v-model="modelValue"`

doc: update v-model.md, fixed what I believe to be an error

---

src/api/reactivity-advanced.md

There's an inconsistency when working with customRefs, it occurs when the getter function returns a newly generated object datatype each time it is run, where this customRef is passed as a prop to a child component, it will trigger reactive dependencies in the child component, meanwhile the reactive dependencies in the parent component don't trigger because the customRef's setter wasn't called.
A warning to users of customRef, providing insight into this possible inconsistency, and a link to the play ground that lets them see the inconsistency interactively.
Fixes #2884

Warn custom ref

---

src/guide/extras/rendering-mechanism.md

The actual code example is missing a div end tag
Add the end tag

fix: update example in guide/extras/rendering-mechanism

---

.vitepress/theme/components/Home.vue
.vitepress/theme/components/SecurityUpdateBtn.vue
.vitepress/theme/index.ts

Added links to Vue 2 EOL and HeroDevs NES Vue 2 support in the home page and sidebar.
**Home Page**
**Sidebar**

chore: add redirect to herodevs site for vue 2

---

src/api/render-function.md

change type of withModifiers param
update documentation to reflect the change in #10856, where the type of the second parameter of withModifiers was changed from string[] to ModifierGuardsKeys[]
[vue/core #10856](https://github.com/vuejs/core/pull/10856)

docs(withModifiers): change type of withModifiers param

---

src/api/sfc-script-setup.md
src/guide/typescript/composition-api.md

This code in typescript triggers a confusing Error: 
```ts
export interface Props {
msg?: string
labels?: string[]
}
const props = withDefaults(defineProps<Props>(), {
msg: 'hello',
labels: ['one', 'two'] 
})
```
Type 'string[]' is not assignable to type '(props: LooseRequired<Props>) => string[]'.
Type 'string[]' provides no match for the signature '(props: LooseRequired<Props>): string[]'.ts-plugin(2322)
TestComp.vue(7, 3): The expected type comes from property 'labels' which is declared here on type 'InferDefaults<LooseRequired<Props>>'
This is correctly circumvented in the example in the docs by wrapping the default value for "labels" in a function.
```ts
export interface Props {
msg?: string
labels?: string[]
}
const props = withDefaults(defineProps<Props>(), {
msg: 'hello',
labels: …
```

Add info for wrapping refrence types in functions for withDefaults

---

.vitepress/theme/components/SecurityUpdateBtn.vue

Recent update 8a4f627 introduced new button component in VitePress theme. CSS styles of this component are not scoped and since `.container` is used several other times, the style leaked:
It might not be apparent for page titles. But we spotted it out, because I added [specific width in Czech translation](https://github.com/vuejs-translations/docs-cs/issues/267). I thought it is only for the button, but it shifted whole layout badly....
I believe there was no intention to edit `.container` style globally and the simplilest solution is just to add `scoped` attribute into `SecurityUpdateBtn.vue`, which I think is also the recommended way of using styles in components to avoid such situations.

fix: scope SecurityUpdateBtn css styles

---

.vitepress/theme/components/Home.vue
.vitepress/theme/components/SecurityUpdateBtn.vue

The security update buttons on both the home page and the sidebar had the same hover for both dark mode and light mode. This made the button hard to read in dark mode.
Add css for hover on dark mode for both buttons.

fix: add different background for dark mode on hover

---

.vitepress/theme/components/SecurityUpdateBtn.vue
src/ecosystem/themes/themes.json

In #2896 two problems were introduced.
1) The trailing comma at the end of the .json file broke the page completely:
2) Orphaned link with no markdown
Little adjustments to fix it
_(I am sorry for two extra commits in this PR. Apparently I put my [latest fix](https://github.com/vuejs/docs/pull/2918) into main instead of a separate branch.)_

Fix themes

---

src/guide/scaling-up/ssr.md

The docs state that with SSG data may not change between deploys.
Rephrase it to say data may not change between requests instead.

docs: fix SSG explanation

---

src/examples/src/fetching-data/App/composition.js
src/examples/src/fetching-data/App/options.js
src/examples/src/fetching-data/App/template.html

When using [fetching-data example](https://vuejs.org/examples/#fetching-data), I encountered rendering error when the data from asynchronous interface has not returned or the request fails.
I added some protection logic.
Maybe also catch and display the retrieval when the request fails (Github API is particularly easy to reach rate limit), this needs to be designed for display.

fix: render error for fetching-data example

---

src/api/sfc-script-setup.md

It's not clear how to reference generic components. Eventually after a lot of searching I found the answer here https://github.com/vuejs/language-tools/issues/3206#issuecomment-1563399071
Document how to reference generic components in the section about generic components.

Add note about how to reference generic components

---

.vitepress/config.ts
package.json

re: https://github.com/vuejs/docs/issues/2931
1. Use native vitepress sitemap generation config (https://vitepress.dev/guide/sitemap-generation#sitemap-generation)
1. Updated engine node to 18 or higher as per **README.md** documentation
2. Generated **sitemap.xml** file:

feat: generate sitemap

---

src/guide/essentials/list.md

`<li v-for="value in myObject">` lists the values of `myObject`, not its keys as suggested via the `Object.keys()` analogy in the docs.
Replace `Object.keys()` analogy to `Object.values()`

Fixed error in docs of List Rendering

---

src/guide/typescript/composition-api.md

In #2945  I didn't document how to reference generic components in the section about `ref()`.
This PR

Add docs on how to reference generic components

---

src/guide/components/v-model.md

Unnecessary expression of using props 
:value="props.modelValue"
:value="modelValue"

docs: remove unnecessary props using

---

src/guide/quick-start.md
src/guide/scaling-up/tooling.md

Attempting to resolve issue https://github.com/vuejs/docs/issues/2898
On the [Quick Start](https://vuejs.org/guide/quick-start.html) page,` yarn create vue@latest` is one of the recommended ways to creating a Vue application. 
But yarn classic doesn't support appending @tag to the create command. And yarn modern recommends using [yarn dlx](https://yarnpkg.com/cli/dlx).
Similarly, the [Tooling](https://vuejs.org/guide/scaling-up/tooling.html) page also faces the same issue.
List both options with comments.
Before & After
| Before | After |
|----------|----------|
|<img width="696" alt="image" src="https://github.com/user-attachments/assets/cf102c0d-64c9-456c-8ecf-8d05907ed2d5">|<img width="727" alt="image" src="https://github.com/user-attachments/assets/39e0f5df-0202-4c0a-a1bf-b5813dd8a706" …

Update yarn create command

---

src/api/options-misc.md

Currently, Composition API documentation offers only `defineOptions` macro for using `inheritAttrs` but said macro was not available before Vue 3.3
Add a link to a part of the documentation that explains how we can use `inheritAttrs` as a component option in normal <script>
Close #2933

Added a link explaining how to use inheritAttrs in normal <script>

---

src/style-guide/rules-essential.md

The link to the Vue Loader "CSS Modules" docs is broken and the one to "Scoped CSS" has changed.
Change the links to the correct targets.

fix: update links to Vue Loader docs

---

src/api/application.md
src/api/built-in-special-attributes.md
src/api/composition-api-dependency-injection.md
src/api/options-rendering.md
src/api/reactivity-utilities.md
src/api/sfc-script-setup.md
src/api/utility-types.md

follow up to b6339b62a9522eb195a24ef74ee6392d65d2bfd7
In mentioned commit a lot of "3.x+" badges were removed from docs and replaced with text "Only suported in 3.x+"
I found two more places, where 3.1 / 3.3 were still present, so I altered them in the same manner.
I also noticed sometimes the text is placed before function description and sometimes after. I took liberty to unify the usage and put all of them **before**, because I think this good to know in advance whether I can use it in my project or not.

docs: remarks about minor versions

---

src/guide/components/async.md

Fixed a typo in Async Components documentation.

fix(typo): typo in async components

---

src/guide/scaling-up/testing.md

This PR updates the E2E testing recommendations to make Playwright more prominent and recommend it alongside Cypress. Also adds some language to make the differences between Playwright and Cypress stand out more, particularly around the state of Component Testing and licensing.

docs: move Playwright to recommended frameworks

---

src/api/composition-api-helpers.md

return value type for useModel() is missing
add ModelRef

docs: missed return value type for useModel()

---

src/api/reactivity-core.md

1) In 66a8ced546bc2feb3b9bb90c09b236039f621b65 example for "side effect cleanup" got duplicated for `watchEffect` (lines `281` and `318`)
2) The example for "Pausing / resuming the watcher" shows `watchEffect` instead of `watch`
1) Remove the duplicated text
2) Fix the function name
1) I removed the original occurence to maintain same order of examples as for `watch` function listed later on the page

docs: fixes in 3.5 updates on reactivity-api page

---

src/guide/components/async.md
src/guide/components/props.md

While translating new content I found a few headlines without usual anchors for future language-prone references from other places
Add missing anchors in the traditional style

docs: add omitted anchors for 3.5

---

src/guide/extras/render-function.md

fix: createVnode() -> createVNode()

---

src/guide/best-practices/accessibility.md

Closes https://github.com/vuejs/docs/issues/2440 
The tip was outdated for Vue3

docs: update a11y docs for landmarks

---

src/guide/reusability/custom-directives.md

The autofocus example in custom directive makes the guide appear to be buggy since it jumps down automatically on page load.
I've replaced the example with a more generic `vHighlight` example to demonstrate how it would work, but retained the practical lessons from the benefits of `vFocus` in a new "When to use custom directives" so people can learn from it still.
Open to other suggestions though if people have a better example that comes to mind!
Closes #2914

docs (#2194): fix issue with autofocus on custom directives page

---

src/guide/essentials/forms.md

Clarify unexpected behavior regarding un-parsable or empty input until/unless https://github.com/vuejs/core/issues/8214 and https://github.com/vuejs/core/pull/8215 are fixed.

v-model.number: clarify unexpected behavior

---

src/guide/built-ins/suspense.md

The `suspensible` prop was added in Vue 3.3 and I forgot to add it to #2785

fix(guide/suspense): missing v3.3+ badge in suspensible prop

---

src/api/general.md

Fix a small grammatical error in the file for improved readability.

Fix grammar in general.md

---

src/guide/typescript/options-api.md
src/guide/typescript/overview.md

Broken links.
Updated the links.
These files were moved in https://github.com/vuejs/core/pull/11520

docs: fix broken links to dts-test files

---

src/guide/reusability/plugins.md

There exists instructions how to write a plugin,
but not how to prepare or build said plugin for npm.
Add link to vite's docs.
I don't think that's a good solution, but it's at least better than what we have now (which is none).
In the long term a detailed instruction would be great,
even better would be if we could have a scaffolding for it, see https://github.com/vuejs/create-vue/issues/565
—

Update plugins.md on how to bundle a plugin.

---

src/guide/essentials/computed.md

This was shipped silently in Vue 3.4. See [PR](https://github.com/vuejs/core/pull/9497)

feat(guide/computed): add previous to computed

---

src/guide/essentials/template-refs.md

Removed a single unnecessary line break in the documentation.
Please review. Thank you!

docs: remove unnecessary line break

---

src/api/built-in-special-attributes.md

ref -> useTemplateRef
```ts
const p = ref() // [!code --]
const pRef = useTemplateRef('p') // [!code ++]
```

docs: update ref attribute example

---

src/guide/essentials/template-refs.md

The required version stated in the docs is incorrect (v3.2.25). Looking at [the changelog](https://github.com/vuejs/core/blob/main/CHANGELOG.md), `useTemplateRef` was only introduced in v3.5.
Update the version to v3.5

docs: fix required version for useTemplateRef

---

src/guide/essentials/template-refs.md

A section of the guide on using template refs has the tendency to be ambiguous because there's not much intentional context around it. It may not be understood without reading the previous section.
The section addresses usage with v-for before v3.5, 'before v3.5' here means before the `useTemplateRef()` helper was introduced. 
I added a description before the code of the summary comes up.

docs: improve clarity on using refs

---

src/guide/essentials/template-refs.md

In the [Template Refs](https://vuejs.org/guide/essentials/template-refs.html) guide, the example code uses `input` as the template ref, but the documentation text refers to `inputRef.value`, which does not match the code. This causes confusion for readers.
I have updated the documentation to replace `inputRef.value` with `input.value`, ensuring consistency between the example code and the explanation.
This Pull Request addresses issue #3064.

docs(essentials/template-refs): fix typo

---

src/api/composition-api-helpers.md

The code sample in composition-api-helpers(useModel) had the end of a square bracket outside of the code sample due to an incorrect indentation as seen below
Removed the extra spaces and the bracket is back inside the code;

docs: Correct indentation of a code sample in composition-api-helpers

---

src/api/sfc-css-features.md

The style module is an interesting feature in Vue.js, and the `useCssModule` helper is also quite useful. However, it seems like `useCssModule` lacks an example, which would make it easier for beginners to understand and use.
I have added a simple example for `useCssModule` to demonstrate how to implement it.
---
If you have any feedback or suggestions, please do not hesitate to let me know. 😁

add useCssModule example

---

src/tutorial/tutorial.data.ts

fix https://github.com/vuejs/docs/issues/3022
Just specify the theme
https://vuejs.org/tutorial/#step-2
https://deploy-preview-3078--vuejs.netlify.app/tutorial/#step-2

fix: Tutorial Syntax Highlight

---

src/guide/built-ins/transition-group.md

Prop spec of TransitionGroup is missing on component documentation page. 
Added the missing information.
While building a library which is making use of TransitionGroup, it took me a loooong minute to find out how to pass the move-class as a prop, (that is, I thought for a while it was not possible and it was only possible using CSS, which is annoying if you want to avoid that), because it was not written on the main documentation page. 
Now I checked again and found it in the API spec and found it after all, yey! I updated my library to include the option for this by using the correct props type.

Update transition-group.md - add detail about prop moveClass

---

src/guide/reusability/custom-directives.md

The text is not aligned with the provided example.
the text is about focusing on the element, but the example is about highlighting the text.
[https://vuejs.org/guide/reusability/custom-directives.html#introduction](https://vuejs.org/guide/reusability/custom-directives.html#introduction)

docs:  align custom-directive example with content

---

src/guide/extras/web-components.md

The doc was incorrect for two reasons:
- For Vue-based custom elements, the types passed into `GlobalComponents` need to be the Vue component types, not the custom element types, or the custom elements will not be type checked in Vue templates.
- The name of the elements need to have at least two words and a hyphen, otherwise with single words the custom elements will not work at all.
A few questions:
- Should we include working examples?
- Here's an example for non-Vue custom elements: https://github.com/lume/element/tree/vue-type-issue/examples/kitchen-sink-vue
- Should we include something like the `DefineCustomElement` type helper in `vue`?
- Should we add type tests?
Having examples/helpers/tests could prevent the docs from being incorrect.
There's a conversation in [`#typescript` in …

Corrected and improved docs on type definitions for Custom Elements.

---

src/api/api.data.ts

- Added comments to explain the purpose and functionality of key functions.
- Clarified the logic behind header parsing, slug generation, and file caching.
- Documented the use of regular expressions for header cleaning and anchor extraction.
- Improved readability and maintainability of the codebase.

Refactor api.data.ts: Add comments and improve code clarity

---

src/about/faq.md

References:
- https://github.com/vuejs/core/blob/76c43c6040518c93b41f60a28b224f967c007fdf/tsconfig.json#L6
- Use of `Array.prototype.includes()` (ES2016 feature) in Vue 3.x source code: https://github.com/vuejs/core/blob/76c43c6040518c93b41f60a28b224f967c007fdf/packages/runtime-core/src/compat/renderHelpers.ts#L160

fix: Vue 3.x targets ES2016+, not ES2015

---

src/examples/src/fetching-data/App/composition.js
src/examples/src/fetching-data/App/options.js
src/examples/src/fetching-data/App/template.html
src/examples/src/fetching-data/description.txt

Currently, [the fetching example](https://vuejs.org/examples/#fetching-data) does not work as intended, since it uses an outdated second branch.
Additionally, the paragraph before the commit list mentions repo of Vue 2, even though the data is fetched for Vue 3 Core repo.
Update the repo and branches names. The branches names are the primary branches from https://github.com/vuejs/core/blob/main/.github/contributing.md.
Also, make the example description a bit clearer.
[The edited example in the preview](https://deploy-preview-3102--vuejs.netlify.app/examples/#fetching-data).

fix(example): fix repo and branches names in fetching example

---

src/guide/extras/web-components.md

There is no anchor for the new content.
I added an anchor to the new content.

docs: add missing anchor

---

src/guide/essentials/computed.md

In the entire vue.js documentation, codes are written without semicolons. Having semicolons in code is not wrong, but for keeping consistency with the other codes in the vue.js doc, I think we can remove the semicolons in the given examples. Only here semicolons are used. I think it would be better to remove the semicolons here to maintain consistency with the other codes in vue.js doc.

docs(computed): remove semicolons

---

src/guide/extras/web-components.md

#3110
In file src/guide/extras/web-components.md {#web-components-and-typescript} we have the breaking link [GlobalComponents interface](https://github.com/vuejs/language-tools/blob/master/packages/vscode-vue/README.md#usage) the page is not found.
https://github.com/vuejs/language-tools/blob/master/packages/vscode-vue/README.md#usage
Change the link to https://github.com/vuejs/language-tools/wiki/Global-Component-Types

Fix(web-component): Set right link #3110

---

src/guide/components/v-model.md

Currently, the visual separation of the code blocks (JS vs. HTML) doesn't match the logical separation (child component vs. parent component):
Split the first code block in two and change the code comments to headings:
(see https://deploy-preview-3069--vuejs.netlify.app/guide/components/v-model.html#under-the-hood)

Make `v-model` code example more readable

---

src/guide/essentials/conditional.md
src/guide/essentials/list.md
src/style-guide/index.md
src/style-guide/rules-essential.md
src/style-guide/rules-recommended.md
src/style-guide/rules-strongly-recommended.md
src/style-guide/rules-use-with-caution.md

To avoid the confusions about Style Guide for now.
- hide all the links
- add warnings at the top of all the style guide pages
Related issue from docs-zh-cn: https://github.com/vuejs-translations/docs-zh-cn/pull/1042

Hide all style guide links and add outdated warnings on style guide pages

---

src/guide/essentials/template-refs.md

In the child component’s <script setup>, if defineExpose is called before an await operation, the parent component will not be able to access the exposed properties and methods.
refs
- https://github.com/vuejs/core/issues/4930
Add an explanation in the template-refs.md document to provide users with a workaround for this issue. If a PR later resolves this issue, update this document accordingly.
I spent several hours on this issue. If the document provides this solution, it will help many people

docs: add explanation for template-refs defineExpose before await

---

src/guide/components/registration.md

> a component registered as `MyComponent` can be referenced in the template via both `<MyComponent>` and `<my-component>`.
While learning about Vue components and navigating the PascalCase and kebab-case support between html and vue, I came across this line in the docs. IMO it is not initially clear what is meant here without having to write some components first and get idea.
Making it slightly more verbose to specify exactly where PascalCase components are allowed.
> a component registered as `MyComponent` can be referenced inside a Vue template (or inside an HTML element rendered by Vue) via both `<MyComponent>` and `<my-component>`.

docs: more specific mention of where PascalCase naming is allowed, in components/registration.md file.

---

src/guide/components/slots.md

The original phrasing "**_whether or not a slot is present_**" was potentially misleading, as it suggested checking the existence of the slot itself rather than whether content was passed to it. Updated the explanation to clarify this distinction for better readability and accuracy.
The original phrase was replaced with "...**_whether or not content has been passed to a slot_**"
-

docs(guide/components/slots): clarify slot presence phrasing

---

src/guide/essentials/reactivity-fundamentals.md

There's an extra space in the documentation
Remove the space
n/a

fix: typo in reactivity-fundamentals.md

---

src/guide/extras/web-components.md

There are a few little stylistic flaws in recently added new content about non-Vue Web Components (#3073)
1) Invalid markup
Fixed by adding space between "..." and ">"
2) Too long comments in code snippets causing content overflow, eg.
Fixed by splitting the comments into more rows
3) Removed unnecessary line breaks
This is just to polish already great work made by **trusktr** 👍

fix: formatting in new web-components content

---

src/api/application.md

as https://vuejs.org/guide/components/registration.html#global-registration:~:text=Throughout%20the%20guide%2C%20we%20are%20using%20PascalCase%20names%20when%20registering%20components.

use PascalCase 

---

src/api/component-instance.md

Related issue: [#3138](https://github.com/vuejs/docs/issues/3138)
Updated the `$el` type in the documentation to `any`, as suggested in the Vue Core discussion ([#7915](https://github.com/vuejs/core/issues/7915)) and to align with the actual behaviour.

docs: fix $el type in documentation to 'any'

---

src/api/options-lifecycle.md

Some additions related to error capturing in Vue. See [issue](https://github.com/vuejs/core/issues/12575#issuecomment-2575368469).

Error Capturing Caveats

---

src/guide/best-practices/performance.md

We can see a warning on https://web.dev/articles/fid telling that FID as reach EOL in favor of INP.
* Change from https://web.dev/articles/fid to https://web.dev/articles/inp
* An info box - The change could be subtle without it and to add more info about the change.
The change could be subtle without the info box but tell me if you see a better way of showing the change.

docs(performance): INP replacement of FID

---

src/api/composition-api-lifecycle.md

improvement composition-api-lifecycle type

---

src/guide/best-practices/accessibility.md

The example code in the skip link section of the [accessibility best practices documentation](https://vuejs.org/guide/best-practices/accessibility#skip-link), resets the focus to the skip link every time the route changes. This brings the link into focus and shows it every time. This is technically functional, but defeats the purpose of hiding it with CSS, and doesn't match the behavior on the documentation website itself (or a few others I checked, like Wikipedia, github, w3.org). If the goal is to replicate the way regular web page navigation would affect the focus, then it should be reset to somewhere directly before the skip link.
Expected behavior: On a route change, the skip link is hidden, and when you press tab it appears and is focused.
Actual behavior: On a route change, the …

Change the way focus is set in skip link example code

---

src/guide/essentials/class-and-style.md

fix 
https://github.com/vuejs/docs/issues/2426

docs: clarify that :style can coexist with regular style attributes like class

---

.vitepress/inlined-scripts/restorePreference.js
.vitepress/theme/components/Banner.vue
.vitepress/theme/index.ts

added banner for vueconf 2025

---

src/guide/essentials/computed.md

The first parameter in	computed is actually `publicThis`: [Playground](https://play.vuejs.org/#eNp9UstOwzAQ/BXLF4pUglDhUkIlHj3AARBwtFSFZpumOI5lr0OkKP/O2mkeB+Bie3fWuzNjN/xW66hywJc8tluTa1wJxRjUujTIUtglTiJrfI6xNMFkdtpHjBlAZ9QYM1bYbMlO1nVSaAmsAGuTDE56vO0O7bzbt2WhHUK6HDsgWJxt5kwbqPLS2cmw7oaypYRIltlsKLmeVhwp4T63EZEZsH6032iJzwexFCAQ3QQhSI9zRaxYdVaUKcgbwamN4Kv40wT4gTwgwo2Xytq2T9+PWpqggjA/ZtJaKD7naEnDLs+igy0VmR7kCe6tyCWYF405aRR88ETwRMry+ynk0Dg4mkd39rD9+iV/sLXPCf5qwIKpQPABw8RkgB28fn+Gms4DSIKdpOp/wDcg/53n2JXdOZUS7UldYPtY+O+Tq+zDrmsEZXtRnmh4glAvOP0879xf0ke6i+jy+HQtubipwPieZOAiuoouFrz9ATLd44Y=)
https://github.com/vuejs/core/blob/93d663a0462d37d2678f0a2198425703749950ec/packages/runtime-core/src/componentOptions.ts#L660-L664

docs(computed): correct parameter in computed example

---

src/guide/built-ins/transition.md

On line 333 in the Transition page, `vue-html` should be used instead of `html`
as above

docs: fix blockquote language

---

src/guide/components/v-model.md

docs: capitalize titles

---

src/guide/reusability/composables.md

"Complexity" is the singular subject of the sentence, but the sentence uses the plural verb "grow".
We should use "grows" instead of "grow".
n/a

docs: fix grammar

---

src/guide/built-ins/transition.md

On line 303 in the Transition document, it should be `<Transition>` instead of `<transition>`
as above

docs: fix transition component casing

---

src/api/composition-api-dependency-injection.md
src/guide/components/provide-inject.md

As a follow-up to my comment in #3175, I suggest this to make things really clear
- Improved wording in both Guide and API section
- Copied remark into Composition API block
- Fixed little grammar mistake on API page (provides -> provide)
[Playground example](https://play.vuejs.org/#eNqlVMFOwzAM/ZUol4I0rdrKCRUkmDjAgU3AMZeq9bqMNomSdEyq+u84adeNCcoGt9jvOX6vcV3TO6XGmwroNY1NqrmyxICt1C0TvFRSW1ITDUvSkKWWJQmQGvTQItEg7KSDxmEXu/uQxEQqhbGkNDm5cZdcBErLDc8g5GINKdbPZ8ElE3HYdsaeGFgoVZFYwIiQeDW5rWt/RdPEIUY+u2scYhiHBxV0RK3Btkuej9dGCrRVuwpGU1kqXoCeK8tRFqPXxCMOS4pCfjz5nNUVjHb5dAXp+zf5tdm6HKMLDQb0BhjtMZvoHGwLP7w+wxbPPVjKrCqQPQC+gJFF5TS2tPtKZCj7gOfVPvoX4CJ/Mw9bC8LsTDmhjtl4PqP4FrMB63u50fjK1zHR4Fc8eMqh0egedGg8pkfjMe3Hoyu+CEowJskhGJGg5ZDJb3OR8Y0/9MMw9cOAYdhCx2Nx0PyfhqIjQ9EphqZnG4pOMuSb/9nQbMWLrLfjo1PMRGeYaVsMW+kb …

docs: clarify how inject() works with multiple providing components

---

src/guide/extras/web-components.md

The [docs-zh-cn#1064](https://github.com/vuejs-translations/docs-zh-cn/pull/1064) repo detected that this code style didn't pass the zhlint check. We need to maintain consistent code style.

docs: update web-components.md NOTE code block

---

src/guide/scaling-up/tooling.md

Old link pointed to [Vue.js devtools (beta)](https://chromewebstore.google.com/detail/vuejs-devtools-beta/ljjemllljcmogpfapbkkighbhhppjdbg).
New link points to [Vue.js devtools](https://chromewebstore.google.com/detail/vuejs-devtools/nhdogjmejiglipccpnnnanhbledajbpd).
Other than replacing the URL, having two list entries -- one for non-beta and one for beta version of the extension -- might be preferable.

Swapped Chrome Extension URL to a non-beta version

---

src/guide/extras/render-function.md

In guide/render-function the [Template Refs](https://vuejs.org/guide/extras/render-function#template-refs) uses the old way of template ref  and only below the new (3.5) useTemplateRef. Everywhere in the docs 3.5 is the default with a fallback [Accessing the Refs](https://vuejs.org/guide/essentials/template-refs.html#accessing-the-refs)
* Made useTemplateRef default example
* Hid the other one in a collapsable pre-3.5 version
* Fixed an example issue in the useTemplateRef version `<div ref="divEl">` -> `<div ref="my-div">`

docs(render-function#template-refs): Make useTemplateRef the default example

---

src/guide/extras/web-components.md

Removed unnecessary list styles.
before:
after:

docs: remove list styles

---

src/guide/essentials/template-refs.md

The defineExpose explanation is currently placed too far from the basic ref operations section, making the documentation flow less intuitive for SFC users.
Move the defineExpose explanation and its related code samples from the "Ref on Component" section to immediately after the "Accessing the Refs" section. This reorganization will:
- Provide a more logical progression from basic ref operations to component-specific features
- Improve the learning experience for SFC users by introducing defineExpose earlier in the documentation
- Create a more natural flow in the documentation structure
The change only involves reordering the content without modifying any technical explanations or examples.
n/a

docs: reorder defineExpose explanation

---

src/api/sfc-script-setup.md

Currently the docs on generics are very light and very focused on how to define a generic component, rather than how to actually use said component and seems to assume that the generic value can always be inferred.
This adds an example of how to use generics in a template with the `@vue-generic` directive to explicitly tell TypeScript what type to use, for when the type cannot be inferred.
Currently I've used a very basic example based on my real-world usage, which does technically have a few assumptions but I think just having an `@vue-generic` example in the docs should greatly increase the chances of people figuring this out quickly.
I'm happy to expand on this further if people think that would be useful, such as adding an example of the component implementation to show why the type …

docs: include example of `@vue-generic` directive

---

.vitepress/config.ts

This PR updates the Russian translation repository link in `.vitepress/config.ts` from `translation-gang/docs-ru` to `vuejs-translations/docs-ru` to maintain consistency with the link in `src/translations/index.md`.
The `vuejs-translations/docs-ru` is the correct and active repository for Russian translations.

Fix: Update Russian translation repository link in config.ts

---

src/guide/extras/ways-of-using-vue.md

This pull request includes an update to the `src/guide/extras/ways-of-using-vue.md` file to expand the options for building desktop applications with Vue.
Enhancements to documentation:
* [`src/guide/extras/ways-of-using-vue.md`](diffhunk://#diff-1c4da34ef08c9e5f7c7264572b6defe977f49d972b19fb8fd5f4c92dc591ca1dL56-R56): Added a reference to [Wails](https://wails.io) as an additional option for building desktop apps alongside [Electron](https://www.electronjs.org/).

chore: Add Wails.io as an alternative desktop framework to Vue docs

---

src/api/reactivity-advanced.md

Updated verb to match the plural subject. From "effects that depends on..." to "effects that depend on...".
The definition for the advanced reactivity utility, `triggerRef()` has a minor disconnect between the the subject, "effects" and the verb, "depends".
Since the subject, "effects" is accurate in this case, the verb has to be updated to be plural and match the subject.
The full sentence is "Force trigger effects that depends on a shallow ref". The part "effects that depends on a shallow ref" is a noun phrase with a subject and verb that have been updated to be in agreement.

docs: fixed typo

---

src/guide/essentials/template-syntax.md

The same is the variable name rather than the value of variable.

Variable name, not value of variable

---

src/about/faq.md

While studying the FAQ I noticed the text has not been updated after reaching end of life date of Vue2.
I haven’t deleted the paragraphs because they still contain relevant historical information.

Update FAQ after Vue2 reached end of life

---

src/guide/reusability/plugins.md

plugins allow us to use `provide` to provide a function or attribute plugin, users are able to `inject` the plugin function or attribute
It says: _Plugins also allow us to use `inject` to provide a function or attribute to the plugin's users..._ and the example shows that `provide` is used. Also after the example it says _Plugin users will now be able to inject the plugin options..._
Replace `inject` with `provide`

Fix: provide/inject in plugins.md

---

src/examples/src/crud/App/composition.js

this is more a typo
this is really not something important, but I spotted it while going through the docs and example, I guess it can be clearer if fixed

Fix: misplaced semicolon in crud example

---

src/api/composition-api-lifecycle.md

errorCaptured() is options api, and there must be onErrorCaptured()

fix hook name to composition version

---

src/guide/essentials/computed.md

In the Options API, the first parameter in the computed getter is actually `publicThis`.
See [https://github.com/vuejs/docs/pull/3206](https://github.com/vuejs/docs/pull/3206)

docs(computed): correct parameter positions in the computed example

---

.vitepress/config.ts
.vitepress/theme/index.ts
.vitepress/theme/styles/index.css
.vitepress/theme/styles/vars.css
package.json
pnpm-lock.yaml
src/api/compile-time-flags.md
src/guide/extras/reactivity-transform.md
src/guide/extras/web-components.md
src/guide/quick-start.md
src/guide/reusability/plugins.md
src/guide/scaling-up/ssr.md
src/guide/scaling-up/testing.md
src/guide/scaling-up/tooling.md
src/tutorial/src/step-1/description.md

Current, the docs site use `<VTCodeGroup>` for define code groups. 
This PR use Vitepress' built-in `code-group` with [vitepress-plugin-group-icons](https://github.com/yuyinws/vitepress-plugin-group-icons?rgh-link-date=2024-12-20T08%3A38%3A13Z) to replace it. which has automatic icon matching.
| Before | After |
| ------ | ----- |
| <img width="723" alt="image" src="https://github.com/user-attachments/assets/d129a421-8889-4df9-a71c-991b470f2492" /> | <img width="714" alt="image" src="https://github.com/user-attachments/assets/0bfa094e-0503-4c1d-b6bf-26df22272c2b" />   |
|<img width="735" alt="image" src="https://github.com/user-attachments/assets/7eb2ceca-aae7-4571-9c34-8677d3dfad13" /> | <img width="719" alt="image" src="https://github.com/user-attachments/assets/9017b3e5-cc01-46ac-85d9-c …

feat: enhance code block & code group

---

.vitepress/config.ts

Vue School Banner script is being blocked by adblockers
Banner Script url updated 
new url - `https://media.bitterbrains.com/main.js?from=vuejs&type=top`

Update Vueschool banner script URL

---

src/guide/quick-start.md

The vite version currently supported by create-vue is 7, and the node version required by vite is as follows. In order to ensure that the created project is OK, you need to synchronize the node version information.
https://github.com/vitejs/vite/blob/588b3b5a44eef35bcca0e3079df579d50a528421/package.json#L6

docs: sync vite need node version
