src/.vuepress/components/BetaBanner.vue

This PR fixes the issue where the bottom border of the "Docs in beta" banner is missing on homepage.
Before:
After:

fix: beta banner bottom border missing on Home

---

src/guide/migration/functional-components.md

In [Migration - Functional Components](https://v3.vuejs.org/guide/migration/functional-components.html#components-created-by-functions), I believe that:
```js
export default GreetingMessage
```
should instead be 
```js
export default DynamicHeading
```

fix(migration/functional-component): typo DynamicHeading

---

src/examples/dynamic-components/index.html
src/guide/migration/global-api.md

In one of the examples as well as in the migration guide there are a few usages of the previous API signature of the `mount` method.

fix: use current `mount` API

---

src/guide/migration/render-function-api.md

Migration guide -> render functions
The last example didn't use the new flat vnode format for all properties. This PR fixes that.

fix: use proper flat vnode format in example.

---

src/guide/migration/v-model.md

This sentence threw me at first because i've been customizing v-model in Vue 2 for a long time! it comes clear later, but figured we could front-load the clarification.

Clarify v-model usage history

---

src/.vuepress/theme/styles/code.styl
src/guide/optimizations.md
src/guide/reactivity.md

Working on the responsive styles for the explainer codepens but I think they will be more legible with a wider container.

Create a wider container for the codepens

---

src/.vuepress/theme/components/Navbar.vue
src/.vuepress/theme/styles/code.styl
src/.vuepress/theme/styles/index.styl

We don't have to go in this direction, but I thought it might be nice to separate from the default vuepress styles and go a little more towards the default vue docs syntax highlighting. Let me know what you think!

Syntax highlighting

---

src/guide/migration/global-api-treeshaking.md

Directives API was changed a while ago: the function was renamed, it no longer requires to provide a current instance and directives should be passed in an array as opposed to being passed as function arguments.

fix: use current directives API

---

src/style-guide/README.md

Vue 3 does keying automatically on a compiler level, so this section is outdated.
Example of auto keying: https://vue-next-template-explorer.netlify.app/#%7B%22src%22%3A%22%3Cdiv%3E%5Cr%5Cn%20%20%3Cdiv%20v-if%3D%5C%22exp%5C%22%3E1%3C%2Fdiv%3E%5Cr%5Cn%20%20%3Cdiv%20v-else-if%3D%5C%22exp2%5C%22%3E2%3C%2Fdiv%3E%5Cr%5Cn%20%20%3Cdiv%20v-else%3E2%3C%2Fdiv%3E%5Cr%5Cn%3C%2Fdiv%3E%22%2C%22options%22%3A%7B%22mode%22%3A%22module%22%2C%22prefixIdentifiers%22%3Afalse%2C%22optimizeImports%22%3Afalse%2C%22hoistStatic%22%3Afalse%2C%22cacheHandlers%22%3Afalse%2C%22scopeId%22%3Anull%2C%22ssrCssVars%22%3A%22%7B%20color%20%7D%22%2C%22optimizeBindings%22%3Afalse%7D%7D
Thanks for your interest in submitting a PR! At this time, because the docs are in beta, the team is currently in the midst of changes and we …

Remove outdated section of keying siblings under v-if

---

src/guide/template-syntax.md

Only `null` and `undefined` will result in no attribute in the final DOM, according to [RFC #24](https://github.com/vuejs/rfcs/blob/master/active-rfcs/0024-attribute-coercion-behavior.md#detailed-design)

Update attribute coercion with respect to new behaviour

---

src/guide/migration/global-api.md

The link to Global API Treeshaking somehow got broken. This PR should fix it.

fix: link to Global API Treeshaking

---

src/.vuepress/theme/styles/config.styl
src/.vuepress/theme/styles/index.styl

Initially, the "beta" banner's height was hard-coded to be `3.3rem`, and other values were calculated based on it. Later on, however, this hard-coded value was removed, resulting in this super minor gap:
This PR removes the gap (using another hard-coded value 😅).

fix: sidebar's top value

---

src/.vuepress/theme/styles/mobile.styl

Not sure if I'm missing anything here, but currently the sidebar has a weird top padding on mobile:
This PR removes it:

fix: sidebar's top padding on mobile devices

---

src/guide/transitions-state.md

This PR simplifies the state transitions page and updates all examples to Vue 3.

State Transitions Page Revamp

---

src/.vuepress/theme/styles/code.styl
src/guide/transitions-overview.md

This adds in interpolation example with style bindings to overview.
While I was in there, I noticed the line highlighting was weird so I updated that, too.

Add in interpolation example

---

src/guide/migration/filters.md

Removes a double "instead" and adds one word for clarity.
In reference to the below note, I trust this small change will not cause any overload for the docs team.  Of course feel free to close if it makes sense to you.

Small grammar fix in filters.md

---

src/guide/migration/global-api.md

In Vue 3,the directive lifecycle hooks are changed.
such as: inserted → mounted
The doc link is [https://v3.vuejs.org/guide/migration/custom-directives.html#_3-x-syntax](https://v3.vuejs.org/guide/migration/custom-directives.html#_3-x-syntax)

fix: change directive inserted to mounted

---

src/.vuepress/theme/styles/index.styl

The current line-height for headings (`1.25`) is a bit too small, causing some headings to overlap on smaller screens, e.g.,
I've increased it a bit—just enough to eliminate the overlapping but not affect the overall look and feel (or so I hope 😅):

fix: increase heading line-height to fix overlapping

---

src/guide/list.md

Fix return statement in an inline arrow function example

---

src/guide/events.md
src/guide/template-syntax.md

You can as well express event listener bindings as the following:
```html
<input v-on:input="foo(), bar($event)">
```
Live example: https://vue-next-template-explorer.netlify.app/#%7B%22src%22%3A%22%3Cinput%20v-on%3Ainput%3D%5C%22foo()%2C%20bar(%24event)%5C%22%2F%3E%22%2C%22options%22%3A%7B%22mode%22%3A%22module%22%2C%22prefixIdentifiers%22%3Afalse%2C%22optimizeImports%22%3Afalse%2C%22hoistStatic%22%3Afalse%2C%22cacheHandlers%22%3Afalse%2C%22scopeId%22%3Anull%2C%22ssrCssVars%22%3A%22%7B%20color%20%7D%22%2C%22optimizeBindings%22%3Afalse%7D%7D
To be clear, it is technically a single expression that contains comma separated list of expressions which is perfectly valid. But this kind of expression does not work consistently across various directives and mustache syntax, so I think it should …

Clarify edge cases for directives attribute expression

---

src/api/options-data.md

Add an explainer that:
1. Emits removes listeners from attribute inheritance
2. Emits removes listeners from the `$attrs` property

Clarify emits API section

---

src/guide/computed.md

Changed an example of `computed` properties to be less cryptic and more 'real-life'
Close #38

Update computed properties example

---

src/guide/contributing/doc-style-guide.md

fixes an error in the doc-style-guide for syntax highlighting multiple sections

fix: syntax highlighting example for multiple sections

---

src/guide/render-function.md

There is a comment in the visualization that is missing from an example, this PR fixes the example code.

fix: add missing comment in example

---

src/.vuepress/config.js

**Motivation**
* Pages under this section group reflect changes that happened only between Vue 2 and Vue 3. It does not help if you're migrating from Vue 1 for example.
* Since it is already a Vue 3 documentation calling migration section `Migration to Vue 3` is a bit of a tautology.
* This grouping does not reflect migration from other frameworks like React or Svelte.

Adjust migration section grouping title to better reflect its contents

---

src/.vuepress/config.js

Relation https://github.com/vuejs/docs-next/issues/318
Remove `internals` guid.  It has duplicate guides.
https://github.com/vuejs/docs-next/blob/master/src/.vuepress/config.js#L71
https://github.com/vuejs/docs-next/blob/master/src/.vuepress/config.js#L86-L87
It was probably degrade in https://github.com/vuejs/docs-next/pull/243

Removed "internals" chapter with duplicate guides

---

src/api/instance-methods.md
src/guide/migration/introduction.md

Added explanation about breaking changes to component `watch` option and `$watch` instance method. Updated the related explanation and added an example for clarification.
See:
- https://codepen.io/yusufkandemir/pen/KKVJKBQ
- https://github.com/vuejs/vue-next/issues/671
- Current source code:
https://github.com/vuejs/vue-next/blob/288b4eab9e10187eb14d4d6d54dc9f077343a2a5/packages/runtime-core/src/apiWatch.ts#L308-L320

feat: Add `watch` changes

---

src/guide/testing.md

This PR aims to clarify the statement where the official docs recommend Vue Testing Library over Vue Test Utils (the official library).
When developing [the new version of VTU](https://github.com/vuejs/vue-test-utils-next/), we wanted to frame it as an “enabling” library. VTU 2 is both a **complete library to test out components**, and also a baseline to build other tools – We even developed a plugin system. This means that VTU is still a valid choice, and that there's no need to rewrite any codebase from VTU to Vue Testing Library.
During conversarions, we agreed that Vue Testing Library had a terser, useful API and that we should recommend it to newcomers.
Closes #326

Reword preference of Vue Testing Library over Vue Test Utils

---

src/guide/render-function.md

Using `v-model` with `input` is still the same as in Vue 2, this was changed only when using with Vue components.

fix: use Vue component instead of `input` in v-model section

---

src/.vuepress/config.js
src/guide/typescript-support.md

This is a raw draft of a TypeScript section

TypeScript section

---

src/.vuepress/components/FirstExample.vue
src/guide/introduction.md

Following the reasoning in https://github.com/vuejs/docs-next/issues/253, I've replaced the first example with Vue component with a reactive property changing over time. I'm still not sure if it's the best decision so would be open to hearing your opinions
Close https://github.com/vuejs/docs-next/issues/253

Replaced first example in Introduction

---

src/guide/teleport.md
yarn.lock

Switch teleport example to real world scenario

---

src/guide/migration/slots-unification.md

I've found a bug related to how to define slots in render function. I guess this worth fixing it because I've lost a few hours struggling with the problem.
That's why I opened a PR. Feel free to close it if needed.

Fix render function slots implementation

---

package.json
src/.vuepress/components/search/index.vue
src/search/README.md
yarn.lock

Added search page as discussed in #352.
Given that the Algolia credentials are not available yet, I've used the ones from v2 for development. If you want to do the same, add the following to `src/.vuepress/config.js` under `themeConfig`:
```js
algolia: {
appId: 'BH4D9OD16A',
apiKey: '85cc3221c9f23bfbaa4e3913dd7625ea',
indexName: 'vuejs',
algoliaOptions: { facetFilters: ["version:2.6"] },
}
```
I've implemented this looking at the [current implementation in v2 docs](https://github.com/vuejs/vuejs.org/pull/1488).
There are some improvements that can be done given the new architecture, for example falling back to VuePress-powered search if Algolia is not configured or unavailable. However, as we've discussed in #352, that would be a nice addition to VuePress itself. So I think it's best to …

Implement search page

---

src/guide/component-basics.md

feat: add v-model through computed explanation

---

src/guide/state-management.md

In the `Simple State Management` section, we had a non-working example with sharing a plain object without making it reactive. This PR fixes the code snippets to use `reactive`
Close #368

Fixed Simple State management section to use reactive

---

src/api/composition-api.md

docs: remove duplicate word and split sentence apart

---

src/guide/reactivity-fundamentals.md

Not completely sure the rules for when to have the vue imports in code samples, but not having this one threw me because the ones directly above do have the imports, and it seems each vue function is imported at least once in the example code.
I spent some time checking if readonly was a native javascript feature of proxies since I've never actually worked with them. Showing the import should quickly clear up where it's coming form.

Add readonly import to code sample

---

src/api/instance-properties.md

update non-props attributes link

---

src/guide/composition-api-provide-inject.md

The PR was originally supposed to just be a small change regarding `readonly`, but then I came up with this scenario to explain provide / inject that I thought would be helpful. 
[Netlify Preview](https://deploy-preview-396--vue-docs-next-preview.netlify.app/guide/composition-api-provide-inject.html#scenario-background)
Feedback welcome as always!
Closes #391

docs (#391): update provide inject in composition api with enhanced reactivity

---

src/guide/transitions-overview.md

This is minor, but I thought it helped to de-duplicate the sidebar section mention

docs: remove duplicate mention of section heading

---

src/api/application-api.md
src/guide/migration/global-api.md

This PR addresses problems raised in #406. Specifically:
1. Minor corrections to an example of `app.provide` in the migration guide.
2. Adding documentation for `app.provide` to the API reference. This had been documented previously but the majority of the text described the wrong feature so it was removed in #355. I have retained some small parts of that previous entry but the majority is new.
I believe it would also be beneficial to mention `app.provide` elsewhere in the documentation, such as in the introductory guide to `provide`/`inject` and in the API reference section for the `provide` & `inject` options. I haven't undertaken that as part of this PR but I would be happy to attempt it if you feel it would be appropriate.

Add app.provide to the API reference

---

src/.vuepress/config.js
src/examples/commits.md
src/examples/elastic-header.md
src/examples/grid-component.md
src/examples/markdown.md
src/examples/modal.md
src/examples/select2.md
src/examples/svg.md
src/examples/todomvc.md
src/examples/tree-view.md

Migrated most of the examples from Vue 2 to Vue 3 docs and into codepen
Note:
- Deepstream was removed due to missing API keys and API going into maintenance only
- Firebase + Validation was not ported due to `vuefire` not being 3.x ready. Confirmed with Posva
- Hackernews clone left for another PR due to complexity
These few should get us up and running with working examples for the docs though!
Issue: https://github.com/vuejs/docs-next/issues/25

feat: migrate examples

---

package.json
src/.vuepress/config.js
src/.vuepress/theme/components/AlgoliaSearchBox.vue
src/.vuepress/theme/components/Navbar.vue
src/.vuepress/theme/package.json

> This PR is a follow-up of [@NataliaTepluhina's tweet](https://twitter.com/N_Tepluhina/status/1290965571023130624).
Hello Vue team! This PR integrates the **new version of DocSearch, that better reflects what we think documentation search should be**.
Reducing users' efforts to get them started integrating your product is key to adoption. We created [DocSearch](https://docsearch.algolia.com) in 2015 as a community effort to solve this problem.
We've had time to try different approaches since then and would like to propose you a new documentation search experience. This new experience has been well received and is now live on the Docusaurus v2 integration: facebook/docusaurus#2815.
| Mobile | Desktop |
|-|-|
| ![Mobile preview](https://user-images.githubusercontent.com/6137112/89410156-809 …

feat(search): update search to DocSearch v3

---

src/guide/reactivity-computed-watchers.md

There are two problems with the existing example:
1. Using `count.value++` changes the value of `count.value`.
2. Despite what it says on the next line, the logged value of `plusOne.value` will be 1, not 2. Note `count.value++` is being used, not `++count.value`.
Changing it to `count.value + 1` fixes both problems.

fix: computed example should not mutate ref value

---

src/.vuepress/components/MigrationBadges.vue

The `validator` for `MigrationBadges` is failing, resulting in console warnings in local builds of the docs.
The `value` is an array, not a string, so it needs to use `every` to test the array entries.

fix: MigrationBadges validator

---

src/.vuepress/config.js
src/.vuepress/theme/global-components/Badge.vue
src/cookbook/editable-svg-icons.md
src/cookbook/index.md

After reviewing a lot of the existing cookbook recipes, a lot of them were vendor focused and felt better suited for blog posts rather than being hosted on the docs site. In addition, a lot of them are outdated, so I thought it'd be easier to start over with a barebone cookbook that we can build back up as people begin using Vue 3.

docs (#26): migrate cookbook

---

src/api/application-api.md

Fixes #423.
There didn't seem to be an established convention for what form these should take. I had a look at both the Vue 2 and Vue 3 docs before making some arbitrary choices:
1. No name or type. In other contexts I might have included the type but for these methods I didn't think `{Object}` really added anything.
2. The values are a sub-list within `Returns`, even though they typically only have a single list item.
3. For the complicated cases (`component` and `directive`) I went for two items in the list rather than trying to cram it all into a single item.
4. I used a capital letter at the start of each item but no full-stop at the end. My reasoning was that these aren't proper sentences, they're more like items on a shopping list or a to-do list.
I made a couple of other small …

Add return values for Application API methods

---

src/.vuepress/config.js
src/guide/migration/transition.md

This PR should round out the migration guide. Transition docs in, still haven't updated the diagram yet though I don't think it's necessary for this section.

Add in transition migration guide docs

---

src/guide/composition-api-introduction.md

Some imports are unused in examples

fix: remove unneeded `toRefs` imports

---

src/api/application-api.md

This PR makes two changes to the API entry for `application.use`:
1. Add the `options` argument.
2. The first argument passed to `install` is the application, not `Vue`.

Update the arguments and description of application.use

---

src/api/application-api.md
src/api/instance-methods.md

This is in response to feedback on #432.
In that PR I attempted to put square brackets around the `isHydrate` argument of `mount` to mark it as optional. It was suggested that we should use the word `(optional)` instead, but that would have been inconsistent with other parts of the same page.
This PR changes all uses of square brackets to the `(optional)` format. It includes `isHydrate`, so #432 can be closed if this is merged.

Indicate optional arguments with the word 'optional'

---

src/guide/composition-api-introduction.md

I've noticed this while reading the guide.

Fix typo in composition-api-introduction.md

---

src/guide/render-function.md

docs: update jsx repository link

---

src/api/global-api.md

the first argument name is `type` not `tag` of function `h`.

docs: fix argument name

---

src/guide/testing.md

I updated my OSS book, the Vue Testing Handbook, to work with Vue.js 3 and VTU v2. This PR adds the correct link to the Vue 3 version of the book.

docs: update testing handbook link to Vue 3 vers.

---

src/guide/render-function.md

fix: should use `createApp` instead of `new Vue()`

---

src/api/instance-methods.md

Delete menu title [ / ] in instance-methods

fix: fix instance-methods title miss

---

src/.vuepress/config.js
src/guide/migration/introduction.md
src/guide/migration/key-attribute.md

This is my attempt to fix #379 (a couple of undocumented breaking changes in Vue 3 related to the `key` attribute).
I think this is technically two separate breaking changes:
* If you manually provide `key`s on `v-if` branches, then each branch must use a unique `key`.
* `<template v-for>` `key` should be placed on the `<template>` tag (rather than on its children).
However, I think it's probably best to keep them on the same page because they're related and often appear at the same time. For example, they appear together in this relatively common situation:
```html
<template v-for="item in list">
<div v-if="item.isVisible" :key="item.id">...</div>
<span v-else :key="item.id">...</span>
</template>
<template v-for="item in list" :key="item.id">
<div v-if="item.isVisible">...</div>
<span …
```

Migration guide section on key attribute changes

---

src/guide/composition-api-setup.md

In "Usage with Templates" the doc shows how props of the object returned from `setup` can be used directly in the template, but I didn't find anywhere else in the composition-api doc where it says that props can also be used directly. This seemed like as good a place as any to add that, since that's where I was looking for it first :-).
Composition API doc doesn't mention that props can be used directly in templates
I added a note and changed the example to use props.

Note that props can be accessed in template directly

---

src/guide/migration/props-default-this.md

The example of using `default` for `props` in the migration guide appears to be missing a wrapper object and `default` property.
I don't think the code as currently written will actually work. Testing with rc.13 seemed to need the extra object.
Added the wrapper object.

fix: introduce the wrapper object to the props default example

---

src/guide/migration/events-api.md

In the migration guide, it suggest using [mitt](https://github.com/developit/mitt) to migrate existing event hubs, but its interface is incompatible with Vue 2 where:
1. mitt's [emit](https://github.com/developit/mitt/blob/22c5dcba10736aecb1f39ee88d9f85278108c988/src/index.ts#L24) doesn't support variadic arguments that [$emits](https://vuejs.org/v2/api/#vm-emit) supports
2. mitt doesn't support `$once`
I suggest to include [tiny-emitter](https://github.com/scottcorgan/tiny-emitter) which its interface is fully compatible with Vue 2 `$on`, `$off` and `$once`, and its [emit](https://github.com/scottcorgan/tiny-emitter/blob/4e6b2eb5869fb4ba862accaef7d16a7051349f4f/index.d.ts#L4) method do support variadic arguments. 
Closes #493

Include tiny-emitter in events API migration strategy

---

src/guide/composition-api-introduction.md
src/guide/composition-api-lifecycle-hooks.md
src/guide/reactivity.md
src/guide/teleport.md

We have a few lessons that should help with Vue 3 learning.  They are all free.
Ultimately these should be turned into play buttons like on the original documentation, but @bencodezen encouraged me to use Markdown for now.
Feel free to modify and move if needed.

docs: added video explanation links for Vue 3

---

src/guide/component-custom-events.md
src/guide/teleport.md

This PR adds links to free Vue 3 lessons from Vue School that complement the docs. The lessons are 1:1 with the concept in the docs.
**Lessons**
- [Emits option](https://vueschool.io/lessons/defining-custom-events-emits)
- [Teleport](https://vueschool.io/lessons/vue-3-teleport)
[Visuals](https://imgur.com/a/OoPjb9S)

docs: add Vue 3 video lessons

---

package.json
src/.vuepress/components/VideoLesson.vue
src/.vuepress/styles/index.styl
src/guide/component-custom-events.md
src/guide/composition-api-introduction.md
src/guide/composition-api-lifecycle-hooks.md
src/guide/reactivity.md

This PR fixes the issue with video lessons not being standardized across platforms.

docs: update video styles

---

src/guide/migration/introduction.md

The "New Features" TOC link in the Introduction section of the migration guide is broken, because the current name and anchor of the section (`New Features` and `new-features`, respectively) does not match the current section name and anchor (`Notable New Features` and `notable-new-features`, respectively).
Fix the TOC item's title and link to match the new section name and anchor (`Notable New Features` and `notable-new-features`, respectively).
The link seems to have been broken with commit 7e55600a84e37d6b26656e44394438d975ae4909 ([pretty GH view][pretty-view]).
[pretty-view]: 7e55600#diff-c9868b6bf75c863c7384dcf155eb6497R35

fix: `introduction.md`: `notable-new-features` anchor in TOC

---

src/guide/migration/global-api-treeshaking.md

There are duplicate words (_something_) in **Global API Treeshaking** section of the docs.
Remove duplicate words.

Remove duplicate words in Global API Treeshaking

---

src/guide/composition-api-lifecycle-hooks.md

The column header for life-cycle hook equivalents in the setup context was called "Hook inside inside `setup`"
One "inside" is enough.

Fixes "Hook inside `setup`" grammar

---

src/api/options-assets.md

Add usage examples for Asset Options

---

src/api/global-api.md

fix: Change the options object: remove the `retryWhen`, `maxRetries` attributes, add the `onError` event, and attach a comment

fix: Change the options object - defineAsyncComponent

---

src/guide/installation.md

Browserify is currently almost underused in the Vue ecosystem.
In fact, it doesn't even work with [vueify](https://github.com/vuejs/vueify) in Vue 3.
vueify is arcvhied.
It has been arcvhied. 
We recommend switching to the current mainstream bundler rollup
As Vue official, we offer a rollup-plugin-vue.
rollup-plugin-vue is available for Rollup as Vue official.
https://github.com/vuejs/rollup-plugin-vue

fix: change to modern bundler

---

src/api/computed-watch-api.md

'watching' was spelling incorrectly  ('wacthing')
fix the spelling

Fix spelling

---

src/guide/a11y-resources.md

`single-switch access` duplicates
remove duplicates
prettier markdown

Fix a11y resources document

---

src/guide/testing.md

standardize for resources sentence.

chore: standardize for resources sentence

---

src/guide/typescript-support.md

The sentences didn't feel complete
Add missing prepositions

fix: add missing prepositions

---

src/.vuepress/theme/components/Navbar.vue

```js
isAlgoliaSearch() {
return this.algolia && this.algolia.apiKey && this.algolia.indexName // string type
}
```
```js
isAlgoliaSearch() {
return !!(this.algolia && this.algolia.apiKey && this.algolia.indexName) //  boolean type
}
```
```js
// config.js: disabled algolia
algolia: {
// indexName: 'vuejs-v3',
// apiKey: 'bc6e8acb44ed4179c30d0a45d6140d3f'
}
```
You should be able to use searchbox now, but origin code can't work, so change the condition.
```vue-html
<SearchBox
v-if="
isAlgoliaSearch === false &&
(
$site.themeConfig.search !== false &&
$page.frontmatter.search !== false
)
"
/>
```
Use searchBox when disabled algoliaSearchBox.
it work:

fix: the isAlgoliaSearch variable set to boolean type

---

src/guide/mixins.md

State that:
1. Mixins are a __simple__ way to reuse component logic, rather than a flexible way to do it. The term __flexible__ goes into conflict with the last chapter of the page, which describes that mixins are in fact inflexible.
2. Add a section title for Precautions.

Improve Mixins page

---

src/guide/migration/introduction.md

Removing duplicate "to" word in "Other Minor Changes 9th point.

Removing duplicate "to" word

---

src/api/global-api.md

See also: https://github.com/vuejs/docs-next/issues/522

fix: adding examples and modifying parameter descriptions (#522)

---

src/guide/a11y-semantics.md

"setting the labels with an matching id" is incorrect.
Change to "setting the labels with a matching id".

fix: change "an matching id" to "a matching id"

---

src/api/options-misc.md

For the `name` option, I don't think this line still applies in Vue 3:
> **Restriction:** only respected when used as a component option.
The distinction between component options and root instance options no longer exists. We now only have component options.
If you're curious, here's a demo showing `name` working fine on the root component: https://jsfiddle.net/skirtle/7ocdjz65/
Remove that line.

fix: remove the restriction for name, which no longer applies

---

src/guide/composition-api-setup.md

Was not able to run the provided composition template code snippet and realized its because the props object was not returned.
Added the props property and also returned props so the template can reference it.

Resolve props template usage composition api

---

src/api/options-misc.md
src/style-guide/README.md

The `delimiters` option was not included in early Vue 3 pre-releases, so it was removed from the documentation. However, it was reintroduced prior to 3.0.0 being released.
I have added it back in the two places it was mentioned previously. I've made some changes to the wording so you may want to check you're happy with that.
Closes #429.
If anyone knows a better way to escape the default value so that it'll render correctly, please let me know. What I've done does work but it isn't pretty.

Add the delimiters option

---

src/api/options-misc.md

`inheritAttrs` has changed in Vue 3 and the current API reference entry is slightly incorrect.
1. The `class` and `style` are now included in `$attrs`, so they are affected by `inheritAttrs`.
2. The example given doesn't quite work. It emits the `input` event twice due to the listener in `$attrs`.
1. Removed the note about `class` and `style`.
2. Added `emits` to the example, which fixes the double listeners.

fix: update the API reference for inheritAttrs

---

src/api/application-config.md

Removed an API that no longer exists

fix: remove devtools from config

---

src/guide/migration/slots-unification.md

Fix a typo in [Slots Unification](https://v3.vuejs.org/guide/migration/slots-unification.html).

docs: fix typo in Slots Unification

---

src/guide/a11y-semantics.md

The word `instecting` is typo.
`You can see the description by instecting Chrome DevTools:`
https://v3.vuejs.org/guide/a11y-semantics.html#instructions
Labels > aria-describedby
change to `inspecting` from `instecting`.

fix typo: instect -> inspect

---

src/api/built-in-components.md

* Add more examples
* Clarify what `is` can actually accept as its value
* Remove redundant types (ComponentConstructor is not described anywhere)

Update built-in meta component API section

---

src/guide/component-attrs.md

The documentation says that `$attrs` can be accessed by setting `inheritAttrs: false`.
However, `$attrs` can be accessed with or without `inheritAttrs` setting.
The rfcs says the following:
>this.$attrs (and context.attrs for setup() and functional components) now contains all attributes passed to the component (as long as it is not declared as props). 
https://github.com/vuejs/rfcs/blob/master/active-rfcs/0031-attr-fallthrough.md#inheritattrs-false
Remove the following sentence and add the new sentence of this PR, or we change to another explanation.
I hope that you update my docs is wrote with my poor English! 🙇

fix: improve component attrs section

---

src/guide/migration/introduction.md

CodeSandbox added support for Vue3 yesterday allowing you to also install dependencies but since it was added yesterday it's still not here
Adding CodeSandbox
Sorry, I am basically a vulture going around adding CodeSandbox

Add CodeSandbox

---

src/examples/grid-component.md
src/examples/modal.md

fix (#516): incorrect examples codepen

---

src/api/directives.md
src/guide/conditional.md
src/guide/list.md
src/style-guide/README.md

In v3, the precedence of *v-for* and *v-if* when used on the same node is is now switched.
+ v2: *v-for* takes precedence over *v-if*
+ v3: *v-if* takes precedence over *v-for*
Update respective sections of the guide
Close https://github.com/vuejs/docs-next/issues/534

Fixed v-for/v-if priority and explanations

---

src/guide/migration/render-function-api.md

From vuejs/vue-next#2248
Missing some information for vnode structure migration
Adding example about staticClass and staticStyle
[Vue 3](https://vue-next-template-explorer.netlify.app/#%7B%22src%22%3A%22%3Cdiv%20class%3D%5C%22button%5C%22%20%3Aclass%3D%5C%22%7B%20isOutlined%20%7D%5C%22%20style%3D%5C%22color%3A%20red%3B%5C%22%20%3Astyle%3D%5C%22%7B%20color%3A%20'blue'%20%7D%5C%22%3E%7B%7B%20cart.items%20%7D%7D%3C%2Fdiv%3E%22%2C%22ssr%22%3Atrue%2C%22options%22%3A%7B%22mode%22%3A%22module%22%2C%22prefixIdentifiers%22%3Afalse%2C%22optimizeImports%22%3Afalse%2C%22hoistStatic%22%3Afalse%2C%22cacheHandlers%22%3Afalse%2C%22scopeId%22%3Anull%2C%22ssrCssVars%22%3A%22%7B%20color%20%7D%22%2C%22bindingMetadata%22%3A%7B%22TestComponent%22%3A%22setup%22%2C%22foo%22%3A%22setup%22%2C%22bar%22%3A%22props%22 …

add staticClass and style to migration guide

---

src/guide/typescript-support.md

Current link to "Single file components" from the Typescript support page does not point to the correct location.
Update the "Single file components" reference to point to the correct path.

Correct typo in "Single file components" reference

---

src/guide/component-registration.md

I found forgetting to close the parentheses in "Component Registration" reference
add closing parentheses

Add close parentheses in "Component Registration" reference

---

src/style-guide/README.md

The style guide has an example intended to show component options without blank lines between them.
This example acquired blank lines during the migration to Vue 3, so it no longer makes sense.
I have removed the blank lines to match the Vue 2 example.
See the second example in:
Vue 2: https://vuejs.org/v2/style-guide/#Empty-lines-in-component-instance-options-recommended
Vue 3: https://v3.vuejs.org/style-guide/#empty-lines-in-component-instance-options-recommended

Remove blank lines from an example that shouldn't have them

---

src/guide/component-edge-cases.md

In [Handling Edge Cases](https://vue3js.cn/docs/guide/component-edge-cases.html#controlling-updates) page, the link of "Components Basics" has broken and redirect to the 404 page.
The reason is that the link file name of "Components Basics" is not existed. The right name should be "component-basics.md"
Change the link file name from "components.md" to "component-basics.md"
In [Dynamic & Async Components](https://vue3js.cn/docs/guide/component-dynamic-async.html#dynamic-components-with-keep-alive) page, "Components Basics" also has a broken link, but I find nothing wrong with the code.

fix:fix a broken link

---

src/style-guide/README.md

The heading for Priority D rules in the Style Guide is missing.
Add the heading for Priority D rules.
Closes #578.

fix(style-guide): add Priority D heading

---

src/guide/migration/introduction.md

I released eslint-plugin-vue@7.0.0.
But the version of eslint-plugin-vue is listed as `next` in the documentation.
Change the version of eslint-plugin-vue described in the documentation.
https://github.com/vuejs/eslint-plugin-vue/releases/tag/v7.0.0
https://www.npmjs.com/package/eslint-plugin-vue

Change version of eslint-plugin-vue

---

src/guide/composition-api-provide-inject.md

the key of inject is non-existent
```vue
<template>
<MyMarker />
</template>
<script>
import MyMarker from './MyMarker.vue'
export default {
components: {
MyMarker
},
provide: {
location: 'North Pole',
geolocation: {
longitude: 90,
latitude: 135
}
}
}
</script>
```
```vue
<script>
export default {
inject: ['location', 'longitude', 'latitude'] // it is wrong
// inject: ['location', 'geolocation'] // it is correct
}
</script>
```

fix(docs): inject key is the provide key

---

src/guide/typescript-support.md

From typescript-support.md:
`This means you don't need any additional tooling to use TypeScript with Vue - it has a first-class citizen support.`
I'd think that 'It has a [...] support.' does not sound right here.
So either; 1) *It has a first-class citizens' support*, or 2) *It has first-class citizen support* may fit better?
Option 2) technically means that first-class citizens support it. So I'd guess option 1) is the way to go.
I'm not a native english speaker, so forgive me for wasting your time if I'm wrong altogether.
Cheers!

fix, minor grammar. first-class citizen

---

src/api/instance-methods.md

One of the examples uses `const` to declare `unwatch`, which causes a `ReferenceError` to be thrown.
Use `let`, initialised on a separate line.
Closes #575.

Use 'let' in an unwatch example as 'const' causes an error

---

src/api/directives.md
src/guide/template-syntax.md

A couple of the examples for events still refer to `2.6.0+`. That makes sense in the Vue 2 docs but is unnecessary in the Vue 3 docs.
I believe these are the only remaining references of this kind.
Removed the `2.6.0+`.

Remove references to '2.6.0+'

---

src/style-guide/README.md

5 broken links in the style guide, all pointing to `single-file-components.html`.
Updated links to `single-file-components.html`.
Closes #587.

Update links to single-file-component.html

---

src/guide/component-slots.md

Consistent binding with image `/images/scoped-slot.png`

docs: fix example in component-slots.md

---

src/api/composition-api.md

fix https://github.com/vuejs/docs-next/issues/456
Missing `getCurrentInstance` API documentation
Add `getCurrentInstance` docs

feat(api): composition-api `getCurrentInstance`

---

src/guide/migration/filters.md

The Migration strategy for filters was a little short and specifically did not help users with migrating their global filters.
Give users guidance how to migrate globally registered filters with `app.config.globalProperties`

feat(migration-guide): add global filters

---

src/guide/migration/filters.md

A few tweaks to the new guide to migrating global filters.
I think it's mostly self-explanatory but I've made review comments inline just in case.

docs: correct minor problems with the guide to migrating global filters

---

src/api/options-data.md

I think it was `Vue instance` and now need to be `component instance`

docs: fix typo in options-data.md

---

src/guide/custom-directive.md

The *200px* in the paragraph is supposed to change depending on the value of `pinPadding`.
Replace *200*  in the text with `pinPadding` so it updates as the value changes.

make pinPadding value change reflect in the template

---

src/api/composition-api.md

fix typos in https://github.com/vuejs/docs-next/pull/590

docs: typos in composition-api.md

---

src/api/instance-properties.md

The API reference entry for `$el` doesn't acknowledge fragments.
Added an explanation for fragments.
Something similar happens for components that don't render anything due to a root-level `v-if`. I originally intended to mention that too but it just made it harder to understand.
The recommendation to use template refs is taken from this RFC:
https://github.com/vuejs/rfcs/blob/master/active-rfcs/0009-global-api-change.md#mounting-behavior-difference-from-2x

Explain $el for fragments

---

src/api/instance-methods.md
src/api/options-data.md

Vue 3 introduced the `flush` option for watchers. While it is documented in a few places, it isn't mentioned in the API reference for the `$watch` method or the `watch` option.
I've added a complete description under `$watch`, similar to the `deep` and `immediate` options.
For the `watch` option I've only noted its existence and provided a link to `$watch`.
Closes #457.

Add the flush option for $watch

---

src/guide/component-custom-events.md

Starting the paragraph with _In the event_ might cause confusion, since the paragraph is discussing component events vs native events.
Avoid using _In the event_, and use _When_ instead.
We can also emphasize that the native event listener will not be used.

Minor edit to paragraph in Custom Events section

---

src/guide/migration/custom-directives.md

custom directives quite often need access to the component instance. The way to do that changed in Vue 3.
This PR documents that change in the migration guide.

feat(migration):  accessing instance in a custom directive

---

src/api/options-lifecycle-hooks.md
src/api/options-misc.md
src/guide/component-attrs.md
src/guide/component-dynamic-async.md
src/guide/component-provide-inject.md
src/guide/installation.md
src/guide/template-syntax.md
src/guide/transitions-state.md
src/style-guide/README.md

This PR fixes various internal links.
In all cases the current link is pointing at something that doesn't exist. Usually this is because a section has been renamed or moved. In a few cases there was a problem with uppercase letters being used in the link hash.

fix: update broken links

---

src/.vuepress/config.js

Every page of the docs has `<[object Object]>` at the top. Most of the time you can't see it. It's easiest to see on the 404 page, e.g. https://v3.vuejs.org/404
---
---
As noted in #556, it can also be seen on other pages using some mobile browsers.
Example: https://deploy-preview-622--vue-docs-next-preview.netlify.app/404
It is caused by a pair of parentheses in `config.js`:
```js
[
('script',
{
src: 'https://player.vimeo.com/api/player.js'
})
],
```
In this PR I have removed those parentheses.
I am unclear whether this is the correct fix. Whatever that configuration setting was supposed to do, it doesn't seem to matter that it wasn't working. It may be that it can be removed instead.
That section of the configuration was originally introduced by @phanan in #71. At that point it didn't …

fix: remove parentheses from the video player configuration

---

src/.vuepress/theme/components/Newsletter.vue

The original problem was reported in #556. On iOS, the Subscribe button was too short and has a gradient background.
There was an attempt at fixing the height in #625 but that has introduced problems in OSX Safari and recent versions of Edge.
**iOS - the height has been fixed but the gradient remains:**
**Safari (same as Edge):**
The original fix changed `height` to `min-height`. The problem on Safari/Edge is that the button's default height is too large, so a `min-height` doesn't do anything.
I believe the original problems can both be fixed using `appearance: none`.
The new problems can then be resolved by undoing #625.
I've tested across various platforms and as far as I can tell the button now has a consistent height and background.

fix: resolve Subscribe button styling problems on Safari and Edge

---

src/guide/migration/custom-directives.md

Users are copying example from directives docs and getting into a problem where the directive doesn't seem to be working.
Use a string in the example
I've seen this cause confusion several times. The examples don't show a variable `yellow` defined, and because a string is expected the example, as is, will fail. I believe adding the extra `'` quotes will make it clearer, and for anyone copy-pasting won't cause issues. Alternatively, the variable could be shown, but that would make examples longer.

Update v3 directive example to have quoted string

---

src/style-guide/README.md

In the `style-guide` some links were pointing to the old docs.
Update links to point to v3 docs.
Closes #627

[issue/627] Replace occurrences of links pointing to old docs

---

src/.vuepress/theme/components/Navbar.vue

Originally reported in #556, there's an vertical alignment problem with the text of the 'buttons' in the search box. The specifics vary depending on the platform but here's an example:
The text is supposed to be central but instead it's at the top of the buttons.
Further, on small screens the search box is supposed to hide those buttons but currently it does not.
Both problems are caused by the same CSS. `NavBar.vue` sets `display: inline-block` for all descendent `<span>` elements, which includes the search box.
I have removed the relevant CSS.
Testing across various platforms I wasn't able to see any visible change to the `NavBar`, aside from the desired changes to the search box. The various `<span>` elements are now a few pixels shorter but that change isn't visible and I don't …

fix: remove NavBar CSS that was interfering with algolia

---

src/guide/migration/custom-directives.md

style: Unified style

---

src/guide/introduction.md

Added missing free course link, as on the Vue 2 version of the guide https://vuejs.org/v2/guide/

Added free course button on introduction page

---

src/guide/custom-directive.md

The current description says that directives are included to `$attrs` and can be bound to an element with `v-bind="$attrs"`
We need to change the description to reflect the fact directives are not included in `$attrs`

Fix a description for custom directives used on components

---

src/guide/transitions-enterleave.md

One of the `<transition>` examples uses multiple child elements, each with a `v-if`. While it will only have one child at runtime it triggers a template compiler warning about multiple children in a `<transition>`.
Switching to `v-else-if` allows the template compiler to verify the children, removing the error.

Transition needs children to use v-else-if

---

src/guide/composition-api-template-refs.md

The headings in `composition-api-template-refs.md` are `<h2>` and `<h3>`, rather than the `<h1>` and `<h2>` used by every other page.
Remove the extra `#` signs from the headings.

Reduce heading levels for Template Refs to match other pages

---

src/api/refs-api.md
src/guide/composition-api-introduction.md
src/guide/composition-api-setup.md

This was originally reported in #562.
There is a problem with using `toRefs` to destructure props when a prop is optional:
```js
setup (props) {
// This assumes `props` has a title property
const { title } = toRefs(props)
}
```
The documentation seems to encourage this pattern but in practice it fails if the prop is missing as no ref will be created. This not only requires extra work to handle an `undefined` ref but it also causes problems if the prop is subsequently added (e.g. via `v-bind="obj"`).
There are various ways this could be addressed through changes to the library but I've assumed that the current behaviour is correct and should be reflected in the documentation.
In `composition-api-introduction.md` I've just marked all the props as `required`. I didn't want to address the …

Clarify the usage of toRefs and toRef for optional props

---

src/.vuepress/components/MigrationBadges.vue

- Sometimes we need in18 to display the badge vocabulary.
- add dictionary.
[vuejs/docs-next-zh-cn PR](https://github.com/vuejs/docs-next-zh-cn/pull/220/files) :

feat: migration badges support i18n

---

src/guide/typescript-support.md

fix typo at Typing `refs`
When I read the document, I found it strange here.
fix typo.
none.

typo at Typing `refs`

---

src/.vuepress/config.js
src/api/built-in-components.md
src/guide/migration/introduction.md
src/guide/migration/transition-group.md
src/guide/migration/transition.md
src/guide/transitions-list.md

`<transition-group>` no longer renders a root element by default, since Vue 3 now supports fragments.

feat(migration): transition-group (close #648)

---

src/.vuepress/config.js
src/guide/tooling/deployment.md

This is mostly a copy and paste from the v2 docs. As far as I'm aware, I don't think anything major has changed CLI wise from v2 to v3. Let me know if I missed anything @sodatea!
P.S. Feel free to add any other reviewers who might know more about this section.
[Netlify Preview](https://deploy-preview-412--vue-docs-next-preview.netlify.app/guide/tooling/deployment.html)

docs (#18): add deployment page

---

src/guide/tooling/deployment.md

Two broken links in `deployment.md`.
Updated URLs.

Update broken links in deployment.md

---

src/.vuepress/config.js
src/guide/state-management.md
src/style-guide/README.md

New documentation is now available for Vuex 4 but it uses a different URL from the Vuex 3 documentation.
There are several places that the Vue 3 docs link to Vuex. In some cases we link to the Vuex docs, in other cases we link to the GitHub repo.
I've gone through these links and updated some of them to point at the new Vuex docs. There are still some that point at the GitHub repo instead but I felt that was appropriate in those cases.

Update links to point at the Vuex 4 documentation

---

src/guide/migration/children.md
src/guide/migration/introduction.md

`$children` instance property is removed but this removal is not documented. This PR adds a required change to Migration guide
Close https://github.com/vuejs/docs-next/issues/454

Document removal of $children API on Migration guide

---

src/guide/migration/introduction.md

docs: fix typo in migration/introduction.md

---

src/guide/teleport.md

Currently, the link at the top of teleport.md looks terrible. In addition, there is a sentence at the bottom of the file that is missing a period.
This switches the link to using `<VideoLesson>`, which should make it look a lot better. It also fixes the sentence by inserting a period.

Improve formatting of teleport.md

---

src/guide/contributing/translations.md

There is a typo on the "Translations" page.
It is now corrected.

Fix a typo

---

src/guide/component-provide-inject.md

This example might come in handy for users that are yet to read on `Computed and Watch` in the documentation so they know that the properties they're making reactive using `computed` is available under `property.value` and not `property`.

Add inject example to reactive section of docs

---

src/guide/migration/global-api-treeshaking.md

Possible typo in global-api-tree-shaking.

Fix: typo in global-api-treeshaking

---

src/guide/transitions-overview.md

3 small changes to `transitions-overview.md`:
1. Change `<h1>` to `<h2>` for a sub-header.
2. Change *affects* to *effects* as that seems to be what was intended.
3. Change *have* to *make* as I think the sentence reads better that way.

Increase header depth and tweak wording in transitions-overview.md

---

src/.vuepress/config.js

A couple of the migration guides are not currently listed in `config.js`, so they don't appear in the sidebar.
This PR adds them.

Add two migration pages to the sidebar index

---

src/guide/render-function.md

Two of the examples in `render-function.md` have problems, both related to using `h` with components and slots.
The first example tries to create a component using `Vue.h('child'`. This won't work because it needs to use `resolveComponent`.
The second example triggers a warning:
> [Vue warn]: Non-function value encountered for default slot. Prefer function slots for better performance.
You can see it yourself here: https://jsfiddle.net/skirtle/ho9t3upv/
When using `h` to create an HTML element there are various different ways to pass the children. However, when creating a component the children have to be passed as a slot object containing functions, otherwise the warning above is shown.
In the first example I have also adjusted the spacing to accommodate the `Vue.resolveComponent`.
The …

Fix two examples of using h with components and slots

---

src/guide/component-slots.md

When the todo-list is nested in the other todo-list in the yellow box example, there is ambiguity compared with the red box example.
If my understanding is wrong, correct it please. thank you.
Replace the todo-list in the yellow box with template like this

docs: update component-slots.md

---

src/guide/migration/children.md

I've made some tweaks to the migration guide about the removal of `$children`.
For the example, the HTML seemed to be an in-DOM template, whereas the JS seemed to be from an SFC. I've made it all an SFC. I've also removed several attributes from the template that didn't seem to be adding anything to the example.

Revise the migration guide for $children, especially the example

---

src/.vuepress/components/search/index.vue
src/.vuepress/config.js
src/search/README.md

Restored search page that was merged in #363.
The page was removed in https://github.com/vuejs/docs-next/commit/2738ccfc7717b788deda024a977800a340b93235, I'm not sure why but looking at the code it seems like some things were broken after updating the algolia dependencies.
In the first commit of this PR I'm restoring what was already discussed in #363, the new code is on the second commit.

Restore search page

---

src/guide/migration/custom-directives.md

A few small tweaks to `custom-directives.md`.
The **Overview** previously had a list of multiple items. Now there's only one item it doesn't need a list, so I've reduced it down to a single sentence instead.
I've also made a few, small grammatical and consistency changes.

Minor revisions to the migration guide for custom directives

---

src/guide/migration/emits-option.md

Aside from some minor wording tweaks there are three more important changes:
1. I've added a `<div>` to one of the examples for consistency with the earlier example.
2. I've removed the `<p>` and `props` from the later example. That example doesn't work as a fragment, it needs a single root node for `$attrs` to be applied.
3. I've reworded the opening to the **Migration Strategy** section. The opening sentence didn't really work grammatically. I've shuffled it about to make the key recommendation a sentence by itself. The explanation about `.native` is then a separate paragraph. I thought it was important that it also mentioned `$attrs`.

Revise the migration guide for the emits option

---

src/guide/migration/introduction.md

Since this page was first created, the documentation for the `next` versions of both Vue Router and Vuex have gone live. I've updated and added links where it seemed appropriate.
I've also made a couple of small changes to a sentence about Vue CLI. The word *preset* didn't seem to be necessary and seemed more likely to cause confusion than anything else. Removing it also helped to fix the grammar.

Update the migration guide introduction

---

src/guide/typescript-support.md

`.vue` imports in `<script lang="ts">` blocks aren't resolved by default by ts-loader. Attempting to do so will result in a `[Vue warn]: Failed to resolve component: my-component` console error.
Document the required configuration (using the `appendTsSuffixTo` ts-loader option).
Credit:
- https://lmiller1990.github.io/electic/posts/20200406_webpack_for_vue_3.html
- https://github.com/starkovsky/vue3-webpack-boilerplate/blob/master/webpack.config.js#L42

Add TypeScript + Webpack Configuration Tip

---

src/.vuepress/config.js

Currently, the _Migration Guide_ and _Contribute to the Docs_ section are nested in the sidebar under the first docs section (_Guide_). Here're are some minor issues caused by this nesting:
1. **Navigation:** When you click the Migration Guide link from the Docs dropdown menu, the sidebar is not scrolling to the relevant section which could cause confusion. For example, if you're on the top of the [Template refs](https://v3.vuejs.org/guide/component-template-refs.html) section and then click on the _Migration Guide_ from the _Docs_ dropdown, it's not clear there's a list of relevant sub-sections you can navigate to.
1. **Copy**: The Docs dropdown is repeatedly using the _Guide_ keyword in the dropdown options.
1. **Discoverability**: It's hard to locate contribution guidelines.
1. Move …

Move the migration and contribution guidelines in separate sections

---

src/api/instance-methods.md
src/guide/component-basics.md
src/guide/component-custom-events.md
src/guide/list.md
src/guide/migration/v-model.md
src/guide/render-function.md

**Note:** There is a CodePen at the bottom of `list.md` that should be updated to match the code in this PR.
Closes #702.
I have added an `emits` option to examples that `$emit` events. This isn't strictly necessary for any of these examples, as they function correctly without it. However, using `emits` is encouraged elsewhere in the documentation and omitting it can cause problems in situations that are very similar to those in the documentation.
An event listener registered with `@` or `v-on` will be included in the `$attrs` unless it is listed in the `emits`. In most cases this does no harm but it does result in a listener being added to the root DOM node of the component. So long as the event name doesn't coincide with a DOM event name this is largely harmless, though wasteful.
Events …

Add an emits option to examples that emit events

---

src/guide/migration/global-api.md

The introduction of `globalProperties` as a replacement for `Vue.prototype` is not currently mentioned in the migration guide.
I've followed the lead of [the original RFC](https://github.com/vuejs/rfcs/blob/master/active-rfcs/0009-global-api-change.md) and documented it as part of the global API changes.
Fixes #700.

Document migrating Vue.prototype to globalProperties

---

src/guide/routing.md

change the documentation link from https://router.vuejs.org/ to https://next.router.vuejs.org/

updated routing.md

---

src/guide/render-function.md

https://deploy-preview-712--vue-docs-next-preview.netlify.app/guide/render-function.html
I was involved in a couple of threads on the Vue Forum discussing how to use slots in `render` functions. From that it became clear that some key aspects aren't covered in the documentation. I've expanded the relevant section to mention some of the common use cases with explanations of some of the most common pitfalls.
I've added an earlier section explaining the creation of component VNodes. This introduces `resolveComponent`, which was already used in some of the examples but wasn't explained. However, my main objective was to make it more explicit that there are differences between creating VNodes for HTML elements and components. Otherwise the use of component VNodes in the section about slots …

Expand the page on render functions, especially their use of slots

---

src/guide/single-file-component.md

This PR adds a new block to the `single-file-component.md` file with a guide on how to bundle `sfc` with rollup.
The guide is oriented to library authors.
This is the first draft, also I am not completely sure it's the right place to add this, or if is better somewhere else / standalone entry
fixes #660

Add bundling with rollup to docs

---

src/guide/reactivity-computed-watchers.md

While working on #734 I noticed some issues with examples and spelling
I have added a more real example of using an array for `watch` and fixed a couple of syntax errors.

watch guide cleanup

---

src/.vuepress/config.js
src/.vuepress/theme/components/BuySellAds.vue
src/.vuepress/theme/components/CarbonAds.vue
src/.vuepress/theme/layouts/Layout.vue

Closes #30 
I couldn't test locally because the `serve` script fails right away
There are a few necessary changes left to be done to display the ads correctly and mimic vuejs.org

feat: add carbon ads

---

src/.vuepress/theme/layouts/Layout.vue
src/.vuepress/theme/styles/index.styl

config: revert banner

---

src/guide/typescript-support.md

The example under [Annotating Props](https://v3.vuejs.org/guide/typescript-support.html#annotating-props) in the TypeScript Support section of the docs would break the prop type for the component because of the `validator` function.
Give an example of how to correctly use `validators` and `default` values for objects and arrays.
[Related issue](https://github.com/vuejs/vue-next/issues/2474)

docs(ts-support): annotating props with validators and default values

---

src/api/application-api.md
src/guide/custom-directive.md
src/guide/migration/custom-directives.md

Current documentation misses the `created` custom directives hook added in https://github.com/vuejs/vue-next/commit/11804fe93f66d43320498bfea564af1c9f7a9eb7
I've added a new hook to API, Migration guide and Guide
/close https://github.com/vuejs/docs-next/issues/430

feat: added `created` hook to directives

---

src/guide/migration/watch.md

Fix typo (remove the additional 'to')

docs(guide/migration/watch.md): fix typo

---

src/guide/template-syntax.md

Some values cause dynamic attributes to be omitted. The current description of this in `template-syntax.md` is not entirely accurate.
The tricky part of explaining this is the handling of an empty string for boolean attributes. My explanation of why it behaves the way it does is very brief but I didn't want to dwell on an edge case. I hope I've provided enough information for those who are curious without derailing those who aren't.
Closes #711.

Explain how to omit dynamic attributes

---

src/api/instance-properties.md

The API entry for `$attrs` doesn't mention `inheritAttrs`.
I recall an occasion when I couldn't remember the name of `inheritAttrs` and I was surprised that it wasn't referenced directly from `$attrs`.
Adding a link in the **See also** section seemed sufficient.
The format for the link text is copied from other links on this same page.

Add a link from $attrs to inheritAttrs

---

src/guide/component-basics.md

I've revised `component-basics.md`. In a few places there were descriptions of Vue 2 functionality that no longer apply with Vue 3. I've also tweaked grammar and wording in various places.
I've made inline comments for the most significant changes.
There are two things I've removed in multiple places:
1. The word *fortunately*. The word itself is fine but it seems to be introducing core features as though their existence is a lucky coincidence.
2. The expression *keep in mind*. There's an implication in that expression that a concept has been discussed previously. It can't really be used to introduce something new.

Revise component-basics.md

---

src/guide/single-file-component.md

Fix: typo in single-file-component.md

---

src/guide/migration/async-components.md

Wrong option field in async component migration page: https://v3.vuejs.org/guide/migration/async-components.html#_3-x-syntax.
change the wrong option name to correct ones.

fix: error option in async component migration page

---

src/guide/component-basics.md
src/guide/component-custom-events.md

Out current recommendation for custom events name casing are outdated (since `emits` can have an object syntax and in this case, camelCased event name is more natural)
Change recommendation for events name casing to make it consistent with props
Close #656

Changed a recommendation for custom events name casing

---

package.json
yarn.lock

`node-sass` is used to compile Sass styles. However, [it has been deprecated](https://sass-lang.com/blog/libsass-is-deprecated).
Replace `node-sass` with `sass` as recommended:
> - We recommend all existing LibSass users make plans to eventually move onto Dart Sass, and that all Sass libraries make plans to eventually drop support for LibSass.
>
> [...]
>
> If you’re a user of Node Sass, migrating to Dart Sass is straightforward: just replace node-sass in your package.json file with sass. Both packages expose the same JavaScript API.
- [`sass/node-sass` #2952: Mark Node Sass as deprecated](https://github.com/sass/node-sass/issues/2952)

chore: replace node-sass with sass

---

src/.vuepress/config.js

Users had troubles finding the guide in advanced and expected it to be in Reusability and Composition.

refactor: move composition api guide to increase discoverability

---

src/api/application-api.md

See https://github.com/vuejs/vue-next/issues/2922
Fixed here https://github.com/vuejs/vue-next/issues/2922

fix(api): remove arguments of `unmount` api

---

src/guide/migration/array-refs.md

I've fixed 3 problems with these examples.
1. `ref` is unused, close #766.
2. The `setItemRef` function needs an `if` check, otherwise removed nodes will be pushed as `null`. This is effectively the same problem I reported in #353, though in a different part of the docs.
3. The `setup` function should not return `itemRefs`, it's highly misleading. `itemRefs` is reassigned in `onBeforeUpdate` but that won't update the value returned from `setup`. There are other ways to fix this (set the `length` to 0 or wrap it in a `ref`) but this seemed the simplest.

Correct small bugs in the v-for array refs examples

---

src/api/application-config.md

The `isCustomElement` config option only applies when using the runtime compiler. Since most users will be using the runtime-only compiler (eg. via `vue-loader` or `@vue/cli`), they may attempt to configure this option by mistake (eg. [`vuejs/vue-next` #2779](https://github.com/vuejs/vue-next/issues/2779)).
Let's add a note that they may need to configure `vue-loader`'s `compilerOptions` for custom elements to work properly.
The language used is [taken from the migration guide](https://github.com/vuejs/docs-next/blob/master/src/guide/migration/global-api.md#L102).

feat: add note on isCustomElement in runtime-only builds

---

src/guide/migration/global-api.md

I've gone into depth about the problem in #773 but this PR is largely independent of the changes I've proposed there.
In summary, I saw a discussion on Discord where several users were getting confused about migrating a Vue 2 app to Vue 3. The confusion came from the difference between using ESM modules and a CDN build. They had read the migration guide for global API changes but hadn't fully appreciated the differences between ESM and CDN.
To make matters worse, the examples on that page keep flip-flopping between the two styles.
This may not seem like a migration problem but the API change is a significant contributor to the confusion. In Vue 2, everything was done via an object/function called `Vue`. In Vue 3, that object only exists for CDN builds. A familiar-looking object has …

Migration guide: Mention accessing createApp from a CDN build

---

src/guide/migration/functional-components.md

Correctly highlight changed lines in example with functional component

docs: Fix example hightlight in functional-components.md

---

src/api/instance-methods.md
src/api/options-data.md
src/api/options-lifecycle-hooks.md
src/guide/computed.md

It seems that VuePress isn't handling slashes correctly when generating the headings in the sidebar:
As far as I'm aware those slashes aren't required as `$` doesn't have any special significance in the markdown engine we're using.
I've removed any `\` that appeared before a `$`.
Some of these slashes were removed previously in 96499101c150c0e13ecb7d2fb10aedb885bc81a2 but they were reintroduced in 363641a13f600cb965ece3fd1c93210826f61a17. I don't know why.

Remove slashes before dollar signs

---

src/api/global-api.md
src/api/refs-api.md
src/cookbook/debugging-in-vscode.md
src/guide/migration/functional-components.md
src/guide/migration/inline-template-attribute.md

Some of the code blocks were using the wrong language, resulting in incorrect code colouring.
Change the language.

Change the language on some code blocks to match the code

---

src/guide/transitions-list.md

Some h3 must be h2 and added to sidebar

docs: Fix headings in transitions-list.md

---

src/guide/migration/global-api.md

This PR includes several small changes to `global-api.md` in the migration guide, including:
* Remove the `Vue.` prefix in examples that don't really need it. The difference between the ESM and CDN builds is covered near the top so there's no need to include that prefix in the examples that follow.
* Adjust the indentation (lines 31-42) so the example is indented to match the list.
* Change the word *current* to *Vue 2*. I assume the wording was copied from the RFC.
I think the other tweaks are probably self-explanatory but let me know if anything isn't clear.
I did want to change the `Foo` and `Bar` to more meaningful names but I don't understand that example well enough to come up with something suitable.

Small revisions to the global API migration guide

---

src/guide/migration/v-if-v-for.md

I've added links from the migration guide about `v-if`/`v-for` precedence to the relevant sections of the main guide.
The first link goes into more detail about using a `computed` property, whereas the second explains how to use a wrapper `<template>` instead.

Add links to the guide from the migration guide for v-if/v-for

---

src/guide/template-syntax.md

The line breaks in one of the examples in `template-syntax.md` have been mangled, making it harder to understand.
This PR puts the example back to how it is in the Vue 2 docs.

Adjust the line breaks in a template syntax example

---

src/api/application-config.md

The original motivation here was to change the example. It showed `app.config = {...}`, which isn't realistic because you can't assign a new object to that property.
I originally considered giving an example of assigning an individual property but couldn't come up with a tidy example. Instead I changed it to log `app.config`, which shows how to access the object but not much else. In that context it no longer made sense to have the `app.mount` line, so I removed that. The sentence that preceded the example then seemed better placed after the example. Finally, I reworded the opening sentence.

Reword the introduction and example for application config

---

src/guide/reactivity-computed-watchers.md

The way a developer needs to use watch on a proxied object is not well documented. I have outlined more details in #733
Add details about shallow copying and deep copying an object to see both the old and new values of it.

Adding documentation for watch and proxied objects

---

src/guide/component-slots.md

Added slot to todo list component to emphasize the fact that you can replace the content with custom content.
As the sentence states, this won't work without scoped slots.
The code does not make sense for the sentence that follows it:
> We might want to replace the slot to customize it on parent component
Added `<slot>` wrapper to emphasize that there is a slot to customize
I had to read this example a few times to understand which slot is being customized in order to understand.

Added slot to todo list component

---

src/guide/component-slots.md

To me, reading the docs at first, didn't make it very clear how to bind multiple attributes to one slot.
I've added an example how to do it.

Added example how to bind multiple attributes to the same slot

---

src/.vuepress/theme/components/CarbonAds.vue
src/.vuepress/theme/layouts/Layout.vue

The initial problem was the horizontal scrollbar, reported in #793. This would appear below 1300px or 1367px width, depending on the page.
I've also tried to fix edge cases that could occur when the ad overlapped content. In the picture below, the text should not be obscured by the ad:
In this picture, the text `js` should be behind the ad but it is on top instead:
I've removed the CSS from `Layout.vue`. That attempted to create a placeholder but it wasn't necessary. So long as the ad uses margins for positioning, rather than relative positioning, it will push text out of the way without needing the placeholder.
I've bumped up the `z-index` to `5` so that the ad appears in front of the language when it overlaps code examples. This is only applied conditionally so that it won't overlap the …

Try to prevent Carbon Ads from causing problems

---

src/guide/component-custom-events.md

Banner call to action read odd and is not consistent with the rest of the site.

fix: grammar and casing on video title

---

src/guide/component-slots.md

I made a suggestion in #763 that has introduced a problem. The sequence:
```text
`{{ item }}`
```
was supposed to be rendered literally. However, VuePress allows for Vue template syntax within the markdown and only code blocks are exempt. Inline code, surrounded by single backticks, is still be treated as a template.
I've wrapped the code in a `<span v-pre>`.
Another alternative would have been to write it as:
```text
`{{ '\u007b\u007b item \u007d\u007d' }}`
```
That avoids the extra element but on balance I felt using `v-pre` would be easier to understand.

Wrap unintended template syntax with `v-pre`

---

src/guide/typescript-support.md

Currently, we don't have `emits` property described in the TS guide
This PR adds a small example for `emits`
Close #776

Add type inference for emitted events

---

src/guide/render-function.md

This is part of #773. The objective is to make more of the examples agnostic to whether they're using a CDN or ESM build. `render-function.md` is one of the pages where the `Vue.` prefix is most conspicuous so I've started there.
The first example still includes the global `Vue` but it is destructured on the first line to resemble an `import`. Most of the other examples are code fragments so that line is omitted. I have included it whenever a new global function is introduced, to make it clear where it comes from.
Many of the examples just show an isolated `render` function, which makes it tricky to also show the destructuring. I wasn't sure how best to show that, so I included a commented ellipsis. It's a little clunky but it was the best idea I had.
I haven't explicitly acknowledged the …

Use destructuring to access createApp, etc. in render-function.md

---

src/guide/render-function.md

Support for using `keyCode` with `v-on` has been removed in Vue 3 but it was still mentioned in the guide to render functions.
I've removed the reference to `.13`, switched the examples to use `event.key` rather than `event.keyCode`, and generally tried to tidy up the table to make it a little easier to read.
Rendered: https://deploy-preview-807--vue-docs-next-preview.netlify.app/guide/render-function.html#event-modifiers

Using a keyCode with v-on is no longer supported

---

src/guide/component-dynamic-async.md
src/guide/routing.md
src/guide/state-management.md

This is the next PR for #773, following on from #803.
I believe there are 4 pages in the main guide that use a global Vue to access something other than `createApp`. This PR changes 3 of them to use destructuring. I didn't change `installation.md` as that will likely need further thought.

Swap more examples to destructuring for accessing the global Vue

---

src/guide/introduction.md
src/guide/list.md

As explained in https://github.com/vuejs/docs-next/pull/796, we decided to make keys recommended for all cases. To make this more visible, we add `key` to all the code examples after we explained what `key` is

Added keys to examples on List Rendering

---

src/.vuepress/theme/components/Home.vue

I was investigating #195. This doesn't necessarily fix all the problems reported there but it may help.
The Patreon Sponsors on the homepage are shown in grayscale until the page has scrolled to a certain point. I made the following observations:
1. The cached value for `sponsorTop` is not always correct. Elements can move when content loads, it doesn't require a page `resize` for things to move. This could be why #195 observed the transition occurring in a strange place.
2. The listeners were never removed. This didn't actually cause any errors but they do leak when you navigate away to a different page.
3. The code directly manipulates DOM elements rather than using Vue to perform the updates.
4. I don't know why there's a check for `window`. The hook is called during SSR so that …

Refactor the effect on the sponsors and fix a position caching bug

---

src/api/global-api.md

Closes #418.
`mergeProps` is discussed in an RFC here:
https://github.com/vuejs/rfcs/blob/master/active-rfcs/0031-attr-fallthrough.md#in-render-functions
It appears from that description that it is intended to be part of the public API.
I've added an entry to `global-api.md`.
I've based the layout for this entry on the entry for `nextTick`. Personally, I prefer the style used on the Instance Methods page but none of the functions on this page are documented that way.
Rendered: https://deploy-preview-817--vue-docs-next-preview.netlify.app/api/global-api.html#mergeprops

Add an API entry for mergeProps

---

src/guide/installation.md

When I use `vite-app`, `Tailwind CSS` can't work.
Use `@vitejs/app` instead of `vite-app`

Use `@vitejs/app` instead of `vite-app`

---

src/api/basic-reactivity.md

No example on how the unwrapping works when assigning a `ref`
Add a warning since it might be a pitfall if someone is expecting to access the `ref` with `.value` when assigning to a reactive 
This functionality might be referenced else where, but without any clear example (if I recall correctly)

feat: add unwrap example code to reactive

---

src/guide/class-and-style.md

The guidance for using conditional classes is a little bit misleading as the following:
```html
<div :class="[isActive ? activeClass : '', errorClass]"></div>
```
'This will always apply `errorClass`, but will only apply `activeClass` when `isActive`is truthy.'
Can be misinterpreted as:
'This will always apply `errorClass`, however when `isActive` is truthy, it will ONLY apply `activeClass` and nothing else.'
I personally had to take time to test the code myself in order to verify the actual behaviour, which should not be a requirement for documentation readers.
I renamed the above to:
'This will always apply `errorClass`, but `activeClass` will only be applied when `isActive` is truthy.'

docs: updating guidance for conditional class application

---

src/guide/forms.md

The tip on using `input` to listen to IME-based composition input was unclear. In the context of the preceding statement about `textarea` and `input type=text` elements using `input`, it seemed that composition with v-model should work with those inputs.
This change makes it clear that `v-model` should be replaced with a custom `@input/:value` pair.
See [this comment](https://github.com/vuejs/vue/issues/9777#issuecomment-478831263) where @yyx990803 mentions this solution.
See also [this pull request](https://github.com/vuejs/vue/pull/9814) to add a `.eager` feature that would simplify this.

v-model: Clarify IME caveat tip

---

src/guide/composition-api-template-refs.md
src/guide/reactivity-computed-watchers.md

- Watchers are flushed before DOM updated by default (`flush: 'pre'`)
- Template Refs are udpated after DOM updates
- So when watching a template ref, `flush: 'post'` has to be used in order to get a correct element reference at all times.
- Add a new section in the chapter on template refs about this, with an example.
- Link to this new section from the "Effect Flush Timing" section in the Reactivtiy docs.
- This behaviour is unintuitive and has been reported as a bug in vue-next multiple times, see for example: https://github.com/vuejs/vue-next/issues/3030

Document why watched template refs require the`flush: 'post'` option to be set

---

src/api/global-api.md

`useCssModule` is not documented.
Most aspects of using CSS modules are documented as part of Vue Loader, rather than the core of Vue itself. However, `useCssModule` is imported directly from `vue` as part of the global API.
Add an API reference entry.
Rendered: https://deploy-preview-833--vue-docs-next-preview.netlify.app/api/global-api.html#usecssmodule
Issue #476 is related.
I haven't documented `useCssVars`. I'm unclear whether that is even officially supported yet as the only official acknowledgement of it that I can find is in an unmerged RFC: https://github.com/vuejs/rfcs/blob/style-vars-2/active-rfcs/0000-sfc-style-variables.md.

Add useCssModule

---

src/guide/migration/introduction.md

The link to the RFC for using state as CSS vars in `<style>` sections is outdated. Using `<style vars={...}>` no longer works in Vue 3.
Link to the latest RFC to match what is currently supported in Vue 3.

Update SFC state-driven CSS variables link + usage

---

src/guide/typescript-support.md

As suggested in #602, the documentation gives an example of using `<script lang="ts">` but doesn't mention `<script lang="tsx">`, which is required to use `JSX`.
I don't use JSX myself but from a bit of experimenting with Vue CLI it seems to be supported by default on a project that has TypeScript enabled. Adding `lang="tsx"` seemed to be the only step required to use it.
Closes #602.

Mention TSX support

---

src/api/basic-reactivity.md

Wrong comment `obj.value` as below:
```markdown
// it will update `obj.value`
count.value++
console.log(count.value) // 2
console.log(obj.count) // 2
```
```diff
- // it will update `obj.value`
+ // it will update `obj.count`
```

Fix wrong comment in basic-reactivity.md

---

src/api/basic-reactivity.md

This is something that came out of a conversation on Discord.
The API reference for `reactive` already mentions that any `ref` properties will be automatically wrapped/unwrapped.
I've added a similar note to `readonly`. It's a simpler cases because the value can't be changed via a readonly proxy.
I've also added notes to `shallowReactive` and `shallowReadonly`. They don't have automatic unwrapping of `ref`, which came as a surprise to me. From looking at the source code it does appear to be a deliberate design decision for them to work that way.

Mention unwrapping of refs for readonly and shallow proxies

---

src/guide/migration/events-api.md

The Migration guide chapter about the Events API mentions that libraries such as `mitt` and `tiny-emitter` can be used to replace an eventHub that used a Vue instance, but provide no further guidelines.
Add an example demonstrating how to actually replace the eventHub

migration: add example for replacement of eventHub

---

src/guide/composition-api-setup.md
src/guide/reactivity-fundamentals.md

Not explicit on the setup only shallow unwraps the returned object
Explain the shallow unwrapping and also show a possible solution

docs: shallow unwrap on setup

---

src/guide/reactivity-fundamentals.md

There was a typo in the word `nested`.
`::` was used to introduce a tip, which doesn't work. There need to be 3 colons.

Correct a couple of typos in reactivity-fundamentals.md

---

src/api/application-config.md
src/api/built-in-components.md
src/api/global-api.md
src/api/instance-methods.md
src/api/instance-properties.md
src/api/options-assets.md
src/api/options-composition.md
src/api/options-data.md
src/api/options-dom.md
src/api/options-lifecycle-hooks.md
src/api/options-misc.md

This is the latest stage of #773, attempting to make the examples less specific to a particular build.
This PR attempts to remove the `Vue.` prefix from all of the examples in the API Reference. In most cases the examples are only using `createApp`, so the prefix is simply dropped. For examples that use other parts of the global API, where it may not be immediately clear to some readers that a particular function comes from the global API, I've switched the examples to use destructuring instead.
The Global API page itself now has an introduction explaining the two different ways to access the functions listed on that page.
There are some examples that explicitly use `import` to pull in parts of the global API. I haven't changed any of those here, though in a handful of cases that seems …

Reduce the reliance on the global Vue in API Reference examples

---

src/guide/render-function.md

Add documentation about custom directives to the render functions guide. This briefly covers `withDirectives` and `resolveDirective`. Further information is already provided in the API Reference.
Closes #855.

Add a section about using custom directives in render functions

---

src/guide/typescript-support.md

The current example that introduces `defineComponent` is not using an SFC. This seems to be causing some confusion, so I've added an extra example that shows the SFC equivalent. The jump from `const Component = ` to `export default` seems to be one that beginners struggle to make when referring to this page of the docs (based on what I've observed on Discord).
SFCs are already discussed earlier on the page, so this isn't introducing a new concept.
I would also note that the two examples at the bottom of the page suddenly switch to using `export default`. While that doesn't necessarily mean they are SFCs, I think that switch is potentially confusing for anyone trying to follow along. I don't know whether my new example helps much but at least it establishes `export default` as a relevant …

Add an example of using defineComponent in a single-file component

---

src/.vuepress/config.js
src/guide/migration/introduction.md
src/guide/migration/vnode-lifecycle-events.md

Vue 2 had lifecycle events, such as `hook:mounted`. These weren't really documented. The only mention of them in the official documentation that I can find is here: https://vuejs.org/v2/guide/components-edge-cases.html#Programmatic-Event-Listeners. Even that just shows them used in an example, with no direct explanation.
While they tend to be used very sparingly, they were used by a lot of projects, so it's worth having some guidance on migration.
In Vue 3, you can use events such as `vnode-mounted` to achieve a similar effect.
I've added an entry to the migration guide that describes this as a simple renaming. I'm not sure whether that's historically accurate but for practical purposes I think renaming will be enough to migrate code across.
The `hook:` events in Vue 2 didn't include any …

Add a migration guide entry for renaming `hook:` to `vnode-`

---

src/guide/component-attrs.md

Replaced `datetime` attribute with `datetime-local` as proposed in https://github.com/vuejs/docs-next/issues/868
Closes https://github.com/vuejs/docs-next/issues/868

Changed datetime to datetime-local in component attributes guide

---

src/guide/reactivity.md

Fixes #761.
I've migrated this CodePen to the main Vue account, fixing a couple of problems in the process.
Previously, clicking the green Replay button at the end would fail (see #761). This attempted to reload the iframe, which for various reasons doesn't work. I tried some direct replacements but none of those seemed any better.
Instead I tweaked the code to perform a manual reset. Most of the code was already wrapped in functions but I wrapped the remaining code in a function called `init`. I also grabbed the initial `innerHTML` for the main content. Clicking the Replay button now sets the `innerHTML` back to its initial value before rerunning all the same functions that are run when the page first loads.
I also adjusted one of the CSS `height` values from `400px` to `320px`. …

Switch the reactivity/proxies CodePen to the Vue account

---

src/guide/installation.md

- unify to use backquotes for `h4` in the section "Explanation of Different Builds"
- remove some markdown linter warnings:
- [MD009 Trailing spaces](https://github.com/DavidAnson/markdownlint/blob/v0.23.1/doc/Rules.md#md009)
- [MD031 Fenced code blocks should be surrounded by blank lines](https://github.com/DavidAnson/markdownlint/blob/v0.23.1/doc/Rules.md#md031)

chore(installation): unify and fix some markdown styles

---

src/.vuepress/config.js
src/guide/migration/introduction.md
src/guide/migration/props-data.md

Currently, we don't reflect in the Migration guide that `propsData` option was removed. This PR aims to fix this
Close https://github.com/vuejs/docs-next/issues/848

Added `propsData` to migration guide

---

src/guide/reactivity.md

Fix typo, track function name should be 'track' instead of 'effect'

---

src/guide/installation.md

Closes #753.
This PR adds a fourth option to the installation guide: downloading the JS file from the CDN and hosting it yourself.

Add self hosting Vue as an option in the installation guide

---

src/.vuepress/config.js
src/guide/migration/introduction.md
src/guide/migration/suspense.md

Issue: #328
Rendered: https://deploy-preview-912--vue-docs-next-preview.netlify.app/guide/migration/suspense.html
This adds a basic introduction to `<suspense>` within the migration guide. As an experimental feature it has not yet been added to the main guide or the API Reference. An entry in the migration guide should allow more people to try it out.
I put together a JSFiddle, based on the Vue Router example, for anyone who wants to experiment with this:
https://jsfiddle.net/skirtle/wyd2fveg/
* Current implementation: https://github.com/vuejs/vue-next/pull/2099
* Usage with Vue Router: https://github.com/vuejs/vue-next/issues/2143#issuecomment-694640896

Add an introduction to suspense to the migration guide

---

src/.vuepress/config.js
src/.vuepress/public/images/lifecycle.svg
src/api/application-api.md
src/api/options-dom.md
src/guide/migration/introduction.md
src/guide/migration/mount-changes.md

Close https://github.com/vuejs/docs-next/issues/924

Mention application mounting changes in migration guide and API

---

src/guide/migration/mount-changes.md

A couple of examples in `mount-changes.md` seemed to be missing `>`.

Add missing angle brackets to examples in mount-changes.md

---

src/guide/optimizations.md

Closes #451.
In addition to migrating the CodePen to the Vue account, I have made the following changes to the Haml. Emphasis mine:
Line 9:
> The virtual DOM **in** is a lightweight JavaScript object, created by this render function
> The virtual DOM is a lightweight JavaScript object, created by this render function
Line 15:
> If we need to update the list items, we do so in **javascript**
> If we need to update the list items, we do so in **JavaScript**
Line 17:
> The Virtual DOM allows us to make performant **update** our UIs!
> The Virtual DOM allows us to make performant **updates to** our UIs!
Line 92:
> = succeed "," do
> = succeed ", **[**" do

Switch the Virtual DOM CodePen to the Vue account

---

src/guide/migration/introduction.md

Closes #931.
I've removed the mention of 2020 and tried to provide a more accurate description of the current status of the supporting libraries.

Update the supporting libraries section of the migration guide

---

src/style-guide/README.md

There are two style guide examples that use `$emit`. This PR introduces a corresponding `emits` option for them.
For the first example, with the `input` event, this is a required change to prevent the native event being passed up. The example doesn't work as currently written. This was something I noted in the discussion for #859.
For the second example, it does work without the `emits` but I believe using `emits` would still be considered best practice.

Add an emits option to style guide examples that use $emit

---

src/guide/migration/introduction.md

Related to #420, though arguably the scope of that issue is much larger than the changes here.
This PR just adds a note to the migration guide that `set`, `delete`, `$set` and `$delete` have been removed.

Migration guide: mention the removal of set, delete, $set and $delete

---

src/.vuepress/config.js

Closes #866.
The current date/time format in the footer of each page is only really appropriate for a US audience. I've switched it to something a little more neutral:
```
2021-03-07, 23:03:47 UTC
```
While there are plenty of locales where this format would not be used in everyday life, it is much easier to guess how to interpret it. It is based on ISO 8601, though I decided going all-in with `2021-03-07T23:03:47Z` would be too confusing.

Use a less ambiguous date format for 'Last updated'

---

src/guide/reactivity.md

Rendered: https://deploy-preview-934--vue-docs-next-preview.netlify.app/guide/reactivity.html
This started as an attempt to make some small tweaks to the Reactivity in Depth page. One tweak led to another and the end result is a significant reworking of the existing page. Much of the original structure remains but the diff will likely be a mess and I suggest that any reviewers approach it is as though it were a new page.
The biggest addition is a section about effects. The term 'effect' is used by subsequent pages in the guide (e.g. when discussing effect flush timing) but it wasn't really explained anywhere. It also appears in the animation at the bottom of this page. To my mind, this is a really important concept that forms a key part of the 'how reactivity works' puzzle. Once the …

Rework the Reactivity in Depth guide

---

src/guide/migration/custom-elements-interop.md
src/guide/migration/introduction.md
src/guide/template-syntax.md

Inclusive language has gained importance by the growing awareness of language's effects on minorities' struggle for equality. Alternatives are substituting terms like blacklist, master, and slave with words without race connotation.
Changed occurrences of whitelisting to allow listing.
Did not change the reference in the link ".../src/globalsWhitelist.ts#L3" inside file "\src\guide\template-syntax.md" since it is a link to another repo. A change there will need to take place before or in sync.

proposal of 'allow listing' as an inclusive alternative to 'whitelisting'

---

src/guide/component-custom-events.md

This came from a conversation on Discord where someone got confused by this example.
`email` and `password` are used inside the method but it isn't clear where they come from. While making them `data` properties would probably be more realistic, adding them as arguments is a simpler change.

Convert unexplained variables to arguments in an emits example

---

src/guide/ssr.md

Currently, our SSR guide mentions only DIY approach, Quasar and Nuxt. With Vite SSR becoming more stable we should add it to the list of possible approaches

Added Vite mention to SSR guide

---

src/guide/typescript-support.md

See https://github.com/vuejs/vue-next/issues/2220 and https://github.com/vuejs/vue-next/issues/2701 .
The lack of documentation have made many people wonder how to solve TypeScript errors caused by custom types in `globalProperties`, so I tried to fix it.
I added a chapter to the document to explain the origin of this problem and how to solve it.
In addition, I also found a small sample code syntax error in this document and corrected it.
> In an object, the lack of a comma between the methods will cause a syntax error.

docs: Add type definition for `globalProperties` in TypeScript chapter.

---

src/guide/routing.md

The link is to the repository of vue-router 3 for Vue 2.
Link the repository of vue-router 4.

Link vue-router-next in routing page

---

src/style-guide/README.md

Closes #974.
An external link in the style guide is giving a 404.
The new link appears to be the same spec based on what I could see on the Wayback Machine. The new URL is already being used in `component-registration.md`.

Update broken link to the custom element spec

---

src/examples/elastic-header.md
src/examples/markdown.md

This PR migrates the Markdown and Elastic Header examples to the Vue CodePen account.
The examples themselves should not have changed.

Migrate two example CodePens to the Vue account

---

src/.vuepress/components/guide/contributing/translations-data.js

Add french translation in the community translation table
It is the first time I'm  contributing to an open source project, so I don't know if I'm doing it the right way.
I translated almost 60% of the documentation in french. 
you can see the deployed site here : https://vue3-fr.netlify.app/
and the repo: github.com/demahom18/docs-next

French translation

---

src/api/built-in-components.md
src/guide/render-function.md

Closes #554.
The built-in components need to be imported to use them with a `render` function or `<component :is="...">`.
Despite appearing to be globally registered, they aren't. Instead, the template compiler has special handling to allow them to be used without global registration, allowing for tree-shaking. This makes it not immediately obvious how to use them in other scenarios.

Using built-in components with render and :is

---

src/guide/a11y-semantics.md

This PR migrates the 10 CodePens on the page `a11y-semantics.md` to the Vue account.
Rendered: https://deploy-preview-983--vue-docs-next-preview.netlify.app/guide/a11y-semantics.html

Migrate a11y-semantics.md CodePens to the Vue account

---

src/guide/a11y-basics.md
src/guide/reactivity.md
src/guide/transitions-overview.md

Once this and #983 are merged there should only be one CodePen remaining that is not on the Vue account. That's the animated Wall-E demo and I'm unclear whether that should be migrated.

Migrate 3 CodePens to the Vue account

---

src/.vuepress/theme/layouts/Layout.vue

I believe the problem is that hydration fails in production because state gets changed in `beforeMount`.
This not only breaks the Vue Mastery Banner but also the search box.

Fix banner bug that also broke the search

---

src/api/application-api.md
src/api/global-api.md

Closes #997.
This PR documents `Vue.version` and `app.version` in the API reference. These are two different ways to access the current Vue version.
In Vue 2, we just had `Vue.version`: https://vuejs.org/v2/api/#Vue-version. When interacting with a global `Vue` object, e.g. for CDN usage, the equivalent in Vue 3 would be exactly the same, `Vue.version`.
For plugins, the first argument passed to `install` was previously `Vue`. It's now `app`, which also exposes a `version` property. This allows plugins to check the version using the `version` property of that first argument.
I borrowed much of the wording and example code from the Vue 2 documentation.

Add Vue.version and app.version to the API reference

---

src/api/global-api.md

Remove an unnecessary word.
Closes #998.

Remove duplicate word 'returns' from h description

---

src/guide/mixins.md

In Vue 2, `data` from mixins was merged recursively. This is no longer the case in Vue 3:
https://v3.vuejs.org/guide/migration/data-option.html#mixin-merge-behavior-change
I've updated the page about mixins to remove the word 'recursive'. I've also reworded that paragraph to distinguish between the `data` functions and the objects they return.

Mixins don't recursively merge data

---

src/guide/mixins.md

I've changed the heading for the final section from *Precautions* to *Drawbacks*. I think that's a more accurate reflection of what's in that section.
For the first item in the list I've changed the word 'feature' to 'mixin'. Nowhere else on this page refers to mixins as features.
I've added a middle item to the list that discusses the problem of figuring out where properties come from when using mixins. That seems worthy of a separate point to me, though it does overlap a little with the previous item. I've removed the words 'and for debugging' from that first item as I think this is what it was alluding to.
For the final item I've just changed the punctuation.

Add to the list of drawbacks for mixins

---

src/guide/render-function.md
src/guide/transitions-list.md

This adds a short section about functional components to the render functions page. The positioning is the same as in the Vue 2 docs.
I originally wrote a lot more material, including a proper example, but in the end I decided to cut it down to a minimal description of the key technical details and leave it at that.

Add a section about functional components

---

src/guide/migration/async-components.md

The docs around async components can be a bit confusing when people use Vue Router, hopefully this change clarifies the use of async component with Vue Router a bit.
- Change the example of `NextPage.vue` to a more generic `Modal.vue`
- Add a note about async components and Vue Router, with a link to the relevant section in the Router docs.
Relates to issue: https://github.com/vuejs/docs-next/issues/1013

docs: :memo: clarify async components for Vue Router

---

src/guide/a11y-basics.md
src/guide/component-edge-cases.md
src/style-guide/README.md

This PR implements one of the formatting changes suggested in #1009. It removes spaces between the triple backticks at the start of a code block and the language name. It should have no impact on the deployed site.

Remove spaces between triple backticks and the language

---

src/guide/render-function.md

This adds a section to the page on Render Functions explaining the possible return values.

Return values for render functions

---

src/guide/migration/custom-directives.md
src/guide/migration/filters.md
src/guide/migration/listeners-removed.md
src/guide/render-function.md
src/guide/single-file-component.md

A handful of code blocks were using `javascript` for the language instead of `js`. This PR brings them into line with the others. It doesn't make any difference to how VuePress renders them: it shows the language as `js` either way.

Switch javascript code blocks to js

---

src/guide/a11y-basics.md
src/guide/composition-api-lifecycle-hooks.md
src/guide/migration/global-api.md

This is another PR based on #1009.
This shouldn't impact the rendered output, it just lines up the columns in the markdown.
`global-api.md` had a rogue, empty column on the final row. It didn't actually render as a column and I've removed it.

Tidy up the markdown tables

---

src/guide/composition-api-provide-inject.md

fix import closed quote

---

src/guide/typescript-support.md

Old link refer to deprecated page

docs: Update link & fix prop name in typescript-support.md

---

src/guide/migration/key-attribute.md

Fix example, because now there is a warning about duplicated keys

docs: Update key-attribute.md

---

src/.vuepress/theme/styles/index.styl

Bold text currently has a `font-weight` of `500`. As noted in #844, this doesn't really stand out from normal text.
The default for VuePress is `font-weight: 600`. This same weight is used in a few other places, such as headings. A weight of `500` was introduced to the docs in #202 and #245, with the latter changing `<strong>` tags.
Having discussed this with @NataliaTepluhina and @bencodezen, it doesn't seem there's a compelling reason to continue using `font-weight: 500` for `<strong>` tags. This PR reverts it to `600`.

Set the font-weight for strong tags back to 600

---

src/guide/component-basics.md
src/guide/component-dynamic-async.md
src/guide/events.md
src/guide/forms.md
src/guide/list.md

Fixes #996.
Some of the CodePens were causing the page to jump when they loaded. It needed a specific set of configuration options to trigger the problem, so only a handful needed updating.
Where possible I have hidden the HTML tab by default. I used this approach whenever the HTML was already shown in a code block.
In cases where that wasn't possible I've removed the `:preview="false"`. This requires the user to click before the CodePen does anything.

Prevent CodePens from stealing focus and scrolling the page

---

src/.vuepress/components/guide/contributing/translations-data.js
src/.vuepress/config.js

Finally! :)
Some points:
It's convenient for me to save English localization files to make it easier to merge from upstream without conficts and later compare files side-by-side. That why russian locale stored in `/ru/` folder and not as default `/`
---
Links for page now contain doubled `ru`, for example `https://v3.ru.vuejs.org/ru/guide/introduction.html`. That's because vuepress didn't offer a way to pre-set default locale. Rewrite russian locale files as default locale is not useful (see above)
---
Root README.md file for english locale duplicated from russian. I don't know how to show /ru/README.md file if I need to show russian locale as default one.
---
Also had to duplicate translation here, because vuepress at start page show /README.md for english locale and not /ru/README.md …

docs: Russian translation

---

src/.vuepress/config.js
src/cookbook/automatic-global-registration-of-base-components.md

In #43 there is a proposal by @bencodezen to move "### Automatic Global Registration of Base Components" to Cookbook.
I updated the Vue 2 example and added a page inside Cookbook.
Related to #565

docs: add automatic global registration to cookbook

---

src/api/composition-api.md
src/guide/composition-api-lifecycle-hooks.md

All hooks were not mentioned in the list of lifecycle hooks in the new docs, also mentioned in #1018
Updated the docs

Add onActivated and onDeacitvated hooks to the list

---

src/guide/ssr/getting-started.md

Node.js 10 is now EOL
https://nodejs.org/en/about/releases/
Update the recommended minimum version

docs: update recommended node version

---

src/guide/introduction.md

Remove IE 11 compatibility build mention

---

src/guide/class-and-style.md

Closes #1059.
I've tried to give a little more detail about how the auto-prefixing of styles works. Specifically:
1. I've removed the mention of `transform` as that hasn't needed prefixing for ages.
2. I've tried to make it clearer that a prefixed style will only be included if it is required by the current browser. The previous wording may have led some people to expect to see multiple, prefixed properties, similar to what you might get in a CSS file. I think that was the underlying source of confusion in #1059.

Elaborate on how style auto-prefixing works

---

src/guide/component-props.md

A couple of examples in `component-props.md` were written in an ES5 style, so I've switched them to be a bit more consistent with the other examples.

Use method shorthands and switch indexOf to includes

---

src/.vuepress/config.js
src/guide/migration/transition-as-root.md
src/guide/migration/transition-group.md
src/guide/migration/transition.md

Closes #738.
RFC: https://github.com/vuejs/rfcs/blob/master/active-rfcs/0017-transition-as-root.md
When a `<transition>` is used as the root node of a component it can no longer be triggered by toggling a `v-if` from outside the component.

Add transition as root to the migration guide

---

src/guide/state-management.md

Time-travel demo gif URL points to nonexistent branch
Change URL to legacy branch

Fix: broken gif url

---

src/guide/composition-api-introduction.md

According to the content of the vue3 source code, the component instance has been created when the setup is executed.
But the description in the document is not created, so `this` cannot be used.
According to the original, `this` cannot be used because this is not bound to this during setup, and props, etc. cannot be used because options such as props, data, compute, etc. will be processed later.
Modified the description information, which is relatively more accurate and will not cause misunderstandings.
Thanks for the excellent documentation.

The description of `this` in setup is inconsistent with the source code

---

src/api/built-in-components.md

Previously, the docs did not make clear that the `activated` hook is called for the entire component tree that is kept alive, and that `mounted` and `unmounted` are not called anywhere in that tree.
Update the docs.

Update keep-alive hook documentation

---

src/guide/class-and-style.md
src/guide/computed.md
src/guide/conditional.md
src/guide/data-methods.md
src/guide/events.md
src/guide/forms.md
src/guide/installation.md
src/guide/list.md

This PR adds Vue School links to the documentation to supplement the documentation with free training videos. 
The lessons are up-to-date, V3 versions of previously approved Vue 2 lessons that were added to the documentation in [PR 2379](https://github.com/vuejs/vuejs.org/pull/2379). As requested in [PR 311](https://github.com/vuejs/docs-next/pull/311)
[Screenshots of the placements can be seen here](https://imgur.com/a/1G4UGNo)
**Lessons**
[Class Binding](https://vueschool.io/lessons/dynamic-css-classes-with-vue-3)
[Event Handling](https://vueschool.io/lessons/user-events-in-vue-3)
[Computed Properties](https://vueschool.io/lessons/computed-properties-in-vue-3)
[Conditional Rendering](https://vueschool.io/lessons/conditional-rendering-in-vue-3)
[List …

Vue 3 vueschool links

---

src/api/application-config.md
src/api/composition-api.md
src/api/directives.md
src/api/options-misc.md
src/api/special-attributes.md
src/guide/component-basics.md
src/guide/composition-api-introduction.md
src/guide/migration/custom-elements-interop.md
src/guide/migration/global-api.md
src/style-guide/README.md

3.1 Updates

---

src/guide/ssr/routing.md

When not awaiting route push I get an error in the console "Hydration completed but contains mismatches" and the routes do not behave as expected i.e. when navigating to a different page using router-link the content of router-view does not get rendered.
await router push
N/A

fix: await router push in ssr server

---

src/.vuepress/public/images/lifecycle.svg

Closes #1077.
I've reworked the entire SVG but at first glance it should appear almost the same as it was before. I've nudged various things around by a pixel or two to try to make sizes and spacing a little more consistent but most of that won't be obvious unless you directly compare the old and new images. The file size is significantly smaller, though that wasn't a priority.
I've tested on Chrome, Firefox, Edge and Safari across a range of platforms and I'm not aware of any remaining problems or inconsistencies. `dominant-baseline` is probably the feature of most concern as it's a relatively new addition. While it does work fine in all of the browsers I tested, it didn't work in some non-browser image viewers I tried. This may cause the text to be positioned a few pixels too high. I …

Update positioning in lifecycle diagram

---

src/.vuepress/config.js
src/guide/security.md

Closes #643.
This migrates the security guide from the Vue 2 documentation.
I've split this into 2 commits to make it easier to review. The first commit is just a dump of what is in Vue 2 and the second commit makes the necessary changes to update it for Vue 3.

Migrate security guide from Vue 2

---

src/guide/migration/migration-build.md

A bracket is missing from the vue.config.js configuration example, this change would add in the missing bracket so the code example is valid.
In the code example for vue.config.js to add the compat rule, a bracket is missing which results in an error when copy/pasted.
The proposed solution would be to add in the bracket, so that the code example is correct and valid.

Correct vue.config.js example

---

src/.vuepress/theme/components/BannerTop.vue

This PR changes the banner on top of v3.vuejs.org to inform visitors that it's less than 48 hours before the Summer Sale expires.
Please merge on Monday, 2021-06-21.
[Click here to see the visuals of the banner.](https://imgur.com/a/HkWMb3t)
Related to [PR 1082](https://github.com/vuejs/docs/pull/1082)

Update Vue School banner

---

src/.vuepress/theme/components/BannerTop.vue

This PR changes the banner on top of v3.vuejs.org to inform visitors that it's only a few hours before the Summer Sale expires.
Please merge on **2021-06-24** around **5:00 pm CEST**.
[Click here to see the visuals of the banner.](https://imgur.com/a/TX9UC0d)
This solves the issue mentioned on https://github.com/vuejs/docs/pull/1103
Related to [PR 1082](https://github.com/vuejs/docs/pull/1082)

Update Vue School Summer Sale banner

---

src/guide/composition-api-template-refs.md

when using the `flush: 'post'` option,  print error 
```javascript
//<div></div>
```
modify
```javascript
//<div>This is a root element</div>
```

fix typo in composition-api-template-refs.md

---

README.md
src/.vuepress/components/guide/contributing/translations-data.js
src/.vuepress/config.js
src/guide/contributing/translations.md

`vuejs/docs-next` is now `vuejs/docs`.
Signed-off-by: Takuya Noguchi <takninnovationresearch@gmail.com>

fix: docs-next is now docs

---

src/guide/typescript-support.md

Close #927
Props to @TheDutchCoder for the examples!

Add TypeScript example for event handling

---

src/.vuepress/config.js
src/.vuepress/theme/components/NavLink.vue
src/.vuepress/theme/layouts/404.vue

@Jinjiang @veaba @kazupon @naokie @narusas @ChangJoo-Park @Alex-Sokolov This will impact the translations, so could I get any feedback you might have?
Related issues: #1080, #932.
In the Vue 2 documentation, links to the translations have the same path as the current page. This PR attempts to recreate that for Vue 3.
The translations will never be in perfect sync with this repo, so when pages are added, moved or removed they will hit a 404. My proposed strategy for handling that is:
* Remove the `noreferrer` attribute from these links so that the 404 page can tell where the user came from.
* If the user came from an alternative translation, show a longer message on the 404 page that attempts to explain why that might have happened.
The 404 page previously showed one of 4 different …

Link directly to equivalent pages in translations

---

src/guide/typescript-support.md

In the `Annotating Props` section of the chapter `Typescript Support`, it is not clear how to annotate a property with any or a union type. 
Extend the example with a union type property and an any property.

Improve Example for TypeScript Property Annotation

---

src/api/global-api.md

The props passed to `createApp` are raw props, so they can include attributes and event listeners as well as actual component props. This PR attempts to clarify that.
The original motivation was a Discord conversation about trying to migrate a `$on` call from Vue 2. In some cases it is possible to achieve the same effect by using a root prop like `onClick`. I intend to put in a separate PR to expand the migration guide page about `$on` to cover this use case.

Elaborate on what can be included in the createApp root props

---

src/guide/migration/events-api.md

The main changes here are:
1. Rename event hub to event bus.
2. Add some content discouraging the use of event buses. I've seen several examples on Discord where people used this page as proof that an event bus is an officially-endorsed strategy for handling component communication.
3. Add an explanation about passing events to the root component via `createApp`.
My bullet-points outlining alternatives to an event bus are somewhat terse. There's a huge amount of material that could be explored on that topic and explaining it in depth would need a whole page to itself. That said, I thought it was important to make some attempt at suggesting alternatives rather than just discouraging event buses.
I've moved the link to the migration build to the top of the 'Migration Strategy' section. I've …

Add various improvements to the Events API migration guide

---

src/guide/migration/keycode-modifiers.md

The original motivation here is trying to explain how to handle punctuation characters. The RFC doesn't seem to acknowledge this problem. `event.key` exposes printable keys as single-character strings, equal to the printable character. There is no 'kebab-case named' equivalent, you just have to write the character literally in the attribute. In many cases that isn't possible as the character isn't syntactically valid. I'm not aware of any workaround for this, aside from not using the modifier.
I've also changed the existing example. The `delete` key has special internal handling, so I don't think it's the most suitable choice for an example. `page-down` illustrates the use of kebab-case. The `q` example illustrates how the conversion to kebab-case results in letters being matched …

Extra examples of migrating keyCode modifiers

---

src/guide/reactivity-computed-watchers.md

These are superficial changes to the code style. Switching `"` to `'`, removing semi-colons and commas, adjusting spacing. It should be consistent with the rest of the docs.
I haven't changed the use of `"` for log output. In practice, browsers either don't show the quotes at all or use `"`, so I've left those as `"`.

Code style in reactivity-computed-watchers.md

---

src/guide/migration/migration-build.md

Config name in docs is wrong
```
[Vue warn]: Invalid deprecation config "ATTR_ENUMERATED_COERSION".
```
Correct typo
https://github.com/vuejs/vue-next/blob/03e26845e2c220b1350a35179acf3435e2711282/packages/runtime-core/src/compat/compatConfig.ts#L54

fix: typo on "ATTR_ENUMERATED_COERCION"

---

src/guide/mobile.md

link native-vue in mobile.md page is redirect to broken link "https://nativescript.org/vue/"
fix redirect link to "https://nativescript-vue.org/"
https://v3.vuejs.org/guide/mobile.html#hybrid-app-development

fix: broken redirect url

---

src/guide/migration/introduction.md

`@vitejs/app` is now [deprecated](https://github.com/vitejs/vite/pull/4179). We should instruct users to use the new `create-vite` package instead.

chore: update migration installation instructions for Vite

---

src/guide/installation.md

`@vitejs/app` is now [deprecated](https://github.com/vitejs/vite/pull/4179). We should instruct users to use the new `create-vite` package instead.
Also, I got rid of the mention of `create-vite-app` since that package is deprecated and says to use `create-vite` instead.

chore: update installation instructions for Vite

---

src/guide/migration/custom-directives.md
src/guide/migration/introduction.md

Closes #758.
Related issues from `vue-next`:
* https://github.com/vuejs/vue-next/issues/3107
* https://github.com/vuejs/vue-next/issues/4029
#1005 attempted to document the same change but the author didn't respond to my feedback, so I'm opening this PR to replace it.
I've only documented the removal. I haven't provided a migration path or rationale for the change because I don't have that information.

Document the removal of binding.expression for directives

---

src/api/options-composition.md

I've updated the API reference entries for `mixins` and `extends`:
* Mention the composition API in the entry for `mixins`.
* Reword the entry for `extends` to better reflect Vue 3. Using a function/constructor is no longer a thing and `Vue.extend` doesn't exist anymore.
This PR replaces #1129.

Update the API entries for mixins and extends

---

src/.vuepress/theme/components/Newsletter.vue

Changed the subscribe button cursor to pointer as all buttons on the page have pointer cursor to make it consistent.

feat: added cursor pointer to ensure consistency

---

src/guide/reactivity-computed-watchers.md

Close https://github.com/vuejs/docs/issues/1154

Extended watching multiple sources explanation

---

src/.vuepress/config.js
src/api/computed-watch-api.md
src/api/directives.md
src/api/effect-scope.md
src/api/global-api.md
src/api/reactivity-api.md
src/api/sfc-script-setup.md
src/api/sfc-spec.md
src/api/sfc-style.md
src/api/sfc-tooling.md
src/guide/introduction.md
src/guide/reactivity-computed-watchers.md
src/guide/single-file-component.md
src/guide/typescript-support.md
src/guide/web-components.md

- Added dedicated API pages for SFC spec, tooling & features
- Added "Vue and Web Components" section
- various 3.2 features

3.2 updates

---

src/guide/list.md

Inspired by #1161, this PR adds a link from the guide discussing using `key` with `v-for` to the relevant style guide entry.

Link to the style guide entry for keyed v-for

---

src/guide/conditional.md
src/guide/transitions-list.md

Links without a `.html` extension cause redirects, which strips off the `#` portion of the URL and prevents the page from scrolling to the correct section.
I've only updated the two links that have a `#` portion.

Avoid redirects by including .html on links

---

src/guide/migration/introduction.md

since vue 3.2 they're not experimental anymore?

docs: remove script setup experimental badge & update links

---

src/guide/installation.md

Double dashes in the scaffolding command with vite
```sh 
npm init vite <proj-name> -- --template vue
```
```sh 
npm init vite <proj-name> --template vue
```

fix: double dashes in command with vite

---

src/guide/migration/v-bind.md

It's'  `attribute`  rather than `property` .
Change `property` to `attribute`
This correction will make the docs more precise and easier to understand
I try attribute with 'foo', the result is just like the expect.

Change `property` to `attribute`

---

src/guide/migration/custom-elements-interop.md

`is` is special attribute 
https://v3.cn.vuejs.org/api/special-attributes.html#is
Change `is` prop to `is` attr

Change `is` prop to `is` attr

---

src/guide/migration/attribute-coercion.md

There are some mistakes in the comparison table.
See the diff.

docs: fix the description for enumerated attributes coercion change

---

src/api/sfc-script-setup.md

The `<script setup>` documentation sometimes used `we` and sometimes used `you`.
The `<script setup>` documentation was unclear about whether `defineProps` was the _only_ way to define props in `<script setup>`; it referred to the "props option," making it ambiguous about whether that option would still be in use.
Edits for clarity below.

Script Setup Edits for Clarity

---

src/guide/migration/custom-directives.md

For consistence: rest of the hooks used `called`.

docs: Update custom-directives.md

---

src/guide/ssr/routing.md

Closes #1219.
A memory history is stateful, so the server should create a new instance every time.
For reference, this is how the Vite SSR example is implemented:
https://github.com/vitejs/vite/blob/46ecda4df229e4cf3e9e364cb6271198f9fdfc40/packages/playground/ssr-vue/src/router.js

Create a new SSR router history for each router instance

---

src/.vuepress/config.js

added viewport meta tag in vitepress config
Signed-off-by: Anik Das <anikdas0811@gmail.com>
Vue docs in Firefox mobile isn't responsive
```js
['meta', { name: 'viewport', content: 'width=device-width, initial-scale=1.0' }],
```
to the vuepress config under head

fix: firefox mobile view fixed (Closes #1217)

---

src/api/special-attributes.md

```js
export type VNodeProps = {
key?: string | number | symbol
ref?: VNodeRef
// vnode hooks
onVnodeBeforeMount?: VNodeMountHook | VNodeMountHook[]
onVnodeMounted?: VNodeMountHook | VNodeMountHook[]
onVnodeBeforeUpdate?: VNodeUpdateHook | VNodeUpdateHook[]
onVnodeUpdated?: VNodeUpdateHook | VNodeUpdateHook[]
onVnodeBeforeUnmount?: VNodeMountHook | VNodeMountHook[]
onVnodeUnmounted?: VNodeMountHook | VNodeMountHook[]
}
```
https://github.com/vuejs/vue-next/blob/v3.2.11/packages/runtime-core/src/vnode.ts#L92

docs: Add a missing type `symbol` to the `key`

---

src/guide/migration/transition-group.md

docs: Change `tag` prop to `tag` attribute

---

src/.vuepress/components/community/team/emeriti.js
src/.vuepress/components/community/team/members.js

Moving my status into emeritus 👋❤️

Sarah into emeritus status, v3 repo

---

src/api/composition-api.md
src/api/options-composition.md
src/api/options-data.md
src/guide/composition-api-setup.md
src/style-guide/README.md

Vue 3.2 introduced `defineExpose`, the `expose` option, and the `expose` function in the `setup` context object. While `defineExpose` is documented, the other two are not. This PR adds some documentation for those two forms of `expose`.
RFC: https://github.com/vuejs/rfcs/blob/master/active-rfcs/0042-expose-api.md
While working on this I noticed that `mount` returns the internal instance, not the exposed instance. This made it trickier to create simple, complete examples. I'd have preferred the API example to use `const vm = Vue.createApp(...).mount(...)` to grab the public instance, but that doesn't work. Instead I've used examples that show how to use `expose` but without explicitly showing how to use the exposed properties. I've opened a PR to change this in `vue-next`: …

Add the expose option and expose function

---

src/.vuepress/theme/styles/code.styl

Irregular border-radius  on the left side of code blocks
Added border top left and top right radii

fix irregular radius on code samples

---

src/.vuepress/components/community/themes/theme-data.js

Themes page misses new themes from PrimeVue.
Adds new Sakai (Free) and Atlantis themes from PrimeVue, moves Ultima before Diamond.

Add Sakai and Atlantis themes for PrimeVue

---

src/api/composition-api.md

I think that `Expose can only be called once` it better to go first in this statement.

docs: adjust some statement of composition-api.md

---

src/guide/installation.md

Missing closing parenthesis in the description of Vue ESM builds.
Add the closing parenthesis in the proper place.
N/A.

Add missing closing parenthesis to the Vue ESM builds' descriptions

---

src/guide/migration/custom-elements-interop.md

`app.config.isCustomElement` is deprecated and should be replaced with `app.config.compilerOptions.isCustomElement`
Change `app.config.isCustomElement` with `app.config.compilerOptions.isCustomElement` where referenced.

Update deprecated app.config.isCustomElement

---

src/guide/ssr/routing.md

I believe `entry-client.js` should be using `createSSRApp` instead of `createApp`. Both will work, but `createApp` will create an entirely new DOM in the browser, whereas `createSSRApp` will hydrate the existing DOM.
I've also made a few other minor corrections. I think they're self-explanatory but let me know if not.

Use createSSRApp instead of createApp

---

src/api/built-in-components.md

Fixes #1308.
I've attempted to address a few problems here:
1. The current entry doesn't render correctly because the `<component>` example isn't wrapped in backticks (see #1308).
2. The indentation is inconsistent with the rest of the page.
3. As far as I'm aware, using a VNode with `<component :is="vnode">` isn't a topic that is covered elsewhere. I've tried to introduce that concept first, before mentioning the caveat of requiring a `key`.

Expand the explanation about using VNodes with <component>

---

src/guide/forms.md

It seems Vue 3 can automatically convert a string value to a number from a number input, i.e. `<input type="number"`：
Vue Source Code：
```javascript
const castToNumber = number || (vnode.props && vnode.props.type === 'number');
```
The documentation about `.number` modifier does not reflect this.
I made some changes to the docs, to make it clearer about this situation. 
No.

Update description about .number modifier

---

src/api/sfc-script-setup.md

In the docs for `<script setup>`, we explain how to use components directly in the template without registering them, but we don't do the same for custom directives.
add a small section to the `<script setup>` docs after the component explanations.

fix: Explain usage of custom directives with script-setup

---

src/api/application-api.md

Editing a comment in application-api.md

---

src/.vuepress/theme/components/BannerTop.vue

This PR fixes the following issue: [1332](https://github.com/vuejs/docs/issues/1332), introduced in [this commit](https://github.com/vuejs/docs/pull/1330).
Before: when the "X" to close the banner was clicked the banner didn't close.
Now: when the "X" is clicked, the banner closes as expected.

Fix Black Friday banner close button

---

src/guide/installation.md

Rationale: newcomers prefer official documentation over GitHub project

docs(installation): link to cli.vuejs.org and vitejs.dev

---

package.json
pnpm-lock.yaml
src/about/team/Member.ts
src/about/team/TeamMember.vue
src/about/team/members-core.json

Add sponsor button to the team members.
Now we may add optional `sponsor` setting to team member JSON.
```json
[
{
"name": "Evan You",
"title": "Creator",
"company": "Vue.js",
"sponsor": "https://github.com/sponsors/yyx990803"
...
},
...
]
```

[next] feat: add sponsor button to team members settings

---

src/guide/component-custom-events.md
src/guide/migration/vnode-lifecycle-events.md
src/guide/render-function.md

`camelCase` should be better, and used lot more in other places of the document.

use camelCase

---

src/.vuepress/theme/layouts/Layout.vue

This PR removes the Vue School Black Friday banner from the top of v3.vuejs.org.
Please merge this PR after **Dec 3th 21 PM (Central European Time)**
The landing page will keep working after the promo ends, so the link (https://vueschool.io/sales/blackfriday?friend=vuejs) will still be valid.
Related to [PR 1330](https://github.com/vuejs/docs/pull/1330)

Remove Vue School's Black Friday banner

---

src/guide/migration/introduction.md

The Firefox-beta link leads to the v6.0.0-beta.2, and this updates it to v6.0.0-beta.20

Update the Firefox-beta link to lead to the latest beta release

---

src/.vitepress/config.js
src/.vitepress/theme/components/NewsLetter.vue
src/about/faq.md
src/guide/advanced/ways-of-using-vue.md
src/guide/advanced/web-components.md
src/guide/essentials/application.md
src/guide/essentials/class-and-style.md
src/guide/essentials/component-basics.md
src/guide/essentials/computed.md
src/guide/essentials/event-handling.md
src/guide/essentials/lifecycle.md
src/guide/essentials/list.md
src/guide/essentials/reactivity-fundamentals.md
src/guide/essentials/template-refs.md
src/guide/essentials/watchers.md
src/guide/introduction.md
src/guide/quick-start.md
src/guide/scaling-up/sfc.md
src/guide/scaling-up/tooling.md

These are all relatively minor tweaks to the pages that are currently ready for review in the new docs.
Some are more subjective than others. Even if the original wording was technically correct, I tried to reword anything that caused me to stumble on first reading.
Let me know if anything is unclear or contentious.

[next] tweaks and typos

---

src/guide/component-props.md

As noted in Issue 1362 https://github.com/vuejs/docs/issues/1362, there is a lack of clarity around mutating of objects and arrays being a bad practice.
Updated the docs to specifically warn against mutation of any prop in particular Arrays and Objects.

Update Prop Mutation Docs to be more clear around mutation

---

src/.vuepress/components/community/themes/theme-data.js

The descriptions of the community theme providers contained a few grammatical errors, namely:
**PrimeVue**
1. "look&feel" is incorrect since there should be spaces between the ampersand and the words.
**Flatlogic**
1. "Check the admin dashboards templates" does not use the conventional expression "check out". It also unnecessarily pluralises the word "dashboard."
2. "how real applications is built" has an inconsistency in that the noun "applications" is plural but the verb "is" is singular.
3. "Additionally these" should have a comma after the preposition "Additionally."
**PrimeVue**
1. "look & feel"
**Flatlogic**
1. "Check out the admin dashboard templates"
2. "how real applications are built"
3. "Additionally, these"

Fixed Grammatical Errors in Community Theme Descriptions

---

src/guide/component-attrs.md

Just try to make it clearer on what could be done after the inheritance is disabled.
Confusing sentence structure.
Rewrite to make it clearer.
I'm not a native English speaker, so I might be wrong.

Clerification on disabling attributes inheritance.

---

src/guide/installation.md

I figured out that there's no vite installation guide using PNPM
This PR consists of vite installation guide using PMPM

chore(vite installation guide): add installation guide using pnpm

---

src/guide/migration/migration-build.md

The current piece of advice for Nuxt.js users (https://v3.vuejs.org/guide/migration/migration-build.html#intended-use-cases) is currently: 
> Server-side rendering: [...] If you are using Nuxt.js, it is probably better to wait for Nuxt 3.
Nevertheless, Nuxt Bridge can be a great alternative, and a nice way to see how much of a codebase will have to be updated to run Nuxt 3.
There's also no link to Nuxt 3, and the fact that it is now in beta phase is not mentioned. I think it would be helpful to give more information about it right the docs.
- Add information + link to Nuxt Bridge "Getting Started" guide  
- Add link to Nuxt.js 3 "Getting Started" guide + a note to inform readers that it is currently in beta.
I guess someone should add a reminder to update the docs again when Nuxt.js 3 …

fix(compat): add a note about Nuxt Bridge for Nuxt.js users

---

src/examples/utils.ts

fix: remove `})` in example comment

---

src/guide/extras/composition-api-faq.md

Wrong word `algin` instead of `align`
Use correct word
This issue was probably not seen as algin is a correct word.

Fix typo on composition api faq

---

src/.vitepress/theme/components/PreferenceSwitch.vue

When scrolling down the left side panel, the preference switch panel would be hidden.
Maybe making it sticky would be more convenient for readers. @yyx990803 
https://user-images.githubusercontent.com/46062972/147519380-440e19cf-5052-4006-a097-6c91aa541619.mov

style: sticky preference switch panel

---

README.md

Using `git clone git@github.com...` notation may lead to an error `Permission denied (publickey) fatal: Could not read from remote repository.` if a user doesn't have a public SSH key stored in their github account. Using `git clone https://` is a 100% error-free solution (it doesn't require any SSH keys).
`git clone https://github.com/vuejs/docs.git`
https://stackoverflow.com/questions/21255438/git-permission-denied-publickey-fatal-could-not-read-from-remote-repository

Change git clone git@github.com to git clone https:// in README.md

---

src/guide/template-syntax.md

Since "mustaches" is a plural noun, the verb "to interpret" must also be conjugated in its plural form.
There is a missing period/full stop at the end of this sentence.
Since the pronunciation of SPA begins with a vowel sound, the article used should be "an", not "a".
1. Changed "interprets" to "interpret"
2. Added the period
3. Changed "a" to "an"

fix: grammatical errors in template-syntax.md

---

README.md
src/coc/index.md
src/community/join.md
src/cookbook/debugging-in-vscode.md
src/cookbook/editable-svg-icons.md
src/cookbook/index.md
src/guide/a11y-basics.md

Corrected Grammer, Punctuations and Typos

Updated: Typos in a11y-basics file

---

src/guide/custom-directive.md

the mounted of the custom directive is earlier than the onMounted of the component,but `called when the bound element's parent component is mounted`  in docs
Modify the documentation description of the custom directive
eg:`called before the bound element's parent component is mounted`
[The issue of pull request](https://github.com/vuejs/docs/issues/1428)

Modify the documentation description of the custom directive

---

src/guide/components/async.md
src/guide/components/attrs.md
src/guide/components/events.md
src/guide/components/props.md
src/guide/components/provide-inject.md
src/guide/components/registration.md
src/guide/components/slots.md
src/guide/reusability/composables.md
src/guide/reusability/custom-directives.md

Following on from #1366, these are relatively minor tweaks to the updated guides to **Components In-Depth** and **Reusability** in the new docs.
Some are more subjective than others. Even if the original wording was technically correct, I tried to reword anything that caused me to stumble on first reading.
Let me know if anything is unclear or contentious.

[next] tweaks and typos - components & reusability

---

src/tutorial/src/step-8/App/template.html
src/tutorial/src/step-9/description.md

There are a few little fixes included in this PR:
- fixed the lifecycle hooks description on Lesson 9 for Composition API (it wasn't rendered due to the closing tag absence)
- fixed the `:key` for todo-list (it's `todo.id` in the description but `todo.text` in the code
- fixed the lesson 8 code to work for HTML: for some reason, self-closing `input` tag generated closing `</ul>` so there was an error thrown about `todo.done`:

Minor fixes to tutorial

---

src/guide/built-ins/keep-alive-demos/SwitchComponent.vue

The first example on the page about `KeepAlive` is supposed to show what happens without using `KeepAlive`. However, it is currently using `KeepAlive`, so the state doesn't get reset. The `v-if`/`v-else` logic in the template of `SwitchComponent` is back-to-front.
Flipping the logic fixes the first example but breaks the second example.
The first example uses:
```html
<SwitchComponent />
```
The second example is similar, but with `KeepAlive` enabled:
```html
<SwitchComponent use-KeepAlive />
```
For this to work, it needs the `useKeepAlive` prop to be defined as a `Boolean`, otherwise it ends up with a value of `""`. Currently this is not the case.

[next] fix keep-alive examples

---

.vitepress/theme/styles/badges.css
src/api/built-in-directives.md
src/api/composition-api-lifecycle.md
src/api/options-lifecycle.md

Following on from e6512dc7d52c1d00adca715e371c123f0ef0b46a, this PR moves the text for 3 badges into CSS `content` .
Currently the links from https://staging.vuejs.org/api/ are broken for `v-memo`, `onServerPrefetch()` and `serverPrefetch` due to the badges being included in the hash.

Fix API links for headings with badges

---

src/guide/best-practices/accessibility.md

People might not know what landmark is in the accessibility doc. So I added a MDN link for it.
Added the MDN link https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/landmark_role
No

Add a MDN link for landmark

---

src/api/utility-types.md

When using typescript Volar/vue-tsc would complain about any custom 
CSS property used in a style attribute:
```html
<div :style="{ '--color': red }">
```
Document how to augment the CSSProperties interface to allow specific properties or just any custom property.

feat(api/typescript): Document use of CSSProperties type.

---

src/examples/src/circle-drawer/App/template.html

Inconsistent word "radius" vs "diameter" in docs - examples - circle.
Use "radius".
The program source seems to handle the interfacing value as radius.
Diameter seems to be generated within the internal logic and it is not obvious to the user.

fix: Inconsistent word "radius" vs "diameter" in doc

---

src/about/team/members-partner.json

In docs - about, a partner member who is located in Brazil and working for institutions in Brazil is marked as "Polish" speaker.
Most probably this could be a simple mistake in edit and it should be meant as "Portuguese".
replace Polish -> Portuguese
I've asked this member directly via email and awaiting for reply.

correct spoken language

---

src/guide/best-practices/performance.md
src/guide/built-ins/keep-alive.md
src/guide/built-ins/suspense.md
src/guide/built-ins/teleport.md
src/guide/built-ins/transition-group.md
src/guide/built-ins/transition.md
src/guide/extras/composition-api-faq.md
src/guide/extras/reactivity-in-depth.md
src/guide/extras/reactivity-transform.md
src/guide/extras/render-function.md
src/guide/extras/rendering-mechanism.md
src/guide/scaling-up/ssr.md
src/guide/scaling-up/state-management.md
src/guide/scaling-up/testing.md
src/guide/typescript/composition-api.md
src/guide/typescript/options-api.md
src/guide/typescript/overview.md

Following on from #1366 and #1432, I've now finished going through the guides and these are relatively minor tweaks to the remaining pages.
Some are more subjective than others. Even if the original wording was technically correct, I tried to reword anything that caused me to stumble on first reading.
Let me know if anything is unclear or contentious.

Tweak wording, correct typos and adjust grammar

---

src/api/sfc-script-setup.md

Latest vue / volar / vue-tsc complains when exporting additional types from SFCs (even though it worked previously). It seems this may be the intended behaviour (please confirm!) but was a bit unclear in these docs.
This change specifically calls out exporting types and provides a short example.

add clarification about type exports in SFCs

---

src/api/sfc-css-features.md

Typo in the phrase "for mode details" (mode => more)
Change "mode" to "more"

docs: fix typo

---

src/examples/src/flight-booker/App/composition.js
src/examples/src/flight-booker/App/options.js
src/examples/src/flight-booker/App/template.html

In example - flight,
1. condition for showing the warning message was logically flipped.
2. date comparison makes errors around end of month. Note that new Date() is zero-based.
1. Add `!`
2. Use 0-11 for month value
I also added "value" for option, for ease with translation projects.

Wrong flight logic

---

.vitepress/theme/components/Home.vue

User reported that the Special Sponsors link for hbuilderx is broken. This fixes that.

fix: special sponsors link on homepage is broken

---

src/guide/extras/web-components.md

There was a typo in the docs.
Fixed by adding "e"

Fixed typo

---

src/guide/scaling-up/testing.md

I've been starting a new project and follow this docs. Here's some suggestion:
Since https://github.com/vitest-dev/vitest/pull/565, `global` is deprecated. I propose a section to add a config for TypeScript.

Use `globals` setting in testing setup

---

src/guide/scaling-up/tooling.md

The Devtools for Chrome are no longer in beta and can be accessed via the main channel.
I've also updated the link for the Electron app to a URL suggested by @Akryum.

Update Devtools links

---

src/guide/scaling-up/ssr.md

Right now, if you click on the Stackblitz links, they open perfectly. But if you try to edit and save, it freezes up for a few seconds, then reloads, which isn't the best possible experience 😁
Replace `edit` in URLs with `fork`. That way, it will fork by default, overall giving a slightly better experience

docs: Fork in stackblitz URL

---

src/guide/typescript/options-api.md

we have some problems while translating this article to other language. It is, if a word (like 'props') means the `props` option in code, then it should have a code style, so we can keep the format of it (like 'props' with 's'). otherwise, by our translating guideline, we will omit the 's', so 'props' become 'prop'.
Anyway, it's just my reason to make this change. If this looks not good, please ignore it. And we will figure out a better solution.
ref https://github.com/vuejs-translations/docs-zh-cn/pull/11

add codestyle to some words

---

src/guide/essentials/application.md
src/guide/essentials/component-basics.md
src/guide/essentials/forms.md
src/guide/essentials/lifecycle.md
src/guide/essentials/list.md
src/guide/essentials/reactivity-fundamentals.md
src/guide/essentials/template-syntax.md

I've gone through the guides in Essentials again, reviewing new content that has been added since #1366.
These are mostly spelling corrections, though for a couple of sentences I've made some other tweaks to try to make them scan better.

Minor tweaks to the guides in Essentials

---

src/guide/extras/demos/SpreadSheet.vue

Similar to #1517, but for the other spreadsheet example.
Fixed preview: https://deploy-preview-1521--vuejs.netlify.app/guide/extras/reactivity-in-depth.html#what-is-reactivity

Remove scrollbars from the spreadsheet cells

---

README.md

This PR removes the WIP notice from the top of README.md. I think we're past the stage of asking people not to submit PRs.

Remove WIP notice

---

src/api/utility-types.md

When using SFC it's often not necessary to do type augmentation if v-bind in CSS is used.
Adding custom properties in a template causes a type error because custom properties are not accounted for in `CSSProperties`. Searching how to fix that error frequently leads to the docs on [CSSProperties](https://vuejs.org/api/utility-types.html#cssproperties) and how to augment the type.
Using `v-bind` in CSS is often the better solution or is at least relevant so linking to that documentation will help convey another solution to fixing the type error.

Add info about v-bind in CSS under CSSProperties

---

src/guide/scaling-up/TestingApiSwitcher.vue
src/guide/scaling-up/testing.md

This is a pretty large change for the testing guide. Here's a list of proposed changes in order of appearance.
- Adds "Why Test?" intro section.
- Adds "Start Testing Early!" tip to "Why Test?" intro.
- Removes "testing concerns" in favor of describing specific issues that each testing type protects against. See the Unit, Component, and E2E sections.
- Adds Unit Testing code example for testing an `increment` function.
- Removes all mentions of "Visual testing" because that's a different testing type w/ a specific meaning (e.g. Percy or Happo snapshots).
- Establishes "Testing Types" terminology throughout the doc.
- Adds section about avoiding mocks in Component Testing section.
- Swaps "Interaction concern" to "Behavioral logic".
- Adds Component Testing example for a Stepper component. …

docs: adding information to testing docs

---

src/guide/scaling-up/ssr.md

chore: fix typos

---

src/api/options-composition.md

Found a typo 
https://github.com/vuejs/docs/blob/8dda0d8a04e8799821aa6d330a6b8199881b6abd/src/api/options-composition.md?plain=1#L89
I think `is` should be replaced with `if`

fixed a typo

---

src/api/built-in-special-attributes.md
src/api/sfc-spec.md
src/ecosystem/themes/themes.json
src/guide/essentials/forms.md
src/guide/extras/web-components.md
src/guide/scaling-up/sfc.md
src/guide/scaling-up/tooling.md
src/guide/typescript/overview.md
src/style-guide/rules-use-with-caution.md

These changes are based on commits that were merged into `master` after the `main` branch was created. They aren't necessarily identical to the original commits, but they attempt to solve the same problems in a similar way.
There are more commits that need migrating, but the ones included here were small enough to batch them together.
For reference, this PR attempts to recreate:
* #1192
* #1207
* #1238
* #1283
* #1285
* #1299
* #1347
* #1376
* #1387
* #1454

Migrate changes from master to main

---

src/api/options-state.md

Simple typo 
explicit declared -> explicitly declared

options-state.md typo

---

src/tutorial/src/step-1/description.md

Simple typo on the first page of the tutorial: https://vuejs.org/tutorial/#step-1
Change "front development" to "front-end development"

Fixed typo on page 1 of tutorial

---

src/examples/src/cells/App/template.html

the `v-for` attribute value is wrong at src/examples/src/cells/App/template.html
```html
<td v-for="c, j in cols">
```
replaced with
```html
<td v-for="(c, j) in cols">
```

fix the `v-for` attribute value

---

src/api/sfc-script-setup.md

This PR adds a section to the API docs for `<script setup>` explaining how to use local custom directives.
It is based on #1319, which was lost following the move from `master` to `main`.

Add a section about custom directives with script setup

---

src/guide/scaling-up/testing.md

Typo in phrase `because they doopen a browser`
Change `doopen` to `do open`

chore: fix typo in testing.md

---

src/guide/best-practices/accessibility.md
src/guide/extras/demos/SpreadSheet.vue
src/guide/extras/demos/SpreadSheetCell.vue

SpreadSheet dark mode text cannot be displayed
Control the change of text and background color through CSS variable

fix: SpreadSheet dark mode display (#1533) & add placeholder example (vuejs#1532)

---

src/api/options-rendering.md

This change came out a conversation on Vue Land. The key change is providing more information about which builds include the template compiler. The link to `dist file guide` is the same link that's used in https://vuejs.org/guide/best-practices/production-deployment.html#without-build-tools.
I also changed the bit about the mounted element. That's only relevant for the root component, so I moved that to the end and adjusted the wording accordingly.

Update the API entry for the template option

---

src/api/built-in-directives.md

We describe the vbind.prop shorthand, but not the v-bind.attr shorthand
Add missing API documentation

Document v-bind.attr shorthand in API section.

---

src/api/application.md

href to `performance.mark` docs was empty
Updated to mozilla docs

Update href of perfomance.mark

---

.vitepress/theme/components/Home.vue
.vitepress/theme/components/VueMasteryModal.vue
.vitepress/theme/styles/index.css
.vitepress/theme/styles/vue-mastery.css
src/guide/introduction.md

- Add "Why Vue?" video to homepage
- Add button to homepage
- Change getting started button colour
- Add video modal
- Add graphical link

Vuemastery video modal and graphical link

---

src/api/options-rendering.md

In #1570 I updated the API entry for the `template` option. I now realise that I got the part about which files include the compiler back-to-front. The word `runtime` signifies 'runtime only', rather than 'runtime compiler'.

Builds named 'runtime' don't include the compiler

---

.vitepress/theme/styles/inline-demo.css

This is similar to what was attempted in #1453, but without the impact on other elements.
In some browser/OS combinations, the `<select>` example [here](https://vuejs.org/guide/essentials/forms.html#select) looks like this:
This PR attempts to introduce a darker background:

Dark-mode styling for select and option elements
