- src/guide/composition-api-lifecycle-hooks.md
> chore: typo fix

- src/.vuepress/components/community/team/vuer-profile.vue
- src/.vuepress/styles/index.styl
- src/style-guide/README.md
> fix: font-family name error #209

- src/guide/migration/functional-components.md
> fix(migration/functional-component): typo

- src/guide/reactivity.md
> fix(reactivity): typo

- src/guide/reactivity-fundamentals.md
> Fix small typo

- src/guide/composition-api-introduction.md
> Add space to align properties

- src/guide/plugins.md
Update the `plugins` section to a step-by-step guide approach to writing plugins, and added some tips and extra information for `using`
> Update plugins section to guide style with example

- src/api/directives.md
- src/api/refs-api.md
> Fix anchors which refers to localhost:8080 domain

- src/.vuepress/components/community/team/members.js
- src/guide/introduction.md
- src/guide/writing-guide.md
This PR covers two things covered in docs meetings:
- Removing click to load state for the first introduction codepen embed
- Capturing in the writing guide the info, tip, warning styles and the proper use of them
Misc:
- My bio update since promotion
> Small edits from docs meetings for release (details below)

- src/guide/render-function.md
> Fix missing `h` character

- src/guide/installation.md
Added Vite to the installation guide, and updated devtools with links and clearer information on requirements. 
Response to Issue #230
> add vite and update devtools

- src/.vuepress/components/BetaBanner.vue
- src/.vuepress/theme/components/Home.vue
- src/.vuepress/theme/styles/index.styl
- src/.vuepress/theme/styles/wrapper.styl
As discussed, this PR adds the ability for the user to discard the "docs current in beta" banner. I've also played a bit with the HTML to make the message fit on devices with smaller screens.
> chore: allow discarding beta banner

- src/.vuepress/public/images/css-vs-js-ease.svg
- src/guide/transitions-enterleave.md
- src/guide/transitions-overview.md
Fixes some todos on the overview, and works out text for more sections.
> Next iteration Transitions

- src/guide/instance.md
This is the first mention of Reactivity in Vue Guide, so it might be worthwhile to link to the explanation page.
> Link to Vue reactivity on Instance page

- src/.vuepress/theme/styles/code.styl
This PR fixes the line highlighting, seen on the Documentation Style Guide page
> Fix highlight color

- src/guide/transitions-enterleave.md
Fixes all the todos and adds in a new pen that explains it for more complex use cases.
> Redo the Transition Modes Section

- src/guide/component-basics.md
- src/guide/component-props.md
- src/guide/introduction.md
This PR makes some opinionated choices, so feel free to close it. The main change I thought was meaningful is to let people know upfront that we typically use SFC where we use a template string. I moved the two way binding up because I think it's compelling, but not attached to it.
> Clarifying SFC and other Simplifications

- src/style-guide/README.md
I must be half sleeping when I did this migration :(
> fix: remove trailing :::

- src/guide/introduction.md
Updates the compatibility phrasing for IE in response to Issue #257
> update compatibility phrasing for IE

- src/guide/migration/global-api.md
> Fix Link in Docs

- netlify.toml
To test redirects in deploy preview, visit https://deploy-preview-287--vue-docs-next-preview.netlify.app/guide/
Closes #238
> feature (#238): add redirect for /guide/ path for easy url sharing

- src/.vuepress/components/community/team/utils.js
- src/.vuepress/markdown/highlight.js
- src/api/built-in-components.md
- src/api/options-data.md
- src/guide/composition-api-provide-inject.md
- src/guide/migration/attribute-coercion.md
- src/guide/migration/keycode-modifiers.md
- src/guide/transitions-enterleave.md
> chore: fix typos

- src/api/application-api.md
> Fix an outdated link to Application Config

- src/guide/computed.md
> fix:remove extra brackets

- src/api/refs-api.md
> fix: here should have property .value that points to the inner value

- src/api/composition-api.md
Fixed link that was causing a 404
> fix: broken link in api/composition-api

- src/guide/component-custom-events.md
> vmodel modifiers clarify example and diff 2.x v 3.x

- src/guide/composition-api-lifecycle-hooks.md
> Add missing quote to hooks example

- src/api/instance-properties.md
fixes a broken url resulting in a 404
> fix: broken url @ api/instance-properties

- .github/workflows/pr.yaml
- scripts/tag-alert-blocks.js
- src/test.md
Fixes #102 
/cc @bencodezen can you decide what label we want to use?
> [WIP] tag PRs using alert blocks

- src/guide/typescript-support.md
A wrong method name in annotation
> A wrong method name in annotation

- src/guide/installation.md
> fix: updated version

- src/guide/component-basics.md
> fixed link (#389)

- src/guide/component-slots.md
CC @bencodezen 
I am very happy can do tiny contribution here :)
Please let me know things I can improve next time.
> fixing typo in slot prop fallback

- src/guide/composition-api-introduction.md
> Fixing typo in Composition API intro example

- src/guide/transitions-list.md
Working pen: https://codepen.io/immarina/pen/OJMKewE
Clears out a `TODO`
> feat: update example to vue 3

- src/guide/component-dynamic-async.md
> Fix invalid link for "Component Basics"

- src/guide/composition-api-provide-inject.md
> fix typo in guide/composition-api-provide-inject

- src/guide/a11y-basics.md
A btw PR during translating this page into Chinese. Thanks.
> Typos on a11y-basics.md

- src/api/computed-watch-api.md
> fix: watchEffect api links

- src/guide/composition-api-introduction.md
> fixed: remove some  unused reference in example.

- src/guide/migration/slots-unification.md
see https://github.com/vuejs/vue-next/issues/2045
Since this is a small change, I'm not sure if it's more clear to suggest this in a PR than an issue
> slots migration guide, mention change to function more prominently

- src/guide/render-function.md
- src/guide/transitions-enterleave.md
fix the hyperlink of `this.$slots`
fix the hyperlink of 'dynamic component'
> fix: render-function, transitions-enterleave.md

- src/guide/typescript-support.md
> docs: set jsx as `preserve` in tsconfig.json

- src/guide/render-function.md
> fix: normalize the event handler's name in the render function

- .github/pull_request_template.md
- src/.vuepress/components/AppBanner.vue
- src/.vuepress/theme/layouts/Layout.vue
- src/guide/contributing/translations.md
> chore: remove beta banner from docs

- src/.vuepress/components/common/vuemastery-video-modal.vue
Updated the homepage "Why Vue" video to the new Vue 3 version.
> Updated homepage video to Vue 3 version

- src/.vuepress/config.js
- src/guide/migration/introduction.md
- src/guide/migration/v-bind.md
- src/guide/migration/v-if-v-for.md
- src/guide/migration/watch.md
> docs: update menu and migration guides

- src/guide/migration/v-bind.md
The sentence seemed incomplete and didn't give a proper solution to the migration
I have completed the sentence according to my knowledge. Let me know if something needs to change
> Update v-bind.md to complete the incomplete sentence

- src/guide/migration/introduction.md
> docs: add redirect for new users

- src/.vuepress/config.js
- src/guide/mobile.md
This was created as a way to allow users to discover great solutions being provided and actively supported by the community. Let me know what you think!
@mhartington @rigor789 Please feel free to let me know if you would like to add or change anything about your project's description and/or resources.
Netlify Preview: https://5f4d0ec6a42f5400070c3564--vue-docs-next-preview.netlify.app/guide/mobile.html
Closes #386
> docs (#386): add mobile section

- src/guide/composition-api-introduction.md
Quite minor grammar change ("several hundreds of" -> "several hundred") but for me it really took the flow away from my reading of the article.
Looking this up it appears the consensous is the latter is better hence the PR!
There was a wording which for me, and a straw poll of 1 more for my partner, really broke my flow of reading the article.
Slight update to the grammar
First Vue PR here. Apologies if I've done it wrong - I saw a style guide but not a PR guide.
> Grammar change ("several hundred")

- src/guide/state-management.md
The first comma in the senctence seems oddly placed. This makes the sentence hard to understand at first. For me at least.
I think that first comma should not be between *store* and *but* but between *convention* and *where*.
This comma even got itself some ~research~ googling: 
[Comma Rules: A Quick Guide | Grammarly](https://www.grammarly.com/blog/comma/)
* Section: Commas with Interrupters or Parenthetical Elements
* Section: Comma Before But
Cheers!
> fix, minor grammar. some comma

- src/guide/transitions-enterleave.md
This is left over from #581. The final example needs a CodePen.
Added the CodePen. This should be the same change requested by @NataliaTepluhina.
> Add the CodePen for the final example in transitions-enterleave.md

- src/guide/component-basics.md
Consistent v-on in example & text
> docs: fix example in component-basics.md

- src/guide/component-slots.md
Profile was in old version, now all about todo's / fix another example
> docs: fix example in component-slots.md

- src/guide/transitions-overview.md
> docs: fix typo in transitions-overview.md

- src/guide/installation.md
Changed 'lighting' to 'lightning'
> fix: typo in `migration/installation.md`

- src/.vuepress/public/images/css-vs-js-ease.svg
#564 The text crawls over the text
Offset text  coordinates
> Fix broken text css-vs-js-ease.svg (#564)

- src/guide/reactivity.md
> fix: delete nonexistent output

- src/.vuepress/theme/components/Newsletter.vue
https://www.w3.org/TR/CSS2/visudet.html#min-max-heights
> Fix newsletter button on safari

- src/guide/migration/introduction.md
It is not as clear what dependencies have successfully migrated to Vue 3, so this PR solves this by pointing towards a maintained issue in `awesome-vue`.
This will allow members to better track Vue 3 compatibility with other libraries that is sourced through community efforts.
> docs: add reference to table to track vue 3 compat libraries

- src/.vuepress/components/community/team/members.js
> docs(team): add antfu

- src/api/composition-api.md
Missing overload of `inject`
adding the overload definition
> feat(composition-api): add overload for inject factory

- src/guide/migration/custom-elements-interop.md
Header level is not matched with other files.
Changed the heading level of `Overview` from h1 to h2
> chore: fix heading level

- src/README.md
> Update the GitHub repo link to `vue-next`

- src/guide/installation.md
> update jsdelivr link

- src/guide/component-provide-inject.md
> docs:  fix typo in component-provide-inject.md

- src/api/options-dom.md
> Fix tip colons

- src/api/built-in-components.md
> docs: fix code highlight in built-in-components.md

- src/.vuepress/config.js
Vuejs 3.0 Chinese docs is ready.
> feat: add translation links

- src/guide/transitions-enterleave.md
Transitions list now in separate chapter
> docs: Update transitions-enterleave.md

- src/.vuepress/config.js
> feature: add blog link

- src/guide/list.md
If todo-items are objects here — change to showing some prop from them
> docs: Fix examples in list.md

- src/guide/optimizations.md
inconsistent terminology
"JS" -> "JavaScript"
> docs: update src/guide/optimizations.md

- src/.vuepress/config.js
> docs: update vue test utils link

- src/guide/composition-api-setup.md
Tabs were used in the sample.
I've unified them into a 2 spaces.
https://v3.vuejs.org/guide/composition-api-setup.html#props:~:text=function%3A-,%2F%2F%20MyBook.vue,%7D
> fix instead tab to 2 spaces

- src/guide/a11y-basics.md
The word "to" is missing in this sentence.
Add the missing word "to"
> Add missing word

- src/api/options-composition.md
> add word 'about'

- src/api/global-api.md
https://github.com/vuejs/docs-next-zh-cn/pull/417
> fix `resolveComponent ` return type error

- src/api/instance-methods.md
> docs: Update instance-methods.md

- src/api/options-lifecycle-hooks.md
Missed space between sentences
> docs: Update options-lifecycle-hooks.md

- src/.vuepress/config.js
> add korean translation site link

- src/api/options-data.md
We removed watching a nested property with a keypath from API. I returned it back :)
> Added watching a nested property to API reference

- src/.vuepress/config.js
> chore: fix a menu link for 'Vue Test Utils'

- src/guide/installation.md
Repetition of conjunction, that.
Remove irrelevant 'that'
Change 'vite' to 'Vite'
> fix grammatical error in installation.md

- src/api/instance-methods.md
> fix error about deep option of watch in instance-methods.md

- src/guide/migration/introduction.md
Closes #1001.
Update the link for `<script setup>` to the latest RFC.
> Update link to `<script setup>` RFC

- src/guide/introduction.md
> fix variable name in code.

- src/guide/typescript-support.md
> Added template refs typing instruction

- src/api/global-api.md
REF: https://github.com/vuejs/docs-next/pull/1008
> Added missed functional component in global-api.md

- src/guide/migration/custom-directives.md
> Add created hook to custom directives code example

- src/guide/migration/render-function-api.md
> Fix typo in render-function-api.md

- src/guide/migration/data-option.md
> fix: json format quotation

- src/guide/migration/global-api.md
Updated the link and realigned the table markdown.
> Update link in global-api.md

- src/guide/migration/attribute-coercion.md
Removed redundant "instead", changed confusing `/` to `-`.
> docs: improved `attribute-coercion.md`

- src/guide/testing.md
I opened a PR in the v2 docs and saw that v3 was separate. Opened this PR because of that.
> docs: typo and brevity

- package.json
- yarn.lock
axios was added in #31, but is now unused as code examples were moved to CodePen in #57.
Let's remove axios.
> chore: remove axios

- src/.vuepress/config.js
> fix: update vue-devtools url

- src/.vuepress/components/community/themes/theme-data.js
PrimeVue themes aren't up to date.
Fixed all information.
https://github.com/vuejs/vuejs.org/pull/2819 is also waiting for approval for old doc.
> Update PrimeVue themes

- src/guide/migration/introduction.md
> fix: link error

- src/guide/migration/introduction.md
The RFC has been merged, changing the URL.
Closes #1140.
> Update link for 'SFC State-driven CSS Variables' RFC

- src/api/global-api.md
Just a missing comma
https://github.com/vuejs/docs-next-zh-cn/issues/608
> Added the missing JS comma at the end of a line

- src/guide/web-components.md
Correct typo
Missing e
Added an e
> Fix typo in web-components.md

- src/guide/plugins.md
> no filters in vue 3

- src/.vuepress/config.js
see #1168 
if not acceptable, pls close it.
> feat: enable editLinks (close #1168)

- src/.vuepress/theme/components/PageEdit.vue
> fix: add `<br/>` to edit link, make it looks better.

- src/guide/web-components.md
Close https://github.com/vuejs/docs/issues/1165
> Fix custom elements registration method

- src/guide/component-attrs.md
`data-status` is a attribute rather than property. It should be consistent with the description on line 100:`With this new configuration, our `data-status` attribute will be applied to our `input` element!`
> Update component-attrs.md 

- src/api/sfc-style.md
> docs: fix typo

- src/api/refs-api.md
Reactive is a `function` more than `method`
> Change reactive `method` to  reactive `function`

- src/guide/reactivity-fundamentals.md
It caused me a little trouble,  When I read that sentence
> It could be a mistake

- src/guide/migration/watch.md
rest of this article used `deep` **option**. just for consistence.
> docs: Update watch.md

- src/guide/component-custom-events.md
redundant (duplicate) code example
remove redundant (duplicate) code example
> remove redundant (duplicate) code example

- src/guide/migration/introduction.md
> docs: Change `is` prop to `is` attribute

- src/api/special-attributes.md
> remove unnecessary space

- src/.vitepress/config.js
require https://github.com/vuejs/theme/pull/33
Adds configuration for global footer.
> [next] feat: configure global footer

- src/.vitepress/theme/components/NewsletterSection.vue
- src/.vitepress/theme/index.ts
require https://github.com/vuejs/theme/pull/33
Adds newsletter section. Best to merge [Global Footer](https://github.com/vuejs/docs/pull/1245) PR first.
> [next] feat: add newsletter section

- src/guide/web-components.md
typo in preserved
updated spelling
> docs: fixed typo of preserved

- src/.vuepress/components/community/team/partners.js
No problem. Just updating my description and links to Quasar.
> chore: Update partners on myself

- src/examples/ExampleRepl.vue
- src/examples/utils.ts
- src/tutorial/TutorialRepl.vue
- src/tutorial/data.json
@yyx990803 as we discussed, this PR enables dynamic content for tutorial steps
> Abstracted example-generating utilities and made tutorial content dynamic

- src/api/special-attributes.md
The word 'diffing' is used without clarify its meaning
I've enclosed a word intended to clarify meaning of diff.
n/a
> enclosed a word intended to clarify meaning of diff

- src/api/directives.md
The example in the document is not very good
Changing the example 
none
> A better example for v-html

- src/api/directives.md
> Fix bug in the rendering of the v-html example

- src/guide/composition-api-introduction.md
Readability issue in 'Why composition api?' doc.
Added comma.
> Added comma for better readability.

- src/guide/essentials/list.md
There was a simple typo
Fix said typo
> Fix a typo

- src/guide/component-slots.md
Update "Add Todo" to "Add todo" so it matches what is in the code.
> Very minor update on letter casing

- src/about/team/members-core.json
> docs(team): update kazupon profile

- src/about/team/members-core.json
> docs(team): update ota-meshi profile

- src/about/team/members-partner.json
Just updating outdated links for Quasar.
> chore: Update members-partner.json on myself

- src/guide/essentials/template-syntax.md
There was an argument to rename. Copy and paste from the previous example
```diff
-<a @click="url"> ... </a>
+<a @click="doSomething"> ... </a>
```
> Docs : Typo

- src/guide/extras/web-components.md
Minor markdown formatting error
Fixed with working link
> Fix: broken link in web-components.md

- src/guide/scaling-up/testing.md
Change import source from'@vue/testing-library' to '@testing-library/vue''
`import { render } from '@vue/testing-library'`
`import { render } from '@testing-library/vue'`
> Update testing example

- src/tutorial/src/step-7/_hint/App/composition.js
- src/tutorial/src/step-7/_hint/App/options.js
I was doing the tutorial and every time I made my solution, I checked with the one that was delivered, in step 7 I realized that when adding a new item to the array todos, the id was not added
I just fixed this by adding the id for each response
> Add the id in the answers from step 7 of the tutorial

- src/guide/essentials/computed.md
extra semicolons
remove extra semicolons
> docs: fix syntax format

- src/guide/essentials/application.md
> chore: fix typo at application.md

- src/guide/extras/rendering-mechanism.md
Binding description missing
supplementary description
> fix: description supplement

- package.json
> add preinstall hook to allow only `pnpm`

- .vitepress/theme/components/VueJobs.vue
- .vitepress/theme/index.ts
- src/sponsor/index.md
As per the discussion with @yyx990803, adding the jobs widget to the docs aside area.
> Add vue.js jobs widget

- .vitepress/theme/components/PreferenceSwitch.vue
Details in #1491 
Fix the width.
> fix: API preferences link is getting squished

- src/api/application.md
> adjustment sequence be consistent with the interface

- src/about/team/members-core.json
> docs(team): add pikax

- .vitepress/theme/components/VueJobs.vue
AB Testing the job listing with company avatar and removing extra details.
> Add company avatar to job postings

- src/guide/components/slots.md
There seems to be a "/" missing in the closing header tag in the code example, so I added one
> Add missing slash in closing header tag

- src/guide/scaling-up/sfc.md
> fix : ensuring correctness

- src/api/composition-api-lifecycle.md
Error on exemple import (unUnmounted instead of onUnmounted)
Replace unUnmounted by onUnmounted
> Fix unUnmounted to onUnmounted

- src/guide/components/slots.md
A confusion was made between header and footer
> chore(slots): fix typo

- src/style-guide/rules-strongly-recommended.md
Vuex is the old store.
Mention Pinia instead.
Hyperlink it.
> Change Vuex to Pinia and link it

- src/api/composition-api-lifecycle.md
> Fix onBeforeUnmounted to onBeforeUnmount

- src/guide/reusability/custom-directives.md
changed variable name, it sounds like my directory, while it's my directive actually
> changed variable name

- .github/contributing/writing-guide.md
The original link does not exist anymore.
> Fix a link in writing-guide.md

- src/guide/built-ins/transition.md
Typo. **by** should be **be**.
Fix the typo.
None.
> Fixes typo

- src/guide/scaling-up/ssr.md
- src/guide/typescript/composition-api.md
Add 'Using <script setup>' as H3，Corresponding to the h3 below --Without <script setup>
> fix: add h3 in src/guide/typescript/composition-api.md

- src/api/composition-api-setup.md
this's value in setup is undefined
> this's value in setup is undefined

- src/api/render-function.md
> docs: src/api/render-function.md

- src/api/application.md
refine the `application` documentation link
> docs: refine the `application` documentation link

- .vitepress/config.ts
Currently, we're lacking links to core libraries (we used to have them on v2 docs)
Close #1663, #1568
> Added links to Vue Router and Pinia

- src/guide/essentials/template-syntax.md
falsy values docs link is missed.
added falsy value mdn docs link to `falsy values` text.
> Added falsy values mdn docs link

- src/public/_redirects
> [Hold] add perma redirects for v2 urls

- src/api/application.md
This PR updates 3 paragraphs from the Application API page that had grammatical problems.
> Grammar tweaks to application.md

- src/guide/scaling-up/testing.md
I found that forgot to add closing brackets in the document of scaling > testing.
and i fixed it in this pr.
> chore: add closing parentheses

- src/guide/components/slots.md
I think the author meant to say either "and passes props as arguments" or "passing props as arguments"
> Fix grammar

- src/about/team/members-partner.json
Updating outdated information about my role and company, and my current city.
Also taking the opportunity the update the vuejs-br community link to the more generic organization link, instead of just a repo link. Finally, adding my Linkedin since it's nowadays the best place to reach me out by text messages.
Just merge this. 😄
N/A.
> Chore: Update about myself in Members Partners page

- src/guide/essentials/event-handling.md
There's a broken URI fragment in the docs.
Update the link.
> Fix a link

- src/guide/typescript/options-api.md
I found the prose-only description a bit confusing and got stuck for a solid ten minutes trying to figure it out.
I've added example code of what does and doesn't work, since I find that more immediately understandable.
> Add more specific example code to Type Augmentation docs.

- src/about/team/members-partner.json
Daniel has done incredible work in the community and he has been nominated by multiple team members to be a community partner.
Adding Daniel as a community partner!
Do not merge until we get @danielroe's approval on the information in the profile.
> docs: add Daniel Roe as a community partner

- src/guide/extras/web-components.md
The used link redirects users to a 404 page. I have updated the URL to the correct page.
Previous link: [https://web.dev/index.md/](https://web.dev/index.md/)
New Link: [https://web.dev/custom-elements-best-practices/](https://web.dev/custom-elements-best-practices/)
> Update the recommended best practices url

- src/guide/scaling-up/sfc.md
If you have any questions, please ask.
> Improve spelling

- src/guide/essentials/computed.md
Beginners or someone who is not familiar with the concept should be able to notice the critical points.
Add the highlighted information in the best practices section on the computed page.
> highlighted the important point in computed properties

- src/api/application.md
Some of the attributes are missing
> perfect: Add missing fields

- src/guide/introduction.md
I removed a hyphen from "Server-Side Rendering" and hyphens from "Static Site Generation" to be consistent with other vuejs.org pages
> Fix minor language typos/improve language

- src/api/sfc-script-setup.md
> Fix typo - hyphenate Single-File Component

- src/guide/essentials/forms.md
As mentioned in #1813
Change `use an` to `use your own`.
--
> rephrase confusing notes for IME

- src/tutorial/src/step-3/description.md
The beginning of the sentence is not capitalized.
Change the beginning of the sentence to uppercase.
> Change the beginning of the sentence to uppercase

- src/guide/essentials/watchers.md
Updated: _With Options API_ → _With **the** Options API_
> Fixed a grammar mistake

- src/guide/components/props.md
...there isn't as much practical benefits for...
...there isn't as much practical benefit in...
> fix: Minor grammatical error in props.md

- src/guide/reusability/composables.md
English-language pedants, like me, may find some grammatical errors and peculiar turns of phrase to detract from the meaning that is being conveyed.
Just tell people like me to chill the **** out, or, consider adopting some of the changes I have proposed ;-)
> Minor lexical improvements to composables.md

- .vitepress/theme/components/PreferenceSwitch.vue
Signed-off-by: Sepush <sepush@outlook.com>
before
after
> fix(PreferenceSwitch): switch-link style overflow

- src/translations/index.md
Similar to this page: https://github.com/vuejs-translations/docs-zh-cn/blob/main/src/translations/index.md
> Add a link to the new released Chinese doc site

- src/guide/scaling-up/routing.md
fixed typo on line 9
changed text to 'responsible'
> fixed typo on line 9

- src/guide/scaling-up/state-management.md
Fix a grammatical mistake in documentation.
"import it ~~from~~ multiple components"
"import it **into** multiple components"
> Update state-management.md (grammar fix)

- src/guide/introduction.md
- src/guide/reusability/composables.md
- src/tutorial/src/step-1/description.md
"In more details" is wrong, there should be no "s" in "details".
"In more detail".
> Fix spelling of an expression

- src/guide/best-practices/performance.md
via https://github.com/vuejs-translations/docs-zh-cn/pull/560
> Variable name fix in performance.md

- src/guide/scaling-up/tooling.md
- src/guide/typescript/overview.md
from https://github.com/vuejs/docs/pull/1989
> fix:update tsc-vue link in two places

- src/tutorial/TutorialRepl.vue
there was an unused and nonexistent module. Idk that it was exist before or not but anyway.
just removed it
> just removing nonexistent module.

- .vitepress/config.ts
Help docs translators to get started for the i18n config easier.
- Added some comments as placeholders.
- Added some type information to avoid config typos.
https://github.com/vuejs-translations/docs-zh-cn/pull/583
> Add placeholder of the i18n config for translations

- .vitepress/inlined-scripts/restorePreference.js
- .vitepress/theme/components/Banner.vue
> Change text to reflect remote event

- .vitepress/theme/components/VueJobs.vue
- src/tutorial/TutorialRepl.vue
hi. saw a warning from TS in VueJobs Page.
sometimes TS gets confused when analyzing our code and yell at us with this message.
```
Property 'x' does not exist on type 'never' in TypeScript
```
simply just use square brackets instead of dot notation to access the property
not so familiar with PR messages so sry about that.
image of that warning
> fix(ts-warning):Property does not exist on type 'never'

- src/guide/built-ins/keep-alive.md
There appears to be a missing pronoun, `it.`
Add the missing pronoun.
> missing pronoun

- src/guide/essentials/forms.md
- src/guide/scaling-up/testing.md
> fix: duplicated id for some headings

- .vitepress/theme/components/VueMasteryBanner.vue
> vue mastery banner mobile fix

- src/about/faq.md
The changes in this PR were originally proposed in #1966.
That PR included various other changes, many of which I wasn't comfortable merging. The original author hasn't responded to the feedback provided, so I've picked out these specific changes so we can get them merged.
> FAQ tweaks

- src/about/team/members-core.json
> chore: update team member

- src/guide/built-ins/transition.md
> Update transition.md to fix a tiny typo.

- src/api/api.data.ts
Unnecessary escape character: \-. 
Remove it.
none
> Removed unnecessary escape character

- src/api/sfc-spec.md
SASS is incorrectly cased.
Sass is cased as such.
> Fix casing of Sass

- src/guide/best-practices/security.md
There were several minor grammar errors, such as missing pronouns and commas.
Fix and improve grammar.
> several small grammar improvements

- src/guide/essentials/watchers.md
This is based on the suggestion here: <https://github.com/vuejs/docs/pull/2144#discussion_r1064070906>.
> Add a clarifying comment to a watcher example

- src/guide/components/props.md
Props is pluralized, thus `have` should be used. :-)
> Update props.md, fix tiny grammatical error

- src/ecosystem/themes/themes.json
New Template order
PrimeVue templates order is fixed and the description section is updated.
> Apollo-Vue order changed and text fixes

- src/style-guide/rules-strongly-recommended.md
Documentation typo on the `computed` word
Rectification of the typo
> fix: typo computed

- src/guide/introduction.md
> Fix Vue Mastery link

- src/guide/extras/composition-api-faq.md
This link provides a high level overview of why the Composition API is valuable and answers many FAQ's about the composition API. 
https://vueschool.io/lessons/introduction-to-the-vue-js-3-composition-api
Thanks!
> Add link to Vue School video lesson

- src/guide/extras/composition-api-faq.md
The link is broken. See https://vuejs.org/guide/extras/composition-api-faq.html#what-is-composition-api
Fix the link.
> Fix broken link

- src/guide/scaling-up/tooling.md
vue-tsk link pointed to 404 page, fixed link to point to correct repo.
> Fix vue-tsc link

- src/guide/typescript/composition-api.md
> Revert "fix: typing component refs"

- src/guide/scaling-up/testing.md
Since Pinia is now the recommended store solution, replacing Vuex in the docs seem appropriate.
I've replaced Vuex with Pinia on the testing page.
> replace Vuex with Pinia

- src/api/options-lifecycle.md
typo/grammar mistake
correct the typo
-
> Fixed single typo

- src/guide/scaling-up/ssr.md
https://nodejs.org/api/stream is 404.
> chore: fix broken url

- .vitepress/config.ts
- src/translations/index.md
I'm pleased to announce that the Ukrainian translation is now completed and we're switching to maintenance mode now! (And switching to other products of the Vue ecosystem).
Big thanks to our Ukrainian community, especially @vozniukvolodymyr, @maxdzin, @nazar1ua, @OlesyaKlochko, @dddarkasss, @winato, @MaksymOsovitnii. 
Proud of you guys!
> Change Ukrainian translation as completed

- src/about/team/members-core.json
Hey guys, adding myself to team page 🤗
> chore: add brc-dd to core team

- .vitepress/config.ts
This PR adds the link to the official certification website.
> Add link to official certification website

- src/guide/essentials/template-syntax.md
> Fix broken URL for restricted list of globals (#2388)

- src/guide/essentials/class-and-style.md
> Update misplaced comma and correct article usage in class-and-style.md

- .vitepress/theme/styles/index.css
- package.json
- pnpm-lock.yaml
The flyout menu height is overflowed when the screen height is limited. See PR https://github.com/vuejs/theme/pull/92.
1. Bumpping the version of `@vuejs/theme`
2. However, there is still a bug with a banner displayed. I added one more line to walk around in `styles/index.css`. This line of code could be removed after this PR https://github.com/vuejs/theme/pull/95 is merged and published further.
Thanks.
https://github.com/vuejs/theme/pull/92
https://github.com/vuejs/theme/pull/95
> fix:the flyout menu height when it's overflowed

- src/guide/essentials/reactivity-fundamentals.md
> Typo in reactivity-fundamentals.md

- src/guide/extras/composition-api-faq.md
When I read “Can I use both APIs together?”, I initially interpreted the question to mean “Can I use both APIs together in the same project?”.
I propse that the question be rephrased to make it clearer that it's about using Composition API and Options API in the same component.
N/A
Closes #2233.
> Clarify Composition API FAQ question (#2233)

- src/guide/components/events.md
- src/guide/components/v-model.md
在我看文档的时候，发现对于多个v-model修饰符的描述信息并没有，然后需要自己去调试测试代码看结果
然后我在原来文档的基础上添加了一个对于多个v-model修饰符的操作文档，可能还需要进一步的改进，希望大家也也能够给予一点建议
->
When I read the documentation, I found that there was no description information for multiple v-model modifiers, and then I needed to debug the test code myself to see the results
Then I added an operation document for multiple v-model modifiers on the basis of the original document, which may need further improvement, and I hope you can also give a little advice
> feat: multiple-v-model-modifiers

- src/guide/components/v-model.md
> docs: remove unnecessary space

- .github/contributing/writing-guide.md
- README.md
- src/guide/extras/ways-of-using-vue.md
- src/guide/scaling-up/ssr.md
> docs: update vitepress link

- src/guide/essentials/reactivity-fundamentals.md
Lexical inconsitency and a slight typo in the verbs
Edited the typo and provided more info that could be a better pointer to what was being discussed
> Changed some typos on reactivity-fundamentals.md

- src/api/reactivity-core.md
The linked section was removed.
I fixed to link another section instead.
> fix: removed anchor

- src/api/render-function.md
it should read 'directive'
as proposed change
none
> fix: fix typo

- src/guide/essentials/event-handling.md
The link contains invalid fragment value.
The link was fixed.
> Fix scroll performance link

- .vitepress/inlined-scripts/restorePreference.js
- .vitepress/theme/components/Banner.vue
- .vitepress/theme/index.ts
> Revert "feat: add vuetoronto23 banner"

- .vitepress/config.ts
- src/translations/index.md
Italian translation is ready to launch
adding translation links
> Italian translation ready to launch

- src/guide/reusability/composables.md
https://vuejs.org/guide/reusability/composables.html#async-state-example
We aren't resetting data and error, also we weren't using `dt` so I stripped it.
Reset reactive data.
> Update composable guide reset values

- .vitepress/inlined-scripts/restorePreference.js
- .vitepress/theme/components/Banner.vue
- .vitepress/theme/index.ts
> Revert "Add Vue Toronto banner - schedule 2"

- src/guide/introduction.md
1. The current "Prerequisites" section doesn't provide enough guidance for beginners to learn these essential technologies before diving into Vue.js. 
2. After reading the introduction page, readers may be unclear on what to read or do next, potentially leading to a disjointed learning experience.
1. Expand the "Prerequisites" section to include more resources for beginners to learn HTML and CSS.
2. Add a “Next Steps” section at the end of the introduction page. This section will guide the reader on which document/page to go to next for further learning.
This addition is aimed at improving the navigational flow of the documentation.
> Updated introduction.md

- .vitepress/theme/components/Home.vue
Special Sponsor section is really messy
> style: fix Special Sponsor loading

- src/guide/components/events.md
It looks like there should be two paragraphs here. The current content has only one newline which will be rendered to a space instead of a paragraph.
Add missing newline.
> Fix incorrect paragraphing

- .vitepress/theme/components/VueMasteryBanner.vue
Change redirection link from https://www.vuemastery.com/pricing/ to https://www.vuemastery.com/holiday
> fix: change redirection link

- src/guide/essentials/template-refs.md
Updates the grammar for template ref to make it clearer
> Correct template ref grammar

- src/about/team/members-core.json
Update my personal information like company, projects, and links.
> Update Jinjiang's personal information

- src/translations/index.md
Add translation info for newly deployed [cs.vuejs.org](https://cs.vuejs.org/)
Repository https://github.com/vuejs-translations/docs-cs
> feat: Add Czech to WIP languages

- src/guide/extras/render-function.md
> docs: add explanation for scoped slots with render functions

- src/tutorial/src/step-2/description.md
Changed "are considered" to "is considered".
Description says `State that can trigger updates when changed are considered reactive`
Description should say `State that can trigger updates when changed is considered reactive`
An alternative would be `States that can trigger updates when changed are considered reactive`. However, in context, I feel like my proposed solution is more appropriate.
https://github.com/vuejs/docs/issues/2688
> Fix: typo of step 2

- src/guide/typescript/overview.md
Fixed a small typo in the documentation.
> fix(docs): typo in documentation

- package.json
- pnpm-lock.yaml
- src/examples/ExampleRepl.vue
- src/tutorial/TutorialRepl.vue
> refactor: upgrade @vue/repl

- .gitignore
- .idea/.gitignore
- .idea/aws.xml
- .idea/codeStyles/Project.xml
- .idea/codeStyles/codeStyleConfig.xml
- .idea/docs.iml
- .idea/misc.xml
- .idea/modules.xml
- .idea/vcs.xml
- .vitepress/inlined-scripts/restorePreference.js
- .vitepress/theme/components/Banner.vue
- .vitepress/theme/index.ts
add vueconf.us banner
added to Banner.vue
should stay active until May 12
> add vueconf.us banner

- src/ecosystem/themes/themes.json
> Added CodedThemes Items

- .vitepress/config.ts
- src/translations/index.md
Add translation link to fa.vuejs.org
Discussions: vuejs-translations/guidelines#6
> Add translation link to fa.vuejs.org

- src/guide/essentials/component-basics.md
> docs: explicitly specify context around v-bind

- .vitepress/config.ts
- src/translations/index.md
I made a review of all pages and I believe Czech translation is now ready to be moved from "In progress" to finished.
The ryu-cho is setup to notify every day about updates in the vuejs/docs repo to keep the translation up to date as well.
> feat: czech translation

- src/api/sfc-css-features.md
The address of the source repository has changed
> docs: modify link

- src/guide/built-ins/suspense.md
added missing anchors on Nested Suspense
> fix: add missing anchors on suspense

- src/examples/src/list-transition/App/style.css
- src/examples/src/list-transition/App/template.html
As noticed in #2813 , I changed tag in example code in [transition group page](https://vuejs.org/examples/#list-transition) from div to li element.
> docs: change tag from div to li element

- .vitepress/theme/styles/inline-demo.css
> align play icon

- src/examples/src/form-bindings/App/template.html
`<pre>` should not put inside `<p>`
References:
https://html.spec.whatwg.org/multipage/grouping-content.html#the-p-element
https://html.spec.whatwg.org/multipage/grouping-content.html#the-pre-element
https://github.com/prettier/prettier/issues/15294
> fix: <pre> syntax error in example code

- src/guide/components/v-model.md
> docs: fix format error in code block comments

- src/about/privacy.md
- src/guide/components/props.md
Recently created sections do not have anchors in headings defined
> docs: missing anchors in new content

- src/guide/best-practices/accessibility.md
Unused comments `common-codepen-snippet` is no longer needed.
> refactor: remove unuseful comments

- src/api/reactivity-core.md
> fix: link to getter function definition

- src/translations/index.md
This PR adds Spanish language as working in progress translations list.
> docs(translations): added Spanish lang as a work in progress

- src/ecosystem/themes/ThemeListItem.vue
- src/ecosystem/themes/themes.json
Hi 👋🏻 
I hope you're doing great. As per our email communication, I've added ThemeSelection in theme vendors. I've also assured that all links are affiliate links.
In addition to vendor addition, I've also
> docs(themes): added ThemeSelection vendor

- .vitepress/theme/components/SponsorsAside.vue
Small follow up to https://github.com/vuejs/docs/pull/2953. I forgot to change the utm when adapting the ViteConf CTA from the vite docs.
Corrected it here.
> chore: correct viteconf CTA utm

- .vitepress/theme/components/Home.vue
There are a few leading spaces in the Home. Extracted from https://github.com/vuejs/docs/pull/2953 so these don't get reverted later.
> chore: remove trailing spaces in home

- .vitepress/theme/styles/style-guide.css
The summary element is missing the cursor: pointer style
> fix: summary add cursor pointer

- src/about/team/members-emeriti.json
Currently defcc mainly works as an Indie Developer. Changes the company homepage to the new one.
Thanks.
Document updation!
> docs: update defcc latest information

- src/about/team/members-core.json
> Update Yiling's personal information

- .vitepress/inlined-scripts/restorePreference.js
- .vitepress/theme/components/Banner.vue
- .vitepress/theme/index.ts
Adding banner for the upcoming VueConf Toronto conference. 
Tagging @yyx990803 for review.
> feat(*): add vuetoronto banner

- src/guide/typescript/composition-api.md
Fixed a typo in TypeScript with Composition API​ documentation.
> fix(typo): typo in composition-api

- package.json
- pnpm-lock.yaml
https://github.com/vuejs/theme/pull/111
> chore(deps): update @vue/theme

- src/guide/quick-start.md
Fixed #2874 
Add new line for yarn v1 users.
> docs (#2874): update quick start instructions for yarn v1

- src/guide/reusability/custom-directives.md
https://github.com/vuejs/docs/pull/2994
Set the right comment
> Fix base on https://github.com/vuejs/docs/pull/2994

- src/developers/developers.json
In developpers.json the content is duplicate and wrong date.
> Fix(developpers): Remove duplicate

- src/api/application.md
The link address for this [useId](https://vuejs.org/api/general.html#useid) in [this section](https://vuejs.org/api/application.html#app-config-idprefix) to have been moved to [this section](https://vuejs.org/api/composition-api-helpers.html#useid).
> Update useId link

- src/guide/essentials/forms.md
> docs(forms): capitalize title

- src/guide/components/v-model.md
#3133 
Change the playground example to match the documentation
> Update playground example for v-model modifiers

- src/guide/extras/render-function.md
added example of template refs for render function with version >= 3.5.0
> docs: update template refs render function

- src/translations/index.md
Co-authored-by: Jinjiang <zhaojinjiang@me.com>
> Add German language links to the translations page

- src/translations/index.md
Use the official website link instead.
> Update German website URL

- src/translations/index.md
Update translations page to list info about progress of Polish translation
> Add polish language to work in progress section

- src/ecosystem/themes/themes.json
> docs(themes): add NuxtUI Pro

- .vitepress/config.ts
- src/translations/index.md
Happy to say that Polish translation of the docs is now complete!
Big thanks to everyone who helped in this initiative: @MateuszMichalowski, @dkasperczyk, @baroshem, @unnunhexium, @Willo0ow, @WawrzenskiPatryk ❤️
> feat: Mark Polish translation as complete

- src/guide/essentials/forms.md
> docs: provide comma

- .vitepress/inlined-scripts/restorePreference.js
- .vitepress/theme/components/Banner.vue
- .vitepress/theme/index.ts
Adds the ViteConf 2025 banner to the docs
> chore. set up viteconf banner
